### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by chiafish** [4ian/GDevelop#6262] opened 2024-01-25 09:40 UTC
### GDevelop version

5.3.187-9eb721662f404d9cc215467ab132bf977fb24121

### Platform info

System Version: 13.3.1, Arch: arm64, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.187 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: darwin

### Additional error context

uniqueErrorId: 1cb611f7-a393-4dcf-859f-2c9badaec002

TypeError: Cannot read properties of null (reading '_batchEnabled')
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1573.fe72a661.chunk.js:2:1953914)
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1573.fe72a661.chunk.js:2:1956079)
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1573.fe72a661.chunk.js:2:1956499)
    at e.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1573.fe72a661.chunk.js:2:1962072)
    at e.val...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aT
    in jT
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in KL
    in div
    in n
    in oa
    in div
    in xO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in u
    in j
    in h
    in h
    in Z
    in d
    in ee
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n...

**Comment by ClementPasteau** [comment] 2024-01-25 09:59
Duplicate of #5997

**Closed by ClementPasteau** 2024-01-25 09:59 UTC
