### ISSUE TITLE
Resources doesn't load after re-importing them

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1048] opened 2019-05-06 08:54 UTC
## Describe the bug
In some cases if you re-import resources the objects can not load them even though they are at the location they should be and the path is correct. It is usually happen when you store resources in multiple sub-folders in the project folder.

**EDIT://** I have just noticed when we scan for images they get referenced by their path in their name while the objects in the scene are looking for the images without reference to the path in the name. That should be the problem.

## To Reproduce
1. Create a new project from the Asteroids example
2. Save it. 
3. Open a new instance of GDevelop, keep the one with the Asteroids game open
4. Create a new empty project
5. Copy all the scenes and events from the Asteroids project over to the new empty project.
6. Copy the assets folder from the Asteroids project over to the new empty project folder.
7. Open the asteroids scene in the new empty project.
8. Edit the player object and add the ship_1.png image to the object, this is to have something in the resources.
9. Go to the resources under game settings.
10. Right click the image in the resources we just added to the player before, select scan for images.
11. All the images should be imported now. Save the project.
12. Close the project, or even close GDevelop entirely. Open the new project again we just closed and the objects doesn't load the images even though they are imported in the resources and the path is correct.

* Please include a link to a game if possible!
https://send.firefox.com/download/4ac2409d2a4e275b/#C3Ey94eSjVfigoA8q2NsUQ
It is the copy that doesn't load the resources for me.

## Other details
* Include any OS/browser version/smartphone that you're using
Pop!_OS 18.04

* Which version of GDevelop are you using? The desktop app or the web-app?
Desktop app version 5.0.0-beta68

* Comment
Would be nice if we could right click in the resources even if there is nothing to scan for resources and if we could hot-reload the project without need to close and open it again.

Thanks.

**Comment by Bouh** [comment] 2019-05-06 15:08
Reference : https://forum.gdevelop-app.com/t/new-video-loader-and-export-problem/18564/1

**Comment by 4ian** [comment] 2019-05-07 11:53
> EDIT:// I have just noticed when we scan for images they get referenced by their path in their name while the objects in the scene are looking for the images without reference to the path in the name. That should be the problem.

Yes that's the "problem". Per se it's not a bug, rather an inconsistency:

* When you add images to objects, images are added with their filenames as the resource name
* When you scan for resources, images that are not in the list of resources are added with their relative path to the project (i.e: folder + filename) as the resource name.

Note that "scan for images" was never meant as a way to "restore" anything, just as a convenient way to add images to your resources :) 

Though I agree it would be best to:
* Always have the relative path to the project (i.e: folder + filename), even when adding resource directly to an object (i.e: same behavior as scan for images).
* If the relative path is including ".." (i.e: if we detect that the images are not in a sub folder of the game), then warn the user "You're adding an image/video/font/audio file that is not located in the project folder. Are you sure you want to continue? It's recommended to always copy your images in your game folder".

or we could copy automatically resources in the project folder, but I'm a bit afraid of causing more confusions ("Help I'm editing my image but it's not shown in the game" "Ah yes, sorry your image was copied into the game folder").

**Comment by 4ian** [comment] 2019-05-07 11:56
cc @blurymind as you've worked on Scan for XXX feature, you might be interested/have advices about how to best import resources and my proposed solution.

**Comment by blurymind** [comment] 2019-05-07 17:51
I think resources should automatically be copied to the projects folder if
they aren't there already and always have relative paths. Resources with
absolute paths should be indicated somehow to warn the user.

Maybe sometimes you would want your project to use a resource from a
template - in the case of prototyping. Some game engines such as rpg maker
let you do that by having an RTP. You can mix and match what's in the RTP
that came with it with your custom resources. But you cannot have resources
scattered Willy nilly at unpredictable user folders and expect them to work
when you start moving stuff. Maybe we should start discouraging that kind
of project management by adding warnings.

In any case I won't be able to look at this atm. I have no proper internet
until the 16th due to housemoving :)

**Comment by blurymind** [comment] 2019-05-16 10:13
if we dont want to allow having resources from outside of the project folder - we can add an indication in the resource manager for those or a pop up message warning when saving or loading a project with such resources.
What do you think is the best approach?

**Comment by Wend1go** [comment] 2019-05-16 16:23
Talking about "re-import", it would be nice to have an additional button in the resources context menu to "re-import" images. This would be useful when you edit images in a separate application and just overwrite the existing image. Currently you need to restart GD in order to see the changed images in the editor.

**Comment by 4ian** [comment] 2019-05-16 19:19
It's true that it's a pain, they are kept in the cache memory I think. Would need to find a way to reset that.

**Comment by blurymind** [comment] 2019-05-16 21:41
There is a button to set the path of a resource - but it has to be done on a per resource basis. The scan commands only work for scanning for resources inside the project folder- so we cant use them for this.
Maybe a new command can be added to do a smart scan of a folder that the user provides and if in it the file name is the same as a resource with a dead path's, assign it to that resource.

**Comment by blurymind** [comment] 2019-05-17 20:27
I have something going in my branch
![warningPath](https://user-images.githubusercontent.com/6495061/57954317-74df9180-78ea-11e9-9174-5cf8a358c248.PNG)
Orange indicates a warning - the resource is outside of the project folder!

Now I just need to add a warning message

**Comment by blurymind** [comment] 2019-05-17 21:14
Here is a warning. Not sure how to best word it:
![warningPopUp](https://user-images.githubusercontent.com/6495061/57956519-271a5780-78f1-11e9-8192-9e70d2c1e932.gif)

**Comment by blurymind** [comment] 2019-05-18 09:46
made a pull for the warnings. The "Reimport missing resources from a path" command will be trickier to do properly, so maybe should be for another pull?

**Comment by blurymind** [comment] 2019-05-18 11:40
What about making the newIde refresh the cache every time the user opens the object properties, where the thumbnails are displayed? Or every time a component that contains resource thumbnails is mounted - refresh the cache?

**Comment by Wend1go** [comment] 2019-05-18 14:44
Sounds good to me, as long as it doesn't slow down bigger projects.

**Comment by Silver-Streak** [comment] 2023-02-05 04:32
This is still an issue/reproducable behavior in 5.1.157. It's pretty commonly complained about in the discord from newer users. 

I think a  fix to this would be to eliminate non-project folder resources entirely AND enable a "standard" folder substructure for users to comply with/make it easier to track their resources, then scan that folder for changes. 
e.g. Take the current assets folder used for the asset store, and add "images" "sounds" "fonts" and "tilemaps" subfolders, and add the appropriate resource to the appropriate path when added to the project.

Doing so would also likely make it easier for things like Piskel and an eventual Tilemap editor to update files live.

**Closed** 2024-10-12 11:28 UTC
Labels: 😤Non optimal UI
