### ISSUE TITLE
P2P Multiplayer Template

### ISSUE THREAD

**Issue by tomekk2006** [4ian/GDevelop#2085] opened 2020-11-10 22:57 UTC
[Multiplayer Template.zip](https://github.com/4ian/GDevelop/files/5520642/Multiplayer.Template.zip)
Use this template to create your own multiplayer game.

**Comment by Bouh** [comment] 2020-11-11 01:54
Duplicate of #2084

**Closed by Bouh** 2020-11-11 01:54 UTC
