### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by PichuMain101** [4ian/GDevelop#2910] opened 2021-08-13 15:42 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
value@https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:408426
xa@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:230854
Uo@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258416
Fo@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258800
Eu@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265836
wu@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265216
Iu@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:266595
In@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:198282
In@[native code]
i@https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:306494
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta114-26f6e95e4629adcb1428e3342c2ccd73d27554a6
* Arch: Unknown architecture (web-app),
* Platform Name: MacIntel,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15,

**Comment by PichuMain101** [comment] 2021-08-13 15:44
Oops I didn’t write anything

**Comment by Bouh** [comment] 2021-08-14 10:33
Duplicate of https://github.com/4ian/GDevelop/issues/2911

**Closed by Bouh** 2021-08-14 10:33 UTC
