### ISSUE TITLE
Text and global object change displayed text on IDE

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1172] opened 2019-07-30 23:22 UTC
## Describe the bug
Text on IDE is changed when object is global

## To Reproduce
Add text, set it to  "Credit : Bouh", add it on scene
Switch this object to Global Object
Text on scene are different and display strange characters like squares or unknown ASCII
And sometimes when i switch scenes in IDE, scene crash, "We encounter a problem" something like this.

![image](https://user-images.githubusercontent.com/1670670/62172050-53ab1080-b331-11e9-9b73-73b977778028.png)

Sometimes text become like text in game.json.
I already saw rgb values with strange ASCII, very strange ^^

Text come back to normal after close/open scene.

## Other details
Win10, B76, maybe in lower version too.

**Comment by 4ian** [comment] 2019-07-31 07:32
Indeed, I've not reproduced the exact same crash/error but also getting some weird behavior.
This is surely due to a memory corruption*, I'll try to take a look asap and release a new version with a fix :)

* These kind of bugs are the worst because they are memory errors either in libGD.js or in the way it's use (like you have a gdSomething object, you delete it and somehow reuse it in another component, which should never be done as it was deleted - hence the "garbage" that you seen on your screen). So a way to reproduce it like you did is very good for debugging them :)

**Comment by 4ian** [comment] 2019-07-31 07:46
The issue here is because when an object is set as global, it's removed from the list of objects of the scene and added to the list of object of the project, destroying in memory the original object and creating a new (identical) one. The problem is that the scene renderer is still pointing to the old object is memory (that does not happen when deleting an object, because there is immediately a call made to remove all the instances of this object on the scene).

**Comment by 4ian** [comment] 2019-08-01 20:06
This is fixed in: https://github.com/4ian/GDevelop/commit/4cc6048e74d9679b8fcf52cb30b7d3482924b995

The fix is here: https://github.com/4ian/GDevelop/commit/4cc6048e74d9679b8fcf52cb30b7d3482924b995#diff-036af786a6483adfbaf7a11277c66dd7R439 - with the new function, the object is not destroyed and re-created in memory. This is important because the scene editor, to render instances, is keeping references to objects in memory. As the object was moved in memory, it was pointing to an invalid memory area.

> I already saw rgb values with strange ASCII, very strange ^^

If this happen, be careful and see if you can reproduce it when re-opening the game :) This is most probably memory corruption/wrong usage of libGD.js and should be fixed asap.

If this happen btw, make a copy of your game file, then save (but make a copy before in case the save is corrupted - unlikely better safe than sorry), and *close and reopen GD* (to start from a "fresh" libGD.js, without potential memory corruption).

**Closed by 4ian** 2019-08-01 20:06 UTC
Labels: 🐛 bug, 💥crash
