### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by pushka124** [4ian/GDevelop#2742] opened 2021-06-14 06:00 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at la (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:128865)
    at Aa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:132740)
    at ja (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:136303)
    at https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149572
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:160339)
    at Su (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149506)
    at Tu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149282)
    at Eu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:148627)
    at je (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:155032)
    at Ue (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:61340)
    at On (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:81951)
    at https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149976
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:160339)
    at Nu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149900)
    at Nn (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:81693)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:363571)
```

## Component stack (don't write anything here)
```

    in Unknown
    in ul
    in ForwardRef
    in ForwardRef
    in n
    in div
    in ForwardRef
    in div
    in Unknown
    in n
    in div
    in a
    in o
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in u
    in E
    in div
    in n
    in u
    in a
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta110-350fea08bf5af9e0ff3b06c4d244e8f5a55472a7
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48,

**Comment by Bouh** [comment] 2021-07-10 13:09
Duplicate of https://github.com/4ian/GDevelop/issues/2767

**Closed by Bouh** 2021-07-10 13:09 UTC
