### ISSUE TITLE
Pairs example Uncaught Type Error when preview

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1032] opened 2019-04-22 08:50 UTC
## Describe the bug
When I run preview I get this error:
```
Uncaught TypeError: gdjs.NewSceneCode.GDcard_95blowfishObjects4[i].getBehavior(...).addObjectPositionTween is not a function
    at Object.gdjs.NewSceneCode.eventsList0x737288 (code0.js:320)
    at Object.gdjs.NewSceneCode.eventsList0x727e80 (code0.js:386)
    at Object.gdjs.NewSceneCode.eventsList0x727de0 (code0.js:426)
    at Object.gdjs.NewSceneCode.eventsList0xb2958 (code0.js:1862)
    at gdjs.RuntimeScene.gdjs.NewSceneCode.func [as _eventsFunction] (code0.js:2019)
    at gdjs.RuntimeScene.renderAndStep (runtimescene.js:232)
    at gdjs.SceneStack.step (scenestack.js:30)
    at runtimegame.js:354
    at gameLoop (runtimegame-pixi-renderer.js:380)
```

## To Reproduce
1. Create a new project with the example
2. Launch preview.

## Other details
Running on Pop!_OS 18.04

**Comment by 4ian** [comment] 2019-04-22 09:31
I just downloaded beta 66 on Windows and macOS, and both a running the example fine.

Can you confirm that this is happening from a fresh install? Maybe some Linux specific issues - can anyone else reproduce this issue? But that's very strange because the packaging is exactly the same for all OSes.

**Comment by 4ian** [comment] 2019-04-22 10:12
Was it on the web-app? I fixed a similar issue.

**Comment by Wend1go** [comment] 2019-04-22 10:13
Just tested the electron version on Linux Mint without any issues

**Comment by 4ian** [comment] 2019-04-22 10:19
Cool thanks :) I guess it was on the web-app then. I fixed the issue (game engine was out of date), make sure to clear your cache when refreshing the web-app.

@ddabrahim Close the issue if that works for you :)

**Comment by ddabrahim** [comment] 2019-04-24 17:05
Yes it was the web-app, sorry forget to mention.
It works now.
Thanks.

**Comment by 4ian** [comment] 2019-04-24 18:28
Cool :) Close the issue if it's ok for you so that we don't keep open issues for nothing.

**Closed by 4ian** 2019-04-24 18:28 UTC

**Comment by 4ian** [comment] 2019-04-24 18:31
I've updated the bug report template so that it ask if you're running the desktop app or web-app: https://github.com/4ian/GDevelop/blob/master/.github/ISSUE_TEMPLATE/--bug-report.md
