### ISSUE TITLE
Arrow functions on IE don't load the game

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1237] opened 2019-09-26 11:47 UTC
## Describe the bug
Arrow functions are used in *jsonmanager.js*, this arrow prevents the launch of the game.

![image](https://user-images.githubusercontent.com/1670670/65685309-f649ec00-e061-11e9-9432-bdb928de36cf.png)

[IE compatibility](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility)

## To Reproduce
1. Open Isometric example
2. Export web online
3. open it on IE 

## Other details
* b80, w10, IE

**Comment by GustavoMarciano** [comment] 2019-09-26 14:11
Adding to this problem ,the tween behavior also prevents the game from starting in internet explorer, to reproduce just create any example add a behavior and create a tween.

**Comment by 4ian** [comment] 2019-09-26 16:59
I thought the tween behavior was fixed, at least there is no arrow functions in https://github.com/4ian/GDevelop/blob/master/Extensions/TweenBehavior/tweenruntimebehavior.js

If you have the error message, that would be useful :)

**Comment by GustavoMarciano** [comment] 2019-09-26 17:49
@4ian 

![Capture](https://user-images.githubusercontent.com/23220658/65712180-ce13ba80-e06c-11e9-89a6-a0a516e563f9.PNG)

**Comment by Bouh** [comment] 2019-09-26 19:47
IE 11
![image](https://user-images.githubusercontent.com/1670670/65719869-07691c00-e0a7-11e9-9abb-745245e04ae2.png)
But console is clear about that, arrow is selected. it's for me the only issue visible in console.

**Comment by 4ian** [comment] 2019-09-26 20:14
@Bouh Actually this is already fixed :) After the merging of the Skeleton extension, this was fixed in the PR: https://github.com/4ian/GDevelop/commit/12c5df67fa1a698838bb9ce66c2729639d5ebdf6#diff-c9dda1f48c012f5c121bbcba5ee43c01R93

**Comment by GustavoMarciano** [comment] 2019-09-26 20:25
I removed my comments to make it clear that was another issue!

**Comment by 4ian** [comment] 2019-10-01 21:41
Closing as this issue is fixed already

**Closed by 4ian** 2019-10-01 21:41 UTC

**Comment by GersteDeKorn** [comment] 2020-12-30 18:54
I've found another arrow-function that stops the game from loading in IE 11
Thats in gd.js on line 369 in the function gdjs.makeUuid

![grafik](https://user-images.githubusercontent.com/66431005/103374271-6b169c00-4ad7-11eb-9d06-9087e316d264.png)

Do you know [Babel.js ](https://babeljs.io/)? I dont know if that fits to your architecture but it compiles ES6 javascript into browser-compatible javascript

**Comment by 4ian** [comment] 2020-12-30 20:12
Unfortunately starting from GDevelop 5.0.0-beta101, we don't support anymore Internet Explorer 11 nor Android 4. These are too old (IE 11 has not been updated in 7 years), don't run WebGL (so performance is poor) and would be way too much work to support longer for a poor result (there are tons of web standards not supported in IE11).
Note that we do use Babel for the editor but not for the game engine. 

If you absolutely need to support IE11, you can try to use GDevelop 5.0 beta 100 (https://github.com/4ian/GDevelop/releases) or try to run babel yourself with configuration to support IE11 on the exported files (but the result is not guaranteed ;)) (you could set up a script to run on your game after it's exported to run babel on all files).

**Comment by GersteDeKorn** [comment] 2021-01-02 13:21
Thank you for the quick and detailed answer!
That you do not support IE11 also makes perfect sense to me, adding the support would only slow down your application ;)

Since I need to support it unfortunately and the game does not need much performance, I ran the export through Babel. This worked great, but I should mention for other users with the same problem that you have to configure Babel so that it does not append the "strict mode".

**Comment by 4ian** [comment] 2021-01-02 21:28
Good to know, thanks for following up 👍
