### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by gabeio64** [4ian/GDevelop#6079] opened 2023-12-14 02:32 UTC
### Describe what you were doing when the crash happened

i just opened a scean and it crashed???

### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: ab980e9a-68cd-4893-8039-b7c9d13551b3

RuntimeError: memory access out of bounds
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:wasm-function[76]:0x277f5
    at gdObject.GetName.gdObject.GetName [as getName] (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:1148114)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1433750
    at Array.map (<anonymous>)
    at file:///C:/Program%20Files/GDevelop/resources/app.a...

### Additional component context

    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c...

**Comment by AlexandreSi** [comment] 2023-12-14 08:43
Hi @gabeio64,
Sorry for the inconvenience.
Is the issue still happening? Was it a scene of your game or a scene of an example?

**Comment by ClementPasteau** [comment] 2024-01-03 09:55
Possible duplicate of #6052 
Need more info to fix

**Closed by ClementPasteau** 2024-01-03 09:55 UTC
