### ISSUE TITLE
Keyboard shortcuts issues when copy/pasting instances

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1115] opened 2019-06-16 16:18 UTC
## Copy and paste instances renders scene uneditable
Starting on first tutorial. Adding tile object, then trying to copy/paste it breaks the ui and have to reload the game to be able to select the objects.

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Go to http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/platform-game/start
2. Download the resources
3. create blank game
4. Add player object as in tutorial
5. Add platform object as in tutorial

<img width="888" alt="Screen Shot 2019-06-16 at 9 00 14 AM" src="https://user-images.githubusercontent.com/8691/59566448-51a52080-9015-11e9-99ba-de4a75ba163d.png">

You see the platform is "selectable" and has the resize icons.

6. click the platform object to select it.
<img width="794" alt="Screen Shot 2019-06-16 at 9 02 29 AM" src="https://user-images.githubusercontent.com/8691/59566464-84e7af80-9015-11e9-92e4-6f37f32a9a61.png">
7. Ctrl-click on object to bring up context menu.
<img width="443" alt="Screen Shot 2019-06-16 at 9 03 20 AM" src="https://user-images.githubusercontent.com/8691/59566481-a9438c00-9015-11e9-9aee-b2c32c928dbc.png">
8. Choose "copy".

Things start getting weird. The object now seems stuck to my cursor as I move around. I move the mouse up a bit and click, now I see this:

<img width="717" alt="Screen Shot 2019-06-16 at 9 04 55 AM" src="https://user-images.githubusercontent.com/8691/59566502-00496100-9016-11e9-96ef-cf1ae5f85aa5.png">
9. Now, nothing is "selectable" except the original tile element. Clicking on anything else just puts a focus ring, but no resize UI. It sticks to the current element. Everything is more or less busted now, as I cannot move any other object or select any other object.

Also, if I click the resize handler, it instantly makes a copy of the tile object again and places it right over the other one. 
See screenshot
<img width="818" alt="Screen Shot 2019-06-16 at 9 07 18 AM" src="https://user-images.githubusercontent.com/8691/59566528-69c96f80-9016-11e9-9507-4470ed5d78ae.png">

It's as if with the "copy" action we have lost focus on the right object, but some references are now on the new one, and things are messed up.

## other details

This is on a macbook pro, using desktop version of gdevelop 

<img width="584" alt="Screen Shot 2019-06-16 at 9 12 05 AM" src="https://user-images.githubusercontent.com/8691/59566577-db092280-9016-11e9-93f1-4d468a6b232c.png">

Here's the project file:
[My project3.zip](https://github.com/4ian/GDevelop/files/3294297/My.project3.zip)

**Comment by triptych** [comment] 2019-06-16 16:26
Created a short quicktime movie. When you see the mouse over the other elements with no resize UI popping up it's me trying to click on them to select them. 

[bugged.mov.zip](https://github.com/4ian/GDevelop/files/3294304/bugged.mov.zip)

**Comment by 4ian** [comment] 2019-06-16 16:29
This might be related to the "Ctrl" Click. What happen if you redo all of this but using right click (with the mouse, check the options in the preferences panel of macOS).

This is also surely partially due to the fact that keys press are not properly handled if done when a menu is opened. Try to redo of all this but press and release Ctrl - and it should unlock again the proper selection of objects?

**Comment by triptych** [comment] 2019-06-16 16:34
I will try when I get a mouse connected. I'm on a laptop which uses a touchpad area, no "right click" available.

**Comment by triptych** [comment] 2019-06-16 16:36
And yes, pressing `ctrl` again after dragging seems to free up the UI again. Objects are selectable once again after doing that.

**Comment by 4ian** [comment] 2019-06-16 16:37
Using two fingers should trigger a right click - at least that's how I do :) Might be something to configure in OS settings.

> And yes, pressing ctrl again after dragging seems to free up the UI again. Objects are selectable once again after doing that.

Nice, so I see the reason, will think about a fix.

**Comment by triptych** [comment] 2019-06-16 16:38
Thanks! I learned something new ( two finger context menu ) . Copy / paste using that method works as expected.

**Comment by Silver-Streak** [comment] 2021-07-25 15:50
@4ian As I'm going through older issues, I saw and tested this out. This appears to still be an issue (Ctrl+clicking on something will still act like ctrl is held even after you release it, until you hold it again).

Is the source of this known/fixable?

**Comment by 4ian** [comment] 2021-08-09 12:05
Sorry for the late reply, this is indeed still a problem on macOS at least - were you able to reproduce this on other OS too? 
And more generally we still have the problem of "stuck" keys, because of how we handle the keys.

**Comment by Bouh** [comment] 2023-03-21 15:44
Hello,
If someone have a macOS please tell us if this bug is still there.
It is not reproducible with version GDevelop 5.1.159 on Windows.
Without messages within 15 days this bug report will be closed as resolved.

**Comment by AlexandreSi** [comment] 2023-06-23 07:37
Closing this since I think that we removed the possibility to open the context menu with a Ctrl+Click.

**Closed by AlexandreSi** 2023-06-23 07:37 UTC
Labels: 👌good first issue, 😤Non optimal UI
