### ISSUE TITLE
Physics collision is not being detected in 5.0.138

### ISSUE THREAD

**Issue by andreholtz2** [4ian/GDevelop#4060] opened 2022-06-23 02:16 UTC
When updating my game [Ball Challenge 2](https://www.crazygames.com/game/ball-challenge-2)  I noticed something strange with the physics.

I updated to version 5.0.138 but the physics collision bug still persists.
In version 5.0.136 everything worked perfectly, as in the video below. (note the sound and bounce)
https://user-images.githubusercontent.com/89740251/175190696-68f25ae1-d646-4d03-b9e6-76b2d3d4817b.mp4

When the ball touches the ground it makes a sound and has the effect of bouncing.

In the video below, in the version 5.0.138 note that the debug text doesn't check for non-collision with the ground, so the effects that were supposed to occur when the ball bounced don't work correctly.
https://user-images.githubusercontent.com/89740251/175190701-1c691c42-2d0f-453f-b437-edea0acafd82.mp4

Here is the debug event that checks for collision.
![bug2](https://user-images.githubusercontent.com/89740251/175192749-b1d91b87-c30a-44f2-8ba5-ec482c33f5bb.png)

Things I've already tried:
- Remove and put the physics behavior;
- Remove the trigger once;
- Change the ball's collision;

**Comment by ClementPasteau** [comment] 2022-06-23 08:18
Thanks for reporting @andreholtz2 
That's strange as we rolled back the change that introduced the bug 🤔 
We're looking into it.

**Comment by AlexandreSi** [comment] 2022-06-23 08:43
Have you tried using the condition `Started colliding` to trigger bounce and sounds?
I guess your project is too sensitive to be sent over, do you think there might be a way you can extract just the part that allows to reproduce the situation?

**Comment by 4ian** [comment] 2022-06-23 09:33
I've made a quick check with what should be equivalent events:
[Test physics ok with sounds.zip](https://github.com/4ian/GDevelop/files/8965964/Test.physics.ok.with.sounds.zip)

But things seem to work properly, in this example at least?
The sound is just played once when the collision occurs (this can be twice in a row if the Coin object bounces a tiny bit).

@andreholtz2 If you can compare my example with your game, this would help us to reproduce your problem :)

**Comment by andreholtz2** [comment] 2022-06-23 18:39
@AlexandreSi Yes, I already tried this. Still the same. 
@4ian I think I found what might be going on. The example below shows that when the tween occurs the physics does not detect the collision.

[Test.physics.ok.with.sounds.zip](https://github.com/4ian/GDevelop/files/8969995/Test.physics.ok.with.sounds.zip)


When the tween effect is removed it works.

**Comment by krunkster** [comment] 2022-06-23 18:49
I found the problem: Disabling Physics Behavior on an object that is currently in collision, will permanently remain in that collision with that object after re-enabling the behavior, even when the collision with that object stops.
[issue-4060.zip](https://github.com/4ian/GDevelop/files/8970122/issue-4060.zip)
The sample here should be fairly self explanatory, but essentially it is a ball that you can move by clicking, and there is an idle timer to stop the ball moving after being in collision for a period of time.  This idling toggles the physic behavior on the ball, which induces the bug I described above where collisions will persist.
Let me know if you need me to open a separate issue, but I believe it's likely all related.

**Comment by krunkster** [comment] 2022-06-23 19:43
@andreholtz2 Your sample project did not contain the wav file... and it played around with your sample, and discovered it's not the tween that causes the problem. It's changing the scale of the physics object! This action seems to make the object retain all off the currently collisions in perpetuity.

Maintainers, I've also experimented further and determined that these "persistent collisions" are asymmetrical, in that only the Object that is modified (Behavior removed/added, scale changed) retains the persistent collisions with the other Physics objects.  The other objects correctly clear their collisions with the bugged object. (i.e. the ball in my demo and the coin in Andre's)

**Comment by andreholtz2** [comment] 2022-06-23 20:10
@krunkster Yes, I didn't even test the sound 😆 I just took the 4ian sample project to check the collision  =) . The problem really is with the scale. Thank you for the sample.

**Comment by krunkster** [comment] 2022-06-23 20:39
Ok boys, I think I've found the issue in the code and the a potential fix:
Essentially based on my read of physics2runtimebehavior.ts it appears that you are using a "currentContacts" array of Behaviors objects.  I didn't find where this array is having objects added/removed, but I could tell that the way that you are looking for existing Behaviors in that array is currently susceptible to this issue at hand.  Essentially you are using a closure like this:
`behavior1.currentContacts.some((behavior) => behavior.owner === object2)`
This is problematic because as my and Andre's demos show the object signature can change between frames, which defeats the "===" operator.
So instead it is likely you will need to instead switch to using conditionals like:
`behavior.owner.persistentUuid === object2.persistentUuid`

Now that's just a guess, since I didn't look up what "persistentUuid" is supposed to be used for, but I'm guessing it's sufficient in this case to check whether or not the Behaviors in the "currentContacts" list match.

**Comment by AlexandreSi** [comment] 2022-06-24 09:15
Thanks for the diagnostics, I'll have a look.
I'm not sure the equality test is the problem here since it's used a bit everywhere, but you never know!

**Comment by AlexandreSi** [comment] 2022-06-24 15:04
Here is my progress so far: there seems to be an interaction between the scale and the physics engine.
In the example, the scale is lowered to 0.7 and the physics engine seems to not being able to detect the end of a contact in that case.

By default, the physics engine will use the object height and width to define the size of the physics body of the engine.

So when you change the scale of the object, you also change the dimension of the physics body of the object.

You can test it out by setting the dimension in the coin behavior:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/32449369/175563057-67c347b7-bc63-407f-9f98-50bda734ca50.png">

When doing this, changing the scale of the object won't change the dimensions of the physics body and the bug should disappear.

I'll have a look at removing this interaction and see if the physics engine can detect the end of a contact when an object changes its size.

**Comment by AlexandreSi** [comment] 2022-06-24 15:54
Update: box2d (the physics engine) correctly detects the end of the contact, but when resolving the contact at the end of the pre events, after the world has been simulated, some contacts disappear from the list `contactsEndedThisFrame` so they cannot be removed from the list `currentContacts` and we consider they are in contact for the rest of their lives.

**Comment by 4ian** [comment] 2022-06-24 16:46
Update everyone: we'll debug that on Monday with @AlexandreSi - hopefully we'll have something fully fixed early next week!

**Comment by AlexandreSi** [comment] 2022-06-29 12:47
Here is a sumup of the situation:

Contacts are detected thanks to a contact listener that triggers a callback on every start/end of a contact.

When I introduced the logic to detect contacts that happen during a frame, I introduced a notion of temporality, considering that every contact happens at a given time (when we launch the simulation of the physics engine (box2d) in the `preEvents`).

The thing is that box2d triggers contact callbacks outside of the simulation, namely on each change of the body that can change contacts (resize, body creation/destruction, something else?).

Today, during the lifecycle of a frame, we can split the timeline in:
```
<------ preEvents ------> | <------ events ------> | <------ postEvents ------>
```

Contacts can happen in each of these phases (non exhaustive list):

```
<------ preEvents ------> | <------ events ------> | <------ postEvents ------>
  box2d simulation          action delete object       Update of the object body following a change of scale
                                                       Delete object in behavior post event
```

We should be able to detect collisions, start of collision and end of collision in each of this phase. During frame 1 `events`, every collision that happened during frame 0 `postEvents`, frame 1 `preEvents` and frame 1 `events` should be detected.

```
<----------------- frame 0 -----------------> | <----------------- frame 1 -----------------> | <----...
 < preEvents > | < events > | < postEvents >  |  < preEvents > | < events > | < postEvents >

...ed during frame 0 events ]
                            [ contacts to be detected during frame 1 events ]
                                                                            [ to be detected during frame 2 events ]
```

This has to be implemented smartly to avoid having to empty and full up arrays on each phase.

---

Notes:
- At some point, I think that the contact listener will need to know the phase during which it triggers callbacks.

---

This needs quite some work to make sure we implement something that works.
We might not be able to do it right now. Is this bug blocking you @andreholtz2 @krunkster or anyone seeing this message? 
We don't want you being blocked publishing releases for your games if this takes too much time to be fixed. If it's blocking you, we could consider reverting my initial fix that was only the tip of the iceberg.

**Comment by andreholtz2** [comment] 2022-06-29 13:42
Hello, @AlexandreSi . I managed to adapt my game to this new version. I used fast tween instead of normal scaling and it seems to work. For other things (like sound and ground impulse contact) putting "Started Colliding" worked. Thanks everyone for the support!

**Comment by krunkster** [comment] 2022-06-30 16:20
I think there is a good chance that #4074 will solve my issues.  I apologize if my arm chair analysis has been distracting, I should figure out how to build the source and contribute sometime.

**Comment by fannieyan** [comment] 2022-07-06 15:42
Hello there!

We have been working on this issue and worked out something that should fix our problems.

Could you please download those experimental builds and try out on your end that the conditions work as expected? They are the builds created from #4074 .
I advise you to make a back up of your project before opening it with this build since it is still experimental.

Mac: https://www.dropbox.com/s/3uo2gs1r9v9hjs4/GDevelop%205-5.0.138-mac.zip?dl=0
Linux: https://www.dropbox.com/s/uk70bxay8pmffmc/gdevelop-5.0.138.zip?dl=0
Windows: https://www.dropbox.com/s/z9fuz1dpqas7d11/GDevelopWindows.zip?dl=0

(tell me if the links don't work!)

We hope it will be satisfying!

**Comment by 4ian** [comment] 2022-07-08 15:37
@krunkster @andreholtz2 if you have 15 minutes to quickly try this new version, this would help to confirm if collisions are now always detected properly :) Let me know!

**Comment by andreholtz2** [comment] 2022-07-08 15:55
@fannieyan @4ian Yes! For me it works correctly! 👏👏👏 Thank you all guys!

**Comment by krunkster** [comment] 2022-07-08 19:46
I apologize I missed the notification on this thread!
Yes it works for my game and my example demo of the bug.
Thank you for addressing this issue!

**Comment by krunkster** [comment] 2022-07-08 21:40
FYI After a couple of minutes of testing I did encounter a hard crash of the physic simulation.
[issue-4060.log](https://github.com/4ian/GDevelop/files/9075167/issue-4060.log)
There are three stack traces included in the above log.
The last one threw repeatedly and stayed hung throwing it over and over.  The first two were the ones that preceded the hang.
I'm not sure if this is due to this test release being an early build, but since the stacks looked directly relevant to the Physics Behavior I wanted to let you know to watch out for this.

**Comment by AlexandreSi** [comment] 2022-07-11 08:36
Hi @krunkster,
What an emotional journey!
Could it be possible for you to share your project so that we can try it out?

**Comment by 4ian** [comment] 2022-07-11 09:34
You can share this privately with us (on Discord for example, or by email), or if you manage to reproduce this in a small example that's obviously better (though I understand this can take a fair amount of time, do whatever is the fastest for you).

I've looked quickly at the code of the new branch with the fix and can't see anything obvious that would trigger this error (we're not changing any object transform during a world's `Step` method or during a callback `BeginContact`/`EndContact`...). Must be an edge case that we skipped or did not think about.

**Comment by krunkster** [comment] 2022-07-11 20:00
I'm not against sharing my project privately with you, but it's in such an alpha state that it would take a while to even explain how to play the game long enough to reproduce. Would a private liluo upload be sufficient, or do you need a zip?

Unfortunately, or I guess it's good news, I played by game for over 20 minutes in a row today and did not see any errors like this. Bad news is, I don't know how to help isolate what I did see previously...
It did happen multiple times though... so I am afraid there is something here... However, there are a few circumstances that may let us write this off:
First, I believe I was running in "debug" mode both times I saw the issue before, which I normally don't do, I was trying to verify some perceived performance impact from the fix. 
Second, before the crash the first time I believe I used the "update" feature to hot swap in some changes.

I seem to remember in my first game I made in Gdevelop that using the "update" feature could have unintended consequences, but when I got your preview build I was trying to test some corner cases and used the "update" feature without much thought... until now.

So I'm comfortable blaming debug mode and "update" as potential catalysts for these hangs... if you agree it's plausible.
I will still keep looking out for any exceptions in the console and try to get my game into a shareable state in case I am able to isolate the issue outside of debug mode.

**Comment by krunkster** [comment] 2022-07-11 22:12
Okay, I decided to open a separate issue #4095 to help further isolate the crash I saw while testing the fix for this issue.
I believe it is likely a precursor to causing a full crash of the physics simulation.
I don't remember seeing the issue before this fix, but I think probability is higher that it is unrelated to this fix.

**Comment by 4ian** [comment] 2022-07-12 08:58
Thanks @krunkster! Super helpful (as usual :)).

Let's continue on the other issue then. It's possible the "hot reload" might play a role in this, though it should not happen while the simulation is being run. Or was it somehow run in between two callbacks when the world is simulated?

This might be unrelated to the fix, so I think we'll merge the fix (it's better anyhow, and André Holtz also checked with his game so it sounds safe), release a new version (without auto update, so that only power users can try it), and we'll see in the meantime if we can reproduce the other issue!

**Closed** 2022-07-12 12:46 UTC
