### ISSUE TITLE
"Flip object horz." on platformer allows jumping after wall contact

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3312] opened 2021-11-30 15:21 UTC
This is a very complex bug and I can't say what could be the origin for it. I feel like it has something to do with the platformer character checking ground while inside of ground.

## Describe the bug

A platformer character is granted another jump when not in contact with a wall/platform anymore if the player is using a custom (smaller) hitbox and is flipped horizontally.

## To Reproduce
1. Create a "player" object
2. Change/Decrease hitbox size

![image](https://user-images.githubusercontent.com/83909121/144074897-fb287cb7-29dd-444c-be3e-80d409252535.png)

3. Give it the **platformer character** behavior
4. Create a "wall" object
5. Give it the **platform** behavior
6. Add following events:
> *Left key is pressed, player is not horizontally flipped > flip hor.: yes*
> *Right key is pressed, player is horizontally flipped > flip hor.: no*

![image](https://user-images.githubusercontent.com/83909121/144072347-a0bfd616-d3ad-4b2c-ad46-ff6260d492d7.png)

7. Start preview
8. Jump at wall (hitbox player **is** in collision with hitbox platform)
9. Flip the character / move away from wall while being airborne (hitbox player **not** in collision with hitbox platform)
10. Jump again (without "touching" ground/floor)
*(Go to 8.)*

## Note

- Smaller/custom hitbox **is mandatory** and won't work without!
- Flipping character **is mandatory** and won't work without!
- Triggering "flip: yes" and "flip: no" only once will not prevent it

## Video

https://user-images.githubusercontent.com/83909121/144070267-b130ab3a-2acb-4f4f-a895-469c736bfd27.mp4

![image](https://user-images.githubusercontent.com/83909121/144073822-5387940e-f5eb-4dd1-8bf8-f78a3329b914.png)

## All Events

![image](https://user-images.githubusercontent.com/83909121/144070419-04914f6b-c048-4678-9143-b77eefd642b6.png)

### Game controls

**Move:** Arrow keys *(platformer default)*
**Jump:** Space, Shift *(platformer default)*
**Toggle debug boxes:** Left Control (LControl)
**Restart scene:** R
**Exit game:** Escape (Esc)

### Project files

.json Project file (should download assets upon opening): [game (3).zip](https://github.com/4ian/GDevelop/files/7626658/game.3.zip)
Web example: https://game-previews.gdevelop-app.com/1638283835649-844836/index.html

## Other details
GDevelop 5.0.122 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by Bouh** [comment] 2021-12-01 21:34
@D8H 
Is that can be related to the recent changes on platformers?

**Comment by D8H** [comment] 2021-12-01 23:24
> @D8H Is that can be related to the recent changes on platformers?

It could, but only the json is attached, I can't try to reproduce it.

@Elairyx7301 Please, can you attach the whole project?

**Comment by Elairyx7301** [comment] 2021-12-02 05:47
As said, that should be the whole project. The assets are download upon opening the .json and the project is the exact same that shown in the video. I can provide you the full project in few hours but what is not working with the .json file?

**Comment by Elairyx7301** [comment] 2021-12-02 13:08
[project.zip](https://github.com/4ian/GDevelop/files/7642106/project.zip)
@D8H Here is the full project with all files. I'm still curious, what happened when you only opened the .json file? Would it not download the assets?

**Comment by D8H** [comment] 2021-12-02 13:09
> [project.zip](https://github.com/4ian/GDevelop/files/7642106/project.zip) @D8H Here is the full project with all files. I'm still curious, what happened when you only opened the .json file? Would it not download the assets?

Ok, I didn't know about asset auto downloading. I'll check.

**Comment by D8H** [comment] 2021-12-02 13:41
This is not a bug, the collision mask is not at the center so it move when the object is flipped.

Try to center the hitbox, like this:
![CenteredCollisionMask](https://user-images.githubusercontent.com/2611977/144432819-2142b926-d271-4ee8-9961-e1fdc0684b35.png)

I still checked with version 121 and the platformer works the same.

**Comment by D8H** [comment] 2021-12-02 15:38
> Ah, I see. So it is that after flipping, the hitbox is inside the ground so it will give the player back its jump?

Yes

> Even though this sounds logical, it still doesn't feel intuitive. Do you think there should be done anything regarding this like only give jump ability when player is on ground or a warning for the user etc.?

First, using custom hitboxes on a platformer character is not recommended. The platformer behavior could check if the character is pushed strictly horizontally but I don't think it would be a good idea because it could have side effects on cases that are actually useful.
At least, it allowed you to find a mistake on the hitbox, I would guess it's a good thing.

**Comment by Elairyx7301** [comment] 2021-12-02 15:47
Thank you for clearing that up!

**Comment by AlexandreSi** [comment] 2021-12-09 13:45
Hi there! Thanks for reporting and discussing this issue @Elairyx7301 and @D8H.
From what you said, I gather there is not much to do. Should we close the issue? Maybe documentation somewhere around the platformer?

**Comment by Elairyx7301** [comment] 2021-12-09 20:12
I think spreading awareness about such things is always great. Where do you think would that be done best? In the doc/wiki, the behavior or directly when changing the hitbox?

**Comment by AlexandreSi** [comment] 2021-12-10 10:12
I would say when changing the hitbox, the other places you mention seem to be more general and could scare the users.

In the collision mask editor, we could check if the sprite has the platformer behavior and display a warning?
@4ian what's your opinion on this?

Just an idea: here we have an unexpected phenomenon between a built-in behavior and a built-in action. But we could have a class that registers those known unexpected phenomenons/conflicting behaviors (built-in or not) and display a warning in different parts of the IDE when we detect a conflict is possible.

**Comment by 4ian** [comment] 2021-12-10 11:46
> Just an idea: here we have an unexpected phenomenon between a built-in behavior and a built-in action. But we could have a class that registers those known unexpected phenomenons/conflicting behaviors (built-in or not) and display a warning in different parts of the IDE when we detect a conflict is possible.

Totally, that's an idea that I usually put inside the card of "diagnostic report": https://trello.com/c/IiLgNR16/462-add-a-diagnostic-report-to-warn-about-potential-issues-in-the-game-and-show-them-in-the-events-sheet
that would both act as 1) a way to report almost certain errors (like a bad expression) and 2) a way to run a "linter" on the project for "known" bad structure/usage.

But without going this far, we could some ad hoc warnings like one here for the platformer behavior and a sprite with custom hit boxes.

**Comment by Elairyx7301** [comment] 2021-12-10 17:02
Thanks to all for working on this!
I see there are other issues open about it so therefore I will close this issue now 🙂

**Closed** 2021-12-10 17:02 UTC
Labels: 💨 Technical debt removal
