### ISSUE TITLE
Idea - Automatically show default variables on each instance

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GDevelop#477] opened 2018-04-22 17:51 UTC
Hi, just had a simple request, from now, creating a variable in an object from the object list, and then use this object in the scene would not show it own variable in the object info panel.
This gif may show you what im talking about:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/19387127/39098073-9dcc934e-4665-11e8-9458-47d0ba394ba7.gif)
It would be much easier to have those variables too when we place the object in the scene than creating them back manually, in this gif exemple, my panel would say the text that is in his own variable, so each panel has different text, so I have to edit the variable for each. Same if I want a lever to open a certain door and each lever got a variable "door" with a different number, etc..

**Comment by blurymind** [comment] 2018-04-25 08:34
That seems like a bug

**Comment by 4ian** [comment] 2018-04-25 08:55
It's not a bug: instances can have variables that will overwrite the variables declared in the object.
It may still be useful to display existing object variables in gray or something like this so that it is clear that object variables already exists and that you're going to add new or overwrite existing ones in the instance variables.

**Comment by Jeje2201** [comment] 2018-04-25 09:05
Yes @4ian that's what @Lizard13 told me.
That's the usefull part I'm talking about, might help and would be faster, like if for some reason we have way more default variable on some object, instead than rewrite them one per one.

**Comment by 4ian** [comment] 2018-04-25 10:03
To be sure that everyone understand: if you redefine one variable in instances variables, all other objects variables will still be available.

If you have Object1 with
```
Variable1: Hello
Variable2: World
```

If you an instance with
```
Variable2: GDevelop
```
Then during the game, instance will have:
```
Variable1: Hello
Variable2: GDevelop
```

**Comment by Jeje2201** [comment] 2018-04-25 10:09
So the title of my request would more be something like "Automatically show default variables on each instance" ?

**Comment by Lizard-13** [comment] 2018-04-25 12:54
I think the grayed out variables idea is pretty good, your instance custom variables shows at the top, and the grayed (which are automatically updated when you modify the base object variables) at the bottom, then you can select one of the grayed variables and edit the value to turn it custom. Is that OK?

**Comment by 4ian** [comment] 2018-04-25 14:38
I think that this would be good yes! Would be more clear that existing object variables will be there if you don't

**Comment by 4ian** [comment] 2018-04-25 14:38
(Closed this by mistake sorry!)
What was mentionned by Lizard-13 would indeed be the way to go :)

**Comment by Jeje2201** [comment] 2018-04-25 14:39
Awesome :b

**Comment by Bouh** [comment] 2018-05-29 15:37
I added $5 bounty on this issue

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=57432113)](https://www.bountysource.com/issues/57432113-idea-automatically-show-default-variables-on-each-instance?utm_source=57432113&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by 4ian** [comment] 2018-07-17 21:17
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/bhz39w4Z/76-automatically-show-default-variables-on-each-instance

I'm not closing it as there is a bounty going on on it.

**Comment by blurymind** [comment] 2018-08-07 08:40
I've been thinking of trying to tackle this actually. I wonder if anyone else is interested or has started working on it :)

**Comment by 4ian** [comment] 2018-08-07 09:39
I've not started worked on this, feel free to try! :) Will be really useful.

What I need you will need to do:
* Get the variables of the object
* Compute the difference between variables of the object and variables of the instance.
* Display this difference (i.e: the variables defined in the object but not in the instance) in gray/disabled state.

For variables in gray/disabled state, don't show the "+" icon or the icon to remove them, but instead show an icon that makes clear that you're going to "overwrite" the variable in the instance.

Most of the work should be in `VariablesList/index.js`. I think you have to add a props `parentVariablesContainer`, in addition to `variablesContainer`. Starting from this you can do what I've written (compute the difference between variables that are in `parentVariablesContainer` and not in `variablesContainer`, then see how to display this properly). For display, you'll either want to duplicate/refactor `VariableRow` into a `ParentVariableRow` or have new props to tell that this variable should be grayed.

**Comment by zatsme** [comment] 2018-09-10 16:41
Group variables would be useful 😁

**Comment by 4ian** [comment] 2018-09-10 19:42
> Should that variable be visible in the inspector?

Groups does not exist anymore when the game is running, variables are always attached for the scene.

> Should an object group have a variable?
> Group variables would be useful 😁

Please be a bit more precise :) What for? What would be the use case, how it will be used?
I'm asking because there are tons of things that could be created for GDevelop, so we don't want to creep the software of unnecessarily or unadapted complex features. Everything needs to be carefully balanced :) 

I see one use case of having a common variables shared between objects of the group. But in this case, what will take precedence, the group variable or the object variable?
Also how should this be displayed in the editor so that it's obvious at the first glance what the variable is from?

**Comment by Lizard-13** [comment] 2018-09-10 22:09
I think there is an easy solution that doesn't modify the engine: What do you think if groups lets you edit variables, but it will just show variables common for all the objects in the group, and adding/modifying variables here would add/modify the variable in every object in the group. This way it would be just an IDE feature.

**Comment by 4ian** [comment] 2018-09-10 22:14
This is a great idea! 🙌
This is also similar to the way the "type" of a group is deduced (the type of all objects is checked, and the type of the group is the same as objects if all objects are same type (Sprite for example), otherwise the group is considered as a base object).

So this would need, when opening the "variables editor" for a group, to get the intersection of all variables of all objects of the group.
The variables should be exactly the same (same name and same default value) to be displayed there. If values are not the same, or if a variable is not declared in all objects, then it should not be shown.

I wonder though if it will be confusing or not for the users that could not understand why a variable they added to the "group" disappeared after adding an object or modifying the variable of another. 🤔

**Comment by Lizard-13** [comment] 2018-09-10 22:51
Haha, I though exactly the same, that's a big downside :/

**Comment by blurymind** [comment] 2018-09-11 07:48
When I put game objects in a group, its like putting them inside a shared class with shared logic. That logic needs some sort of variables :)
The idea is similar to construct2's family instance variables
https://www.scirra.com/manual/142/families

Once you add a variable to a group, all of the members of that group have it and can use it

In any case, the biggest problem imo is that all the variables are not visible in the inspector, but are scattered in different sub windows. The left side inspector should be showing all of the variables of a game object. This is consistent in all game engines btw, so gdevelop is kind of going against UI

**Comment by 4ian** [comment] 2018-09-11 08:00
Note that groups in GDevelop are more akin to "interface" or "abstract classes" in programming languages.
They do not provide features per se, but allow to manipulate their content in the same way.

> In any case, the biggest problem imo is that all the variables are not visible in the inspector, but are scattered in different sub windows.

Yes the main problem for users here is that variables in the instance variables are not showing the variables that are "inherited" from the object, and this can be confusing.
A solution would be to display these object variables "grayed out" in the instance variables, to make it obvious that they will be here during the game :)

Also to answer to @Bouh remark:

> Variables can be defined by actions of the type: "Modify" for a Scene, Object, and Global variable. But when they are declared this way they are not in the list of variables (Scene, Objects, Global) Because of the way they are defined.

Indeed, GDevelop support dynamically creating variables on the fly using events, but it may be source of errors (if you enter the name of a variable incorrectly) or confusion (people don't understand why the can use any variable name).
(It's a good example of a design that is too flexible for users and backfire against them ;)).
I don't think we should remove this anyway but in GD4 I made a feature that analyzed the variables used in events and added them to the list => this could be reused in GD5 to have a similar feature.

I'm thinking of something like, at the opening of an object/scene/global variables list editor, analyze the events and if any variable is used without being declared, add a warning or show the variable grayed out with an explanation :)

Both of these features would make more obvious were variables are coming from :)

**Comment by 4ian** [comment] 2018-09-11 08:02
I've created a card for the second issue (variables declared in events): https://trello.com/c/hTlS55Mg/156-automatically-show-in-the-variable-editors-the-variables-that-have-been-used-in-events-but-not-declared-in-the-variable-list and the first issue is here: https://trello.com/c/bhz39w4Z/76-automatically-show-default-variables-on-each-instance

**Comment by Jeje2201** [comment] 2018-09-11 08:04
Never thought posting idea would move that much of people and other ideas haha 😄

**Comment by 4ian** [comment] 2018-09-11 08:06
It's often the case ahah - but it's great to foster discussions like this 😉

**Comment by Bouh** [comment] 2018-09-22 12:37
Remember i put on this issue a [bounty](https://www.bountysource.com/issues/57432113-idea-automatically-show-default-variables-on-each-instance) of $5

**Comment by Bouh** [comment] 2019-01-24 02:14
I'va added $6.39 to $5, now it's $11.39USD for this issue 🤪
[Link on bounty source](https://www.bountysource.com/issues/57432113-idea-automatically-show-default-variables-on-each-instance)

**Comment by blurymind** [comment] 2019-01-24 12:57
Guess I could look into it if nobody else wants to tackle it

**Comment by 4ian** [comment] 2019-01-24 12:59
I think that's a super interesting feature :) And would help a lot people to understand what's going on with instance variables (as they will see the object variable grayed out, and hopefully understand better than they can "override" them or declare new one for the specific selected instance)

**Comment by blurymind** [comment] 2019-01-26 15:59
Ok so just to summarize, we need to:
- include object variables with instance variables
- be able to see all variables of an instance directly inside the Properties panel (no need for extra clicks!)

**Comment by blurymind** [comment] 2019-01-26 16:49
The advantage of having the variables list inside the instance properties panel is that it is much easier to compare values of instances.  Its instant access and key information is not hidden by default in a popup.
This is how Unity3d, Godot and most other game engines do it. When you create new variables, they are accessible directly in the properties panel
![gdevelop-easyaccess](https://user-images.githubusercontent.com/6495061/51790241-3af74d80-218a-11e9-8131-d39a98c9b7ed.gif)
What I want to hear before going further with this is- is it a welcome change? 
Having them all in one place and that place is instantly visible upon selecting any instance

**Comment by blurymind** [comment] 2019-01-26 19:19
some update on this:
![gdevelop-compact-er](https://user-images.githubusercontent.com/6495061/51791728-135eb000-219f-11e9-94d7-170d4d26a949.gif)

I moved the copy/paste/delete buttons to the add variable row - its more compact that way. Also I think the location is more intuitive there- as editing variables is not split into two rows that way

**Comment by Wend1go** [comment] 2019-01-27 08:06
Is this only for instance variables or can we also edit object variables this way? (without having to open the right click menu on an object)

**Comment by blurymind** [comment] 2019-01-27 11:19
not yet, but the goal is to also be able to edit object variable values when editing instance variables. I am working on it :)

**Comment by Bouh** [comment] 2019-01-27 12:22
In this pannel if we have 1 sub-variable the space is tiny, imagine with 3 sub level ?
I prefer open a new windows than resize the panel at eatch time for see all my variables.

**Comment by blurymind** [comment] 2019-01-27 18:44
We can keep the pop out option if you want to. I don't think that many
people will create variables with alot of nesting

**Comment by 4ian** [comment] 2019-01-27 18:59
> instead of popping them out, we could optionally collapse them with something like

I'm pretty sure we could do it ourselves without a new dependency :) (store collapsed: true or false in the state, render the children or not according to it).
But yeah that would be super useful to be able to collapse. Also would improve performance when having a lot of nested variables on large games.

> not yet, but the goal is to also be able to edit object variable values when editing instance variables. I am working on it :)

I wonder if it's not too risky, would create a lot of confusion maybe?

> We can keep the pop out option if you want to. I don't think that many
people will create variables with alot of nesting

Yes a button to open the full editor in a separate dialog sounds a good idea to me.

**Comment by blurymind** [comment] 2019-01-27 19:43
@4ian I think that since if one creates an instance variable with the same name as an object variable, that overwrites the object variable - it will make a lot of sense to include the object variables listed as instance variables too. I think I worded it wrong before- the idea is not to edit object variables in the instance variable editor- but to automatically create an instance variable for each object variable
 and  communicate the user that it is overwriting the default object variable - even show to the user the object variable itself as a placeholder when the field is empty:
![gdevelop-objectvarplaceholder](https://user-images.githubusercontent.com/6495061/51802304-b0bdf080-2240-11e9-8f3b-be75e5984384.gif)

**Comment by 4ian** [comment] 2019-01-27 20:32
So it's indeed two different concerns :) 
* Here we should be solving the issue of making instance variables easy to edit AND showing properly the existing object variables (so that's it's obvious for people that they can "overwrite" existing variable). For this, the current design looks good, as long as we can open the dialog separately (to avoid resizing panel if there are too much variables) and if we display the name of the object variables also grayed out, like the placeholder.
* As for editing object variables, maybe it's something that we can think differently. Either a button to open it, or a button/tab in the object editor (after all, variables ARE part of the object - so they could have their tab in the object editor - and the object editor is easy to open).

**Comment by 4ian** [comment] 2019-01-28 09:47
Yes, I think this is especially the case for scene/global variables - I have a large game with lots of nested global/scene variables too.
So it's both valuable to be able to open the dialog separately with a button (even if instance variables will surely have much less nested variables) and to work at some point on being able to collapse nested variables.
Adding the ability to collapse variables can be done separately to showing object variables values inside instance variables. I've created a card for it: https://trello.com/c/ZtiM98XI/241-add-button-to-collapse-show-nested-variables-in-the-dialog-to-edit-variables

If someone want to try, this seems actually not too hard to implement.

**Comment by blurymind** [comment] 2019-02-01 19:16
Another progress report:
@4ian asked to add some limitations to this,so now any object variable names can not be renamed from the instance editor, or removed - they are only shown. If their value is changed- in the background what happens is that an instance variable with the same name gets created and listed - we call that an inherited variable, as it overwrites the object one. We can also not create any structured inherited variables automatically - as there is currently a limitation in gdevelop, noted here:

I managed to move down the instance variable button below animations as @Bouh  requested and yes it's back as @Wend1go requested

Screenshot here :)
![gdevelop-resettodefaultdynamic](https://user-images.githubusercontent.com/6495061/52144303-caeb3a80-2655-11e9-8f21-0967c00abd9c.gif)

its not as pretty as before, but it works better, as it is dynamic and instance variables overwriting the object one get created only when the field is edited, not on mount

**Comment by blurymind** [comment] 2019-02-07 20:45
I now have something working in the pull request. Another thing I did was in adding a button to edit object variables at the bottom:
![capture](https://user-images.githubusercontent.com/6495061/52152172-61772600-266d-11e9-9a2f-2ed1244c46a0.PNG)

Would appreciate any feedback/review.  :)  please let me know if you find corner cases where it breaks

**Comment by 4ian** [comment] 2019-02-07 21:21
Great, will look at this asap :)

**Comment by Lizard-13** [comment] 2019-02-08 01:18
I like that, new users will see the big instances variable button, once you know the difference between instance and object variables you've a nice shortcut :)

**Comment by blurymind** [comment] 2019-02-11 20:33
Here is a progress update:
![gd-instancevariables](https://user-images.githubusercontent.com/6495061/52589221-4018f580-2e36-11e9-8aa2-23d50b642faf.gif)
I think we are getting there now :D

**Closed** 2019-02-19 21:19 UTC
Labels: ✨ enhancement, 👌good first issue

**Comment by Bouh** [comment] 2019-02-19 21:28
You can ask to claim [your bounty here](https://www.bountysource.com/issues/57432113-idea-automatically-show-default-variables-on-each-instance)

**Comment by 4ian** [comment] 2019-02-19 21:37
Almost forgot that there was a bounty on this! Yeah @blurymind Feel free to have it as you've worked a lot on this.

**Comment by blurymind** [comment] 2019-02-19 22:11
@Bouh @4ian @Lizard-13 thank you for the help along the way 😄  I am really happy that this is in gdevelop now. It makes working with instance variables a breeze

**Comment by Jeje2201** [comment] 2019-02-19 22:11
And my mail box is now happy that the idea is finally close 😄
