### ISSUE TITLE
Cannot download particle emitters from the asset store (v5.1.155)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4770] opened 2022-12-30 19:27 UTC
## Describe the bug

Cannot download particle emitters from the asset store when using version 5.1.155.

![Screenshot 2022-12-30 114448](https://user-images.githubusercontent.com/8879811/210105741-e000fde1-9036-426e-87f9-8c3fb48f1e5f.png)

## To Reproduce

1. Try to download particle emitter from the asset store
2. See the error in the screenshot: 
```There was an error while installing the asset "Bubbles". Verify your internet connection or try again later.```

## Other details
* Windows 11
* GDevelop 5.1.155

**Comment by ClementPasteau** [comment] 2023-01-03 09:15
Duplicate of #4743 fixed

**Closed by ClementPasteau** 2023-01-03 09:15 UTC
