### ISSUE TITLE
GDevelop freezes when changes the events order.

### ISSUE THREAD

**Issue by ghost** [4ian/GDevelop#1903] opened 2020-08-01 10:03 UTC
## About the bug:
The editor freezes when change the events order on the action section from the events sheet on a scene. But the navigation bar (the menu where the options to open, help, etc.) come out does work (only freezes the editor section).

## Steps to Reproduce the bug:
1. Go to any scene.
2. Open the events sheet.
3. Put some actions on the "actions" section.
4. Try to change the actions order.

## Other details:
* OS: Windows 10 2004 19041.388
* GDevelop 5.0.0 Beta-98

**Comment by 4ian** [comment] 2020-08-02 15:10
I can't seem to reproduce this. Would you be able to make a short video or a set of screenshot?

**Comment by Silver-Streak** [comment] 2020-08-17 14:14
@4ian I'm able to reproduce this, but it isn't consistent. It seems to happen the most when moving "And" as well as "Or" conditions that have events in them.

**Comment by Bouh** [comment] 2021-11-08 19:59
I up the topic again because I've faced this freeze and crash.
It also happens more and more often to users as we have more and more of them.
The problem is not related to the specification of the computers because we have recent and old PCs.
With 64Gb of RAM or 4GB so not related to the hardware.

I really think that the problem is related to the library that manages the event tree.
Which is rather unique and is called [react-sortable-tree](https://github.com/frontend-collective/react-sortable-tree).
We don't have updated it often since the creation of GD5.

There is also [a fork of the library](https://www.npmjs.com/package/@nosferatu500/react-sortable-tree) as many bugs were not fixed by the original author...

As a bonus a preview of the problems in GDevelop before a crash.
Crashes often happen on the big event sheet, with many sub-events/groups.
Other people have also indicated that the OR condition is sometimes the cause of crashes.
This is quite possible as it can contain other conditions and therefore act as a group or sub-event.
The problem is not yet critical, it's only prevention.

![eventsheet_drag drop](https://user-images.githubusercontent.com/1670670/140806628-509d748c-c428-4626-b18a-4100ec40b1af.gif)

**Closed** 2022-05-27 08:41 UTC
Labels: 💥crash
