### ISSUE TITLE
Add support for releasing ladders with a key in the Platformer Object behavior

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2625] opened 2021-05-08 10:51 UTC
## Describe the bug
The below JS code no longer works (player should drop off ladder). It was working when I originally added/tested it back in Feb. I reverted my GDev back to 5.0.0-beta105 and it works again.

![image](https://user-images.githubusercontent.com/71751097/117536521-c258ea00-b03e-11eb-9576-fef3934cdabb.png)

## To Reproduce
1. Run the latest build, does not work.
2. Run 105 build, works.

## Other details
* Nightly Build from 23rd or 24th of April.
* Windows 10.

**Comment by 4ian** [comment] 2021-05-08 13:58
This is unfortunately not really a regression - because it's expected that anything that starts with an underscore (_isOnLadder) is a *private* method or member. As such, it should never be used (outside of the implementation of the behavior), and by using it you expose yourself to have such incompatibilities in the future.

Ideally, it would be great to not show them in autocompletions or even trigger an error (to avoid mistakes).
Instead, make sure to always rely on the "public interface", which is guaranteed to be maintained or at least you'll have an alternative if it breaks. In your case, use `isOnLadder()`:
https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/PlatformerObjectRuntimeBehavior.html#isOnLadder

**Comment by 4ian** [comment] 2021-05-08 13:59
(Closing but discussion can continue)

**Comment by AtomicCrocStudios** [comment] 2021-05-09 00:21
> This is unfortunately not really a regression - because it's expected that anything that starts with an underscore (_isOnLadder) is a _private_ method or member. As such, it should never be used (outside of the implementation of the behavior), and by using it you expose yourself to have such incompatibilities in the future.
> 
> Ideally, it would be great to not show them in autocompletions or even trigger an error (to avoid mistakes).
> Instead, make sure to always rely on the "public interface", which is guaranteed to be maintained or at least you'll have an alternative if it breaks. In your case, use `isOnLadder()`:
> https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/PlatformerObjectRuntimeBehavior.html#isOnLadder

Thank you for the information @4ian . I am aware that I should not be using a private method, however there is nothing exposed that will let my character just "let go" of the ladder currently and when I requested it back in #2300 (with the above work around) the issue was closed and I was told to use a work around of disabling the behaviour. Unfortunately disabling the behaviour doesn't achieve the same results as telling the player to "just let go" (at least not with multiple checks to make sure the behaviour is reactivated)

**Comment by 4ian** [comment] 2021-05-09 10:51
Ah right I misunderstood your need! 
For now, you should be able to work around this by using `platformerBehavior._setFalling()`, but this is really a feature request: add support for "releasing" a ladder, by pressing the "release" key (which is already used for releasing a grabbed platform).

**Comment by AtomicCrocStudios** [comment] 2021-05-09 13:11
> Ah right I misunderstood your need!
> For now, you should be able to work around this by using `platformerBehavior._setFalling()`, but this is really a feature request: add support for "releasing" a ladder, by pressing the "release" key (which is already used for releasing a grabbed platform).
> 
> (EDIT: so that you can do `platformerBehavior.simulateReleaseKey()` in the future, which will be always supported - or you will just be able to use traditional actions to do that)

That was the JS work around we ended up going with :D Thank you again for the help and adding`platformerBehavior.simulateReleaseKey()` for the future!

**Comment by ClementPasteau** [comment] 2021-08-12 14:57
the action `simulateReleaseLadder` has just been added in #2892 and should be available in the next release!

**Closed by ClementPasteau** 2021-08-12 14:57 UTC
Labels: ✨ enhancement, 👌good first issue
