### ISSUE TITLE
Using text object action/conditions without a text object on the scene crashes the game

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GDevelop#1147] opened 2019-07-08 21:47 UTC
## Bug 1
The action "changing to an other scene" from function doesn't work for some condition

I created a function in the new "Functions/Behaviors" so depend on the sprite you click, it would move you to another scene, but look like the "change scene" event doesn't work in the function.
I tried a simple function like
` If hover an object (set as a param) then play a sound (to be sure it get trigger) and change to a scene that is a parameter too` 

Somehow the sound get trigger, but no scene change here is a simple exemple: [Game2.zip](https://github.com/4ian/GDevelop/files/3370390/Game2.zip)

## Bug 2
If the object parameter is a text, the preview stop at 100% with this error message in the console
Here is the project exemple : [game.zip](https://github.com/4ian/GDevelop/files/3370379/game.zip)

![Screenshot_53](https://user-images.githubusercontent.com/19387127/60845860-e72f6c80-a1dd-11e9-82a0-1d074ca20edc.png)

## Other details
Gdevelop Beta 75
Windows 10

**Comment by Bouh** [comment] 2019-07-08 22:25
I can't reproduce this error.
And you need call the value from parameters, like this : 
`GetArgumentAsString("sLaScene")`
So the action need to be : 
`Change scene to GetArgumentAsString("sLaScene")`

**Comment by Jeje2201** [comment] 2019-07-08 22:36
Oh yeah, indeed, not intuitive as when it's for an object as it detect the object parameter, expected same for scene name, good to know, thanks @Bouh 
But then, when fixing it with your solution, it give me back this
![bug1](https://user-images.githubusercontent.com/19387127/60846981-81dd7a80-a1e1-11e9-852c-400b0ae96472.png)
 with what it seem a problem at that line
![bug2](https://user-images.githubusercontent.com/19387127/60846997-8efa6980-a1e1-11e9-8ae5-2513c9f51e5e.png)

**Comment by Jeje2201** [comment] 2019-07-08 22:49
Seem like the bug only appear if the scene in the parameter exist

**Comment by Jeje2201** [comment] 2019-07-08 23:32
Welp, reproducing the bug just by placing a text object ? Starting to seem not really cool
![TextBug](https://user-images.githubusercontent.com/19387127/60849075-78f0a700-a1e9-11e9-8dab-ba085c2e770e.gif)

**Comment by Jeje2201** [comment] 2019-07-08 23:44
Might come from here ?
![image](https://user-images.githubusercontent.com/19387127/60849462-20baa480-a1eb-11e9-95b4-56ad660a1153.png)

**Comment by 4ian** [comment] 2019-07-09 11:35
Can you share the project file (and images if any) here? Thanks!

**Comment by Jeje2201** [comment] 2019-07-09 12:39
Seem like the problem come from my computer 🤨
I tried to load the project on an other computer and it worked, gonna try to uninstall and install back Gdevelop5 and letting you know if it was a package missing, but weird as it worked fine until yesterday, and no updates of Gdevelop were added between
(Computer accessible in 3h)

**Comment by 4ian** [comment] 2019-07-30 20:40
This is a good first issue:  the root cause is actually using some text object related actions/conditions while not having an object on the scene.
This can be fixed by ensuring that using an object action/condition will import all the needed include files (only Extensions/TextObject/textruntimeobject.js is imported for now, ideally Extensions/TextObject/textruntimeobject-pixi-renderer.js and Extensions/TextObject/textruntimeobject-cocos-renderer.js should be too).

**Comment by piyushpalawat99** [comment] 2019-08-05 10:43
I believe this issue can be closed now :)

**Comment by 4ian** [comment] 2019-08-05 12:13
Right, thanks for pinging us about this :)

**Closed by 4ian** 2019-08-05 12:13 UTC
Labels: 👌good first issue, 😇A workaround exists
