### ISSUE TITLE
Automatic logging in to your profile works only when you go check it in File->My Profile. Otherwise debugger will ask for support.

### ISSUE THREAD

**Issue by Sapper-Morton** [4ian/GDevelop#3238] opened 2021-11-12 06:44 UTC
## Describe the bug
You have active profile and have previously logged in. You can go check to see that your profile is active.
Now on the next launch of GDevelop your profile is not really logged in and when started, the debugger notifies that you should give GDevelop some support.

## To Reproduce
1. Start GDevelop, load project and start debugger.
![image](https://user-images.githubusercontent.com/23439320/141421275-9185d13f-85fa-443e-ab5f-d920ce4273f6.png)

2. Debugger gives this message.
![image](https://user-images.githubusercontent.com/23439320/141421320-4a197530-61fb-48a3-9c4f-9e33113d033d.png)

Methods to avoid debugger message:
1. Go visit your profile window first in File -> My Profile

## Other details
GDevelop version 5.0.121

**Comment by VanCastar** [comment] 2021-11-12 06:49
Yup, I was wondering about this just the other day as well.

**Comment by Bouh** [comment] 2021-11-12 11:14
[A first fix](https://github.com/4ian/GDevelop/commit/7f5821a2994efef4d9ae57b8bd9d331b8ebfb95a) has been made but it doesn't affect the debugger.
It's indeed a problem, I face it too.

**Comment by 4ian** [comment] 2021-11-12 11:33
I was thinking this would have been fixed by what you linked Bouh. I'll take a look.

**Comment by ClementPasteau** [comment] 2021-11-23 11:05
I've tried reproducing the issue.
It seems to happen only in production and only the first time you launch the app. 
(if you refresh the electron wrapper, it works)

So I suspect that the call to fetch the profile doesn't happen the first time you launch the app (maybe a timing issue in the async calls?) - I can't verify this as the Devtools take a bit of time to open, so I may be missing the calls.

I can't reproduce it locally, even the first time I launch electron...

**Comment by 4ian** [comment] 2021-11-23 11:21
Are you properly testing using 5.0.122-beta1? It has the fix but 5.0.121 is impacted by this problem.

**Comment by ClementPasteau** [comment] 2021-11-23 11:44
You're right I had not tested 5.0.121!
I've managed to reproduce it with 5.0.121 but it's really inconsistent (1 out of 5 launches of the app)
With 5.0.122-beta1, I've tried 20 times and the problem doesn't happen at all.

**Comment by 4ian** [comment] 2021-11-23 12:10
That's encouraging! Let's consider this is fixed (I remember doing a fix, so if I did it properly and you can not reproduce it in 5.0.122-beta1, chances are that it's indeed fixed!)

**Comment by Bouh** [comment] 2021-11-23 13:32
I can't reproduce it on 5.0.122 beta-1 too.
I did some tests on:
- Export
- Debugger
- Profile
- Live preview
Each time I closed the app and relaunched to test the next feature.

**Comment by Bouh** [comment] 2021-11-23 13:33
We can consider this bug fixed, thx guys!

**Closed by Bouh** 2021-11-23 13:33 UTC
Labels: 🐛 bug
