### ISSUE TITLE
Black screen if an object has a Physics2 behaviour

### ISSUE THREAD

**Issue by ced64k** [4ian/GDevelop#1075] opened 2019-05-31 12:19 UTC
## Describe the bug
If I add a Physics2 behaviour on any object in my scene, the screen is black with 100% in white in preview

## To Reproduce
1. Create a new project
2. Add a new scene
3. Add a new object (sprite)
4. Add an image for this sprite
5. Put the object in the scene
6. Add a Physics2 behaviour to this object
7. Preview the game

![UPnZc0e](https://user-images.githubusercontent.com/3351314/58705285-005b2700-83af-11e9-898a-81c1d69e628f.png)

## Other details
* Windows 10 1809
* GDevelop 5.0.0-beta70 desktop

**Comment by 4ian** [comment] 2019-05-31 13:10
Can you post a zip file containing the game?

**Comment by ced64k** [comment] 2019-05-31 14:07
Here it is. I reproduced the bug in a new game file with only a sprite and a physics behaviour.
[games.zip](https://github.com/4ian/GDevelop/files/3241528/games.zip)

**Comment by 4ian** [comment] 2019-05-31 18:25
Thanks, that was useful. It's due to a regression in latest version where the gravity and scale properties of the physics engine are not initialised properly by the extension when the behavior is first added to an object. A "workaround" could be to use a game where physics engine is already added to some objects. (If all objects with the physics behavior are deleted in the editor, the bug will trigger again)

I'll try to push a fixed version this week-end, sorry about this.
Fixed in ea059947026fb13196382fed79cc14224856216d

**Closed by 4ian** 2019-05-31 18:25 UTC
Labels: 🐛 bug

**Comment by ced64k** [comment] 2019-06-01 14:20
I confirm it's working now in beta72, thanks @4ian :)
