### ISSUE TITLE
3D model animation actions/conditions

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#6953] opened 2024-09-12 16:04 UTC
## Description

There isn't currently a way to restart an animation that is already playing. With 2D sprites you can set the frame of the animation back to 0. But that isn't the case with 3D models.

## Solution suggested

Allow animations to be restarted in the same way as sprite animations.

_______

(Edit: The animation can be restarted by switching the animation to something else before changing it to the one you want to use, but this is sort of a "hack" solution. It would be better if the time elapsed action worked as consistently as the frame action, allowing users to reset animations during and after the animation has finished playing.)

**Comment by stanikeva** [comment] 2024-09-16 21:36
@HelperWesley Is this still available?
If so, I would like to contribute

**Comment by 4ian** [comment] 2024-09-17 10:23
@stanikeva Yes please, you're welcome to contribute a PR to add this :)

**Comment by Ahmad986Ferdaws** [comment] 2024-09-17 14:07
I would like to contribute

**Comment by 4ian** [comment] 2024-09-17 14:31
Feel free to start working on an issue, no need to ask for permission (though discussion can be useful if it's a complex problem) :)

**Comment by kitsiosvas** [comment] 2024-09-21 17:02
@HelperWesley Good evening, could you please provide a bit more information about this issue? Maybe where in the pipeline this feature is implemented in the 2D sprites so we can start from there? Also maybe where would this new implementation go in the code? Thank you for your time!

**Comment by D8H** [comment] 2024-09-21 21:28
> There isn't currently a way to restart an animation that is already playing. With 2D sprites you can set the frame of the animation back to 0, or switch to a different animation and then back to the one you want to restart. But that isn't the case with 3D models.

Actually, the following action can be used on any object that has animations:

![image](https://github.com/user-attachments/assets/c1e4666b-6d36-49e9-95a2-9b415d89f9f9)

**Comment by HelperWesley** [comment] 2024-09-22 13:25
@D8H 


https://github.com/user-attachments/assets/19349bff-3ccc-4cf7-8774-dc4dcfb3b8e6

**Comment by AlexandreSi** [comment] 2024-10-07 13:30
@HelperWesley thanks for the analysis.
If you still have the project, sending it here would be a great addition to the issue for contributors to have a reproductible bug.
@kitsiosvas @stanikeva @Ahmad986Ferdaws I think you have everything to submit a PR:
- The action that should work (you can search the sentence in the codebase in order to get the function that is executed in game)
- The fact that it does work for Sprites but not 3D models (both are `Animatable` objects) so it can be considered as a bug. Plus you can have a look at the sprite object way of doing things to get ideas about how to fix this for 3D models.

**Comment by AlexandreSi** [comment] 2024-10-25 16:06
Closing this since I think it's been fixed in the latest release. Feel free to re-open if there is still an issue.

**Closed by AlexandreSi** 2024-10-25 16:06 UTC
Labels: ✨ enhancement, 👌good first issue
