### ISSUE TITLE
Object value input only active for one character (in instance properties)

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#5237] opened 2023-04-15 10:00 UTC
## Bug description / What happens
When modifying object variables for an instance in the instance properties panel the first time, the input is only active for one character and will then lose focus. Other than this being inconvenient, any other character will be caught by the keyboard shortcuts so it's easily possible to accidentally toggle panel visibilites (which reset panel layouts), change settings or even close GDevelop.

## When it does (not) happen
This behavior does not happen when modifying instance variables. It also only happens when changing an object variable of an instance the first time. Once it has a different value than the initial/default object variable value, this will not happen anymore. It also only happens in the instance properties of an instance, not in the object variable editor of the object itself.

## Possible causes
When changing the object variable for one specific instance, it looks like GDevelop then doesn't treat this variable as an object variable anymore but like an instance variable. This is also why this variable is then moved below the object variables in the variables list. I can imagine that after changing or inputting a character, GDevelop instantly notices the change, cancels the action and moves the variable to the instance variables.

![Bild1](https://user-images.githubusercontent.com/83909121/232205913-eac3bbf8-8789-417c-912d-a54e94281078.png)

## To Reproduce
1. Add a object variable to an object
2. Instance it in the scene
3. Select the instance
4. Change the object variable content in the instance properties panel

## Video
https://user-images.githubusercontent.com/83909121/232207109-13411aa2-143a-4d5a-9ce3-23e9d05c86b0.mp4

## Other details
Windows 11
Regular GDevelop desktop release
v5.1.160

**Comment by tristanbob** [comment] 2023-04-18 12:31
Thanks for reporting this, it is a duplicate of #4048.

**Closed** 2023-04-18 15:34 UTC
