### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by arow102** [4ian/GDevelop#6241] opened 2024-01-23 02:06 UTC
### GDevelop version

5.3.187-7fbe1bd23dfee19829f238048afd4c7ac84a00cf

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15, Platform: MacIntel

### Additional error context

uniqueErrorId: 5817f231-b0ce-4072-9f53-f7a9c9e9f90d

i@https://editor.gdevelop.io/static/js/1573.fe72a661.chunk.js:2:3301945
mo@https://editor.gdevelop.io/static/js/1573.fe72a661.chunk.js:2:3302382
Ie@https://editor.gdevelop.io/static/js/1573.fe72a661.chunk.js:2:3439006
e@https://editor.gdevelop.io/static/js/1573.fe72a661.chunk.js:2:3439590
value@https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:1536341
value@https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:1535770
ds@https://editor.gdevelop.io/static/js/main.14977905.js:2:505413
Fu@https://editor.gdevelop.io/static/js/main.14977905.js:2:523186
@https://editor.gdevelop.io/...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aT
    in jT
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in KL
    in div
    in n
    in oa
    in div
    in xO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in u
    in j
    in h
    in h
    in Z
    in d
    in ee
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n...

**Comment by ClementPasteau** [comment] 2024-01-25 08:53
Duplicate of #5987 - MacOS crash

Need to upgrade to Pixi 7.3.2 to get the fix

**Closed by ClementPasteau** 2024-01-25 08:53 UTC
