### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by tungstenterminators011** [4ian/GDevelop#6185] opened 2024-01-12 17:14 UTC
### Describe what you were doing when the crash happened

I was just working on my project/game when suddenly when I was adding my first block of code in and tried to test it without the action statement for the second time, everything went blank and i got a error message.

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36, Platform: MacIntel

### Additional error context

uniqueErrorId: 759cec18-9b4e-4c0e-b396-e62f16e0da2a

TypeError: Cannot read properties of undefined (reading 'fill')
    at u.value (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:670511)
    at u.value (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:677268)
    at u.value (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:671286)
    at u.get (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:518442)
    at a.update (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:664882)
    at new a (https://editor.gdevelop.io/static/js/1859.62848722.chunk.js:2:663649)
    at Object.createNew...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in mw
    in Mw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-18 09:09
Looks like duplicate of #6180 

Few questions @tungstenterminators011 
- Are you using a BBText in your scene?
- Was this an old project or one you just created?
- Does this happen consistently on your project?

Thanks

**Closed by ClementPasteau** 2024-01-18 09:09 UTC
