### ISSUE TITLE
Objects are not rendered in the editor.

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#707] opened 2018-10-20 09:36 UTC
## Describe the bug
Objects, sometime are not rendered in the editor.

## To Reproduce
It can not be reproduced it does happen randomly:
http://forum.compilgames.net/viewtopic.php?f=20&t=10478

It does happening to me at this very moment with this project in the online editor:
https://editor.gdevelop-app.com/?project=example://custom-font

The text object in the loadFont scene is not displayed for me in the editor in Firefox on Windows 10 64bit.
It works in Chrome.

## Solution
Sometime it does solve it self in the desktop version by closing, opening the project a few times. Others also mentioned zooming in and out solved the problem for them. I have already opened the project multiple times in Firefox and cleared the cache too, zoomed in and out but the problem is still there when I open the project in Firefox.

Can anyone else catch it this time?

**EDIT://** it seems like in this case with the above project the problem is that the fon't isn't loading in Firefox, if I remove the custom font, the text is visible and if I set the custom font, the text no longer rendered. 

So, when we experience the same problem with sprite objects in the desktop version, maybe it is a similar problem and the images can not be loaded for some reason? But it did happened to me once when only certain instances of the same object was not visible in the editor and others was,,,

Anyway, have fun devs :)

**Comment by rikazukun** [comment] 2018-10-20 10:48
Same with https://github.com/4ian/GDevelop/issues/536

**Comment by 4ian** [comment] 2018-10-21 22:43
This is something that I've seen but I'm not sure for now about the reason objects are disappearing.

> Same with #536

Nope, these are two different issues. The issue in #536 are custom fonts not loaded fast enough to be displayed during preview/game.

**Comment by Jacques-Olivier-Farcy** [comment] 2018-12-11 10:22
I have this problem, and it is not random, i always have objects invisible inspite of they exist on the scene.
Windows 7 64 / Gdevelop beta58.

When i edit an object and then apply without any changes, the object is coming back on the scene.

**Comment by ddabrahim** [comment] 2019-11-24 17:55
In beta83 it seems this problem is back.
I did not experiences this problem for a while, I have just downloaded beta83 this morning and boom, few objects did not render in the editor. Zooming in an out did make them appear.

GDevelop 5 beta83 Desktop
Windows 10 64bit

**Comment by Silver-Streak** [comment] 2021-07-25 16:18
I'm going through older issues to bring attention to them or close them out.

@ddabrahim are you still seeing this in b113? I haven't seen this in a long while, but I also don't remember seeing it in b83 so I wanted to confirm with you before I close this out.

I'll close out this issue upon receiving confirmation from you that it is resolved, or if no response is received within 30 days of this post.

**Comment by Bouh** [comment] 2021-07-25 17:16
The resources loaders have changed since we use Pixi V6.
Since the problem is old, I prefer to close it.
If it still exists on the beta 113 then let's reopen a new report that will be more up to date.

**Closed by Bouh** 2021-07-25 17:16 UTC
Labels: 🐛 bug

**Comment by 4ian** [comment] 2021-07-26 08:45
Can confirm there was a "race condition" that resulted in this problem that I solved a few betas ago.
