### ISSUE TITLE
Search filter for online editor not functioning as desired

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1537] opened 2020-03-16 11:52 UTC
## Describe the bug
The search filter for online editor is not functioning as desired. 

## To Reproduce
1. Go to [link](https://editor.gdevelop-app.com/)
2. Click 'Create a new project'
3. Click 'Examples'
4. Try filtering examples

## Screenshots

![Screenshot 2020-03-16 at 5 10 55 PM](https://user-images.githubusercontent.com/42793024/76755457-e78af900-67a9-11ea-85c2-a3cb26bdb974.png)
Eg: Hitting 'm' should ideally list examples with titles starting from 'm'.

![Screenshot 2020-03-16 at 5 11 05 PM](https://user-images.githubusercontent.com/42793024/76755463-eb1e8000-67a9-11ea-9185-801ed1490190.png)
Still doesn't show

![Screenshot 2020-03-16 at 5 11 16 PM](https://user-images.githubusercontent.com/42793024/76755469-ece84380-67a9-11ea-9280-b7f9c9bbcdcf.png)
Finally shows but misses many other examples starting with 'm'.

![Screenshot 2020-03-16 at 5 21 08 PM](https://user-images.githubusercontent.com/42793024/76755857-a21afb80-67aa-11ea-8fe3-316256b98cf8.png)

## Other details
* Mac OSX, Mojave Firefox 74.0 (64-bit)
* Web App

**Comment by pranavmodx** [comment] 2020-03-16 11:53
@4ian If this issue sounds valid to you, I shall take this up.

**Comment by 4ian** [comment] 2020-03-16 12:16
Feel free to take a look yes!

**Comment by pranavmodx** [comment] 2020-03-17 17:30
It seems that it's not a bug but a missing feature. If not, what is the filtering based on? Like, is the filtering based on example game's title, description or sth else?

**Comment by pranavmodx** [comment] 2020-03-17 17:35
On a side note, the same filter issue can be seen for Objects search also.

**Comment by pranavmodx** [comment] 2020-03-18 13:18
@4ian Can you fill me in here?

**Comment by 4ian** [comment] 2020-03-18 13:46
Take a look at https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ProjectCreation/ExamplesList.js

It's a fuzzy filter. I'll close this because it's a feature, not a bug. All search should be, where possible, fuzzy filter.

**Closed by 4ian** 2020-03-18 13:46 UTC

**Comment by pranavmodx** [comment] 2020-03-18 13:57
Thanks for clarifying on a short notice. :)
