### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by leCyox** [4ian/GDevelop#6139] opened 2024-01-03 13:38 UTC
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: bde38bb5-d341-4ef8-8e2e-292affcfc1d2

RuntimeError: memory access out of bounds
    at wasm://wasm/00b41e4e:wasm-function[124]:0x11216
    at gdObject.GetName.gdObject.GetName [as getName] (file:///C:/Users/chris/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1005048)
    at file:///C:/Users/chris/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:1537452
    at Array.map (<anonymous>)
    at file:///C:/Users/chris/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:1537365
 ...

### Additional component context

    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in gt
    in c...

**Comment by ClementPasteau** [comment] 2024-01-04 08:34
duplicate of #5994 

Thanks for reporting the issue @leCyox , do you remember what you were doing before and when the crash happened?

**Closed by ClementPasteau** 2024-01-04 08:34 UTC
