### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by OBgames** [4ian/GDevelop#6126] opened 2023-12-25 06:27 UTC
### Describe what you were doing when the crash happened

I went to the object editing menu, selected "behaviours", clicked the "add new behaviour" button and an error warning appeared.

changed:
This error only appears in a cloud project!!!

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: fd9fdc31-e82a-4b61-9daf-79df57008c92

RuntimeError: null function or function signature mismatch
    at wasm://wasm/00b41e4e:wasm-function[4194]:0x1cc732
    at BehaviorMetadata.GetRequiredBehaviorTypes.BehaviorMetadata.GetRequiredBehaviorTypes [as getRequiredBehaviorTypes] (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1248064)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:932166
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:932307
    a...

### Additional component context

    in ax
    in div
    in s
    in Ay
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Wy
    in n
    in t
    in Unknown
    in Yy
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
...

**Comment by ClementPasteau** [comment] 2024-01-03 14:15
Hi @OBgames thanks for reporting.
Can you try restarting, then reinstalling the app to see if it solves it?
Wondering if your app is in a corrupted state.

Duplicate of #6121

**Closed by ClementPasteau** 2024-01-03 14:15 UTC
