### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by KotaroMT** [4ian/GDevelop#6073] opened 2023-12-13 13:49 UTC
### Describe what you were doing when the crash happened

I added a new scene, then added some objects, and the error occurred. This has happened three times, without fail, in this exact sequence.

### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 4220b677-f11a-4fa5-b32a-d6cb2860f57a

TypeError: Cannot read properties of null (reading 'valid')
    at new n (file:///C:/Users/XM/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:1946700)
    at n.value (file:///C:/Users/XM/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1996142)
    at new n (file:///C:/Users/XM/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1995126)
    at Object.createNewInstanceRenderer (file:///C:/Users/XM/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.ch...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by AlexandreSi** [comment] 2023-12-14 08:41
Hi @KotaroMT,
Sorry for the inconvenience and thank you for taking the time to open this issue.
Is it still happening consistently today? Do you remember if during those 3 times, it happened while you were doing a particular thing?

**Comment by ClementPasteau** [comment] 2023-12-14 12:58
Duplicate of #5896

**Closed** 2024-01-03 09:54 UTC
