### ISSUE TITLE
newIde: ability to lock selection on layers

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#670] opened 2018-09-25 20:12 UTC
It would be great if we could lock layers, so items on them can not be selected!

## Description
This is something that becomes a problem when you have a HUD layer and you keep clicking on the hud elements by mistake, when you are trying to move some level element.

This forces one to hide the hud while designing, which then leads to having to re-show it before every playtest. Its a pain in the neck

## Solution suggested
I could try to add a tiny lock toggle button on the layerrow, so as to able to set a layer to locked:true. Then relay that to the instances selection code, to ignore instances on a locked layer!

I was just looking at that exact code why it hit me that this can also be something that can be added to improve the situation

**Comment by Lizard-13** [comment] 2018-09-26 11:54
You could hide the layer, and add an event "At the beginning of the scene >> Show layer HUD". No need to hide/unhide this layer again until you've to edit it :)

**Comment by blurymind** [comment] 2018-09-26 12:11
@Lizard-13 that would be solving an Ide usability problem by adding extra code to the game itself. It is however a nice workaround :)

**Comment by 4ian** [comment] 2018-09-27 01:10
> I could try to add a tiny lock toggle button on the layerrow, so as to able to set a layer to locked:true. 

Sounds good. 

1) You can use a `<Checkbox>` like it's done for Visibility I think :)

2) This would need some changes in C++ code to save layers that are locked, that might be the "hard part". (well, you can copy how it's done for the visibility. Basically: 
* add isLocked boolean and getter/setter here: https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Project/Layer.h#L44-L52, 
* then add the methods to Bindings.idl in GDevelop.js: https://github.com/4ian/GDevelop.js/blob/master/Bindings/Bindings.idl#L549-L550
* Compile GDevelop.js
* Done, you have a isLocked and setLocked method :))

3) According to `isLocked()`, we can select or not instances in method `selectInstance` (like what you did for visibility). Would be good as everything will be on a single place when it comes to selecting instances.

**Comment by 4ian** [comment] 2018-09-28 14:48
If you're on Linux, you should be able to follow the README word-by-word: https://github.com/4ian/GDevelop.js#how-to-build-

There is now continuous build done by Travis-CI on Ubuntu and @Lizard-13 manage to compile it so I'm confident you can do it on Ubuntu :)
For Windows, I've not tried in a while, it should be pretty similar. You can open an issue on the repository if you have a problem while following the readme.

**Comment by Lizard-13** [comment] 2018-09-28 18:41
Yeah, just make sure to set the tools versions listed by 4ian in the roadmap: https://trello.com/c/U6yiHQF9/139-add-a-wrapping-option-for-text-objects
I'm working in a little script that does the first download/set versions/compile the lib, just trying some things (I want to take out a "sudo" and improve the directory tree).

**Comment by blurymind** [comment] 2018-10-01 08:07
@Lizard-13 thank you for this :)
I installed manjaro linux again and will give this a try sometime in the week

**Comment by blurymind** [comment] 2018-10-03 11:33
An update on this: I installed manjaro linux and set it up for compiling. Will give this a try after I sort out the rotation widget for instances :)

**Comment by 4ian** [comment] 2018-10-03 11:57
Sweet! :) Keep us posted here about your progress. I'm going to close this issue as it's a new feature and not a bug/defect in the software.
We can continue the discussion here though. I created this trello card for tracking it on the roadmap: 
https://trello.com/c/hHugJdFj/166-add-buttons-to-lock-layers-making-objects-from-the-layer-not-selectable

Feel free to move it to "Planned" and then "Doing" when working on it :)

**Closed by 4ian** 2018-10-03 11:57 UTC
Labels: 😤Non optimal UI behavior
