### ISSUE TITLE
Changing the button text with an Action is not working on Desktop App, but working with online editor

### ISSUE THREAD

**Issue by gonzaguepatinier** [4ian/GDevelop#7219] opened 2024-12-03 01:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Problem:
Cannot change the text of a button in action.
Not working on Desktop, but working on Online Editor.

Steps:

- Created a scene
- Add Button in resources
- Add an action to create the button at the beginning of the scene and change the text

![image](https://github.com/user-attachments/assets/4e885c01-c311-4f2e-af51-3977a38bf2b2)

The text is not changed but empty on the desktop.

![image](https://github.com/user-attachments/assets/34582d04-162e-4276-8bf7-0d63750f62c6)

Did the same on the web editor, and it is working.

![image](https://github.com/user-attachments/assets/a90355bc-b42b-4176-8238-8714f1a125ef)

### Steps to reproduce

- Created a scene
- Add Button in resources
- Add an action to create the button at the beginning of the scene and change the text
- Preview the scene.

### GDevelop platform

Desktop, Web

### GDevelop version

5.4.218

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*

MACOS.

>

*OS Version (e.g. Windows 10, macOS 10.15)*

macOS 10.15
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

Chrome.

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by gonzaguepatinier** [comment] 2024-12-03 11:32
[Quizz Game.json](https://github.com/user-attachments/files/17992101/Quizz.Game.json)

I believe this is the file you are referring to.

**Comment by 4ian** [comment] 2024-12-03 15:27
Have you changed anything in the PanelSprite button? Because it was modified and bugs have been introduced in it.

Do this to re-install it:
<img width="946" alt="image" src="https://github.com/user-attachments/assets/6a66ad95-ef9a-43ef-99cc-b3ef26b51fcb">

Closing as not a bug.

**Closed by 4ian** 2024-12-03 15:27 UTC
Labels: Need a game/precise steps to reproduce the issue

**Comment by gonzaguepatinier** [comment] 2024-12-03 22:33
Re-installed the Panel Sprite Button, and it's working now.

I haven't made any change to the Panel Sprite Button, that I know off, but I'm a newbie to Gdevelop so ... might have been click at the wrong place.

Issue can be closed, and thanks for your support.
