### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by kutyamacska** [4ian/GDevelop#6145] opened 2024-01-04 17:31 UTC
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0, Platform: Win32

### Additional error context

uniqueErrorId: 90e0bcb9-1f6c-4d1f-887c-19dd2ae46d6a

fu@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:509002
enqueueForceUpdate@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:467783
41113/_.prototype.forceUpdate@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:539720
value@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:1289727
61428/Ar/g</<.children<@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:413204
61428/nx/<@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:926102
fs@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:501821
ds@https://editor.gdevelop.io/static/js/main...

### Additional component context

    in nx
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in Ar
    in div
    in s
    in f
    in ix
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in ax
    in div
    in s
    in Ay
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
 ...

**Comment by ClementPasteau** [comment] 2024-01-08 08:30
Duplicate of #5933

**Closed by ClementPasteau** 2024-01-08 08:30 UTC
