### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by rhaiyid** [4ian/GDevelop#6153] opened 2024-01-07 13:25 UTC
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

uniqueErrorId: 04147bd0-a20a-4133-96a2-20c8ac8874ad

Error: Error creating WebGL context.
    at new e (https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:3032986)
    at n.value (https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:1484287)
    at n.value (https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:1483708)
    at ds (https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:501984)
    at Fu (https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:519772)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:548513)
    at Ko (https://editor.gdevelop.io/static/js/main.6d...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in mw
    in Mw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-08 08:34
Duplicate of #5956

**Closed by ClementPasteau** 2024-01-08 08:34 UTC
