### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by narteyoscar** [4ian/GDevelop#6171] opened 2024-01-10 18:38 UTC
### Describe what you were doing when the crash happened

I was working on a game project in Gdevelop version 5 app on my pc. But suddenly, my pc was freezed up so i had to quit all the programs and restart it which made me forget to save my files before. When I restarted the pc and was trying to access my gdevelop game files, they told me I have lost my files and so I need to write a crash report to Github.

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 6.1.7601 SP1, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: f78a3878-6423-4df4-ba00-51917f1391a5

Error: Error creating WebGL context.
    at new e (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:3032986)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:1484287)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:1483708)
    at ds (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/main.f3ca4708.js:2:501984)
    at Fu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/main.f3ca4708.js:2:51...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in mw
    in Mw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-18 08:40
Duplicate of #5956

**Closed by ClementPasteau** 2024-01-18 08:40 UTC
