### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by tunder228** [4ian/GDevelop#6254] opened 2024-01-24 22:42 UTC
### GDevelop version

5.3.187-9eb721662f404d9cc215467ab132bf977fb24121

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.187 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 11c923f3-bbe3-4637-a305-1736d16314e8

Error: Error creating WebGL context.
    at new e (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.187.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/2785.eefc90c7.chunk.js:2:3438735)
    at n.value (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.187.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/283.8113e3ca.chunk.js:1:1536482)
    at n.value (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.187.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/283.8113e3ca.chunk.js:1:1535903)
    at ds (file://...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aT
    in jT
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in KL
    in div
    in n
    in oa
    in div
    in xO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in u
    in j
    in h
    in h
    in Z
    in d
    in ee
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n...

**Comment by tunder228** [comment] 2024-01-24 22:43
My game says that I need to back up my game file.

**Comment by ClementPasteau** [comment] 2024-01-25 08:45
Duplicate of #5956

**Closed by ClementPasteau** 2024-01-25 08:45 UTC
