### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by CNJ03** [4ian/GDevelop#1805] opened 2020-06-09 21:30 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: n[q[((q[(w >> 2)] + 16) >> 2)]] is not a function
    at Ga (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a:25:4336)
    at Resource.GetName.Resource.GetName [as getName] (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a:75:719532)
    at y (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:292770)
    at v._renderItemRow (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:499557)
    at file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:500787
    at file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:593418
    at Wi (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:90462)
    at Co (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:102773)
    at Ua (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:128044)
    at Fa (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:128428)
    at Tu (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135464)
    at Eu (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:134844)
    at Iu (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135940)
    at Ue (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:47510)
    at On (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:68168)
    at HTMLDocument.i (file:///C:/Users/cnjso/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:350020)
```

## Component stack (don't write anything here)
```

    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in div
    in div
    in div
    in t
    in t
    in o
    in a
    in v
    in div
    in t
    in div
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in C
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in div
    in W
    in G
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Z
    in b
```

## Other details
* IDE version: 5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta95 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment] 2020-06-09 21:50
Duplicate of #1792

**Closed by 4ian** 2020-06-09 21:50 UTC
