### ISSUE TITLE
Editor crash - wasm error - possible auto-update corrupted the app

### ISSUE THREAD

**Issue by magicalbathmat** [4ian/GDevelop#6121] opened 2023-12-22 18:09 UTC
### Describe what you were doing when the crash happened

Was working on my game.  Saved after a couple of hours of working, shut down my laptop and took a shower.  So, after I am done I start up my computer and open GD.  Go to my events screen which was fine literally 30 minutes earlier and now it's in shambles.  All of my physics2 extensions are broken.  Go to add extension again and I get this weird message.  Please help and fix this issue.

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 900fe55f-9504-46ae-84ff-76136666ff8e

RuntimeError: null function or function signature mismatch
    at wasm://wasm/00b41e4e:wasm-function[4194]:0x1cc732
    at BehaviorMetadata.GetRequiredBehaviorTypes.BehaviorMetadata.GetRequiredBehaviorTypes [as getRequiredBehaviorTypes] (file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1248064)
    at file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:932166
    at file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app...

### Additional component context

    in ax
    in div
    in s
    in Ay
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Wy
    in n
    in t
    in Unknown
    in Yy
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
...

**Comment by ClementPasteau** [comment] 2024-01-03 14:05
Duplicate of #5898 

The app is in a corrupted state when this happens.
When you restart GDevelop, does it work again?
If not, could you zip it and share your project here? or via email at hello@gdevelop.io

**Comment by ClementPasteau** [comment] 2024-01-03 14:06
If it doesn't work when restarting the app, I would suggest uninstalling and reinstalling GDevelop.
It is possible an auto-update went wrong.

**Comment by magicalbathmat** [comment] 2024-01-03 20:24
I actually uninstalled and rolled back to the previous version. Everything
has worked perfect since then.

**Comment by ClementPasteau** [comment] 2024-01-04 08:38
thanks for the update.
You should try using the latest version, I believe it should work fine and it was just a faulty update.

**Closed by ClementPasteau** 2024-01-04 08:38 UTC
Labels: 💥crash
