### ISSUE TITLE
Physics polygon removed in GD5 but present in GD4?

### ISSUE THREAD

**Issue by SomeWeirdo** [4ian/GDevelop#803] opened 2018-12-15 02:26 UTC
Currently in GD5, the physics behavior only allows the object shape to be a rectangle or a circle, even when changing the hit box to a custom polygon, it won't matter. As far as I know, there is a polygon option in the physics behavior on GD4. I'm not sure if I'm just missing something in GD5 but this is highly impractical as my game unfortunately deals with triangles and rounded edge rectangles, which is a terrible combination for a rectangle only physics shape.

**Comment by zatsme** [comment] 2018-12-15 12:56
A new physics engine is coming with polygon support, the visual polygon editor is not yet done so we have to wait a while.  GD5 is still relatively new and function is being added almost every week thumbsup

**Comment by 4ian** [comment] 2018-12-15 13:48
It's tracked in this feature card on the roadmap: https://trello.com/c/rzomYC61/181-support-custom-hitboxes-for-physics-engine :) 
A new physics engine is being added by @Lizard-13 - and I think he was planning on adding support for polygon but this is a pretty hard job to come up with a good editor for this, so might take a while.

**Comment by 4ian** [comment] 2018-12-15 13:48
I'm closing the issue as it's not a bug

**Closed by 4ian** 2018-12-15 13:48 UTC

**Comment by jjhesk** [comment] 2022-03-15 08:12
where I get find some polygon example? does this polygon feature works in GD5 now?
