### ISSUE TITLE
Lock position/rotation button not effective

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#785] opened 2018-12-03 19:01 UTC
## Describe the bug
In the scene editor you can lock the position and angle of an instance, but it does not work!

![image](https://user-images.githubusercontent.com/17770123/49395047-51a29a80-f72d-11e8-8b00-8406153a6728.png)

Once you check this button you can no longer select the instance, however you can drag select and once you've done that you can use any of the widgets to change the instance.

I believe this is unexpected behaviour and therefore a bug.

**Comment by Bouh** [comment] 2018-12-03 20:13
I'have selected the instance by list of instance and we have the widgets, and in properties we can aslo change the all values when lock option in checked

**Comment by 4ian** [comment] 2018-12-03 20:21
Lock is meant only as a way to not being able to "select" the instance from the scene editor. So Instance list is fine. Changing properties once it's selected is also fine. 
But being able to select it by clicking and dragging to draw a selection is indeed not the intended behavior and should be fixed if it's the case.

**Comment by zatsme** [comment] 2018-12-03 20:45
I might be being stupid now, but if you no longer can select or drag select, then it will be a problem to find the instance in the list if you have a lot.

Surely the best behavior would be to be able to select the instance, but to hide the widgets?  That way it would be much easier to unlock the instance when required and at the same time make it impossible to move/rotate/resize in the editor!

🤔

**Comment by Lizard-13** [comment] 2018-12-03 21:54
Note that it isn't so hard to find locked instances since there's a lock icon in them.
But I have to admit that if there are tons of instances, the instances panel is not the best friend, with the instances ordered in an "arbitrary" way, not Z-order nor object type, I think it's the order in which they were added.

**Comment by blurymind** [comment] 2018-12-04 00:05
perhaps when an instance gets locked, it should also become deselected?

**Comment by 4ian** [comment] 2018-12-04 00:14
> I might be being stupid now, but if you no longer can select or drag select, then it will be a problem to find the instance in the list if you have a lot of them.

The way it was done in GD4 was that, when you right click on the instance, you had an option to unlock it.

> Surely the best behavior would be to be able to select the instance, but to hide the widgets? That way it would be much easier to unlock the instance when required and at the same time make it impossible to move/rotate/resize in the editor!

The issue is that if for example you select a bunch of instances, including the locked instance, then moving a non locked instance will also move the locked instance (at least that's how it would work right now).

But maybe ideally we should be able to still select them, but any drag/resize/angle should not do anything. Should we also show the properties in the left panel? I think so otherwise you have no way to unlock the instance.

**Comment by zatsme** [comment] 2018-12-04 06:31
> But maybe ideally we should be able to still select them, but any drag/resize/angle should not do anything. Should we also show the properties in the left panel? I think so otherwise you have no way to unlock the instance.

This is how I thought it should work, and why I reported the bug 😄

**Closed** 2022-01-31 14:08 UTC
Labels: 👌good first issue, 😤Non optimal UI
