### ISSUE TITLE
PLOBLEM WITH GEDEVELOP PISKEL

### ISSUE THREAD

**Issue by alex1san2to** [4ian/GDevelop#1845] opened 2020-07-01 14:22 UTC
![image](https://user-images.githubusercontent.com/67696530/86253456-f5169400-bb8a-11ea-91db-b911f35bc2ce.png)

Please double check  the bug 
## To Reproduce
1. Go to 'GDEVELOP'
2. Click on 'EDIT WITH PISKEL'
3. TOP MENU WILL BE ALL WHITE AND I CANNOT SAVE

![image](https://user-images.githubusercontent.com/67696530/86254243-ed0b2400-bb8b-11ea-8f59-d5f2f9e1f3db.png)

## Other details
* I3 PROCESSOR, 4G RAM
*GDEVELOP 5,BETA96
W10
* IT ALWAYS HAPPENS

**Comment by 4ian** [comment] 2020-07-01 15:51
Duplicate of #1411
Please don't write using ALL CAPS, it looks like you're screaming and is considered bad taste on the internet. Thanks!

**Closed by 4ian** 2020-07-01 15:51 UTC
