### ISSUE TITLE
"Take into account linked objects" false and all others if one doesn't exist

### ISSUE THREAD

**Issue by properson** [4ian/GDevelop#940] opened 2019-02-18 01:45 UTC
## Describe the bug
Not sure if this is a bug, but using other conditions with the TIALO one might return false for all of them if that linked object doesn't exist. This is very annoying with things (for example, a bullet trail is added to a bullet. if that bullet trail doesn't exist, you use that condition, and add another condition like "Health of Enemy is <=0", the enemy is unable to be killed unless the bullet trail exists in the game world.

## Other details
* Please disable the "return false for everything in that event" for linked objects. It's halting my work right now.

**Comment by zatsme** [comment] 2019-02-18 09:36
I don't follow the issue, can you post some example events or better post a small game example showing the problem.

**Comment by Lizard-13** [comment] 2019-02-18 10:07
I think I get it. Imagine you link A and B, then in an event you can pick the linked objects through the linked condition and in the actions you want to move A. Now also imagine there's no B (no B in scene or picked list), you can pick the linked objects two ways:
- Pick all A linked to B: There's no B so there won't be A  >>  False (and A won't move)
- Pick all B linked to A: No B so no B will be picked but A is unchanged  >>  False (and A won't move) >> Should work this way?

The related code is this one:
https://github.com/4ian/GDevelop/blob/d37ef3004121d2c2fe6613afadbbfa92f1b4b33b/Extensions/LinkedObjects/linkedobjects.js#L115-L122
The first return is for the first case so it's ok, the second one is the "problematic" one as it makes it fall if the second objects list is empty (to "fix" it we should remove the "return" so it just does the pick, and then return true). But not sure if we should change it...

@properson Does it help if instead the condition you use the action to pick linked objects?, as it isn't a condition the "falses" won't matter :) 
(if the action works there's no need to change anything).

**Comment by zatsme** [comment] 2019-02-18 10:19
As the question seemed to involve some objects and also variables I'm sure there's an alternative way to achieve what he wants.  🤔

I'm sure the logic must be wrong in his events 🙄

The condition looks like it's working as designed... to me 🙂

**Comment by properson** [comment] 2019-02-18 19:43
> @properson Does it help if instead the condition you use the action to pick linked objects?, as it isn't a condition the "falses" won't matter :)
> (if the action works there's no need to change anything).

Yes! The action works. Thanks for your help. My explosions now damage them and kill them.

**Comment by 4ian** [comment] 2019-02-18 22:27
Might be worth explaining this on the wiki page :) I've added a note here: http://wiki.compilgames.net/doku.php/gdevelop5/all-features/linked-objects but feel free to rewrite/improve.

**Comment by 4ian** [comment] 2019-02-18 22:28
Closing as it's not a bug

**Closed by 4ian** 2019-02-18 22:28 UTC
