### ISSUE TITLE
An error occured in the Instance editor ...

### ISSUE THREAD

**Issue by dagode** [4ian/GDevelop#6355] opened 2024-02-17 21:03 UTC
### Describe what you were doing when the crash happened

<img width="524" alt="Screenshot 2024-02-17 215806" src="https://github.com/4ian/GDevelop/assets/104324119/1221f54b-e7cf-4698-a0b1-5aa352fbf6b1">

I am not sure, maybe because I was opening the preview too frequently ?
I don't have much events or sprites on the scene too.

### GDevelop version

This version of GDevelop is: 5.3.180

### Platform info

Microsoft windows 11 home.

**Comment by ClementPasteau** [comment] 2024-02-19 13:17
Duplicate of #5956 - Thanks for reporting, no solution found yet

**Closed by ClementPasteau** 2024-02-19 13:17 UTC

**Comment by JTSimmsTV** [comment] 2025-10-15 01:09
This happened to me and I was so confused everything I just worked on is gone everything just everything is gone
