### ISSUE TITLE
When renaming object, event loop are not handle

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1351] opened 2020-01-03 18:06 UTC
## Describe the bug
When renaming an object, events loop are not handled. (For each and Repeat)
It's handled in expression from standard event btw.

## To Reproduce

1. Setup a object
2. Add event For each, and Repeat.
3. Setup the expression in these events. ( `Count(NewObject)` for Repeat)
4. Rename the object
5. Nothing as change.

## Other details
B83

**Comment by 4ian** [comment] 2020-01-03 19:12
Yep this has been there forever 😬
We would need to have the events to be able to expose parameters so that they can be changed when refactoring.

**Comment by 4ian** [comment] 2020-02-22 11:44
Marking this as a good first issue because this would need a bit of changes in the C++ base classes for the event, so that they are able to expose a `std::vector` of `ParameterMetadata`. Then, use this in the `WholeProjectRefactorer` (and related classes) to also update these parameters :)

**Comment by Aparna-Sakshi** [comment] 2020-02-27 16:39
Could you please help me understand how to use expressions, at first I typed them in javascript code(I have checked the GDevelop wiki events->expressions), and made it a sub event to Repeat. Also nothing is visible in preview when I run it(I created a sprite object), is there any mistake am I doing?

**Comment by 4ian** [comment] 2020-02-27 17:46
@Aparna-Sakshi The GitHub is not made for this, it's only for GDevelop development related discussion. Please ask on the forum! Thanks

**Comment by Aparna-Sakshi** [comment] 2020-02-29 10:53
I am extremely sorry for this. Where can I ask such questions question
(which channel in discord )?  I am sorry to bother you with silly questions.

**Comment by 4ian** [comment] 2020-02-29 10:58
Ask this question on the Discord ;) You should find a channel for general questions

**Comment by gautamv95** [comment] 2020-03-17 07:07
I would like to work on this, @4ian thanks for the info, will take a look at this

> Marking this as a good first issue because this would need a bit of changes in the C++ base classes for the event, so that they are able to expose a `std::vector` of `ParameterMetadata`. Then, use this in the `WholeProjectRefactorer` (and related classes) to also update these parameters :)

**Comment by utkarshshri1016** [comment] 2020-04-01 17:06
>  Renaming an object at a particular event doesn't change the object name in previous events 
>
Is this Issue similar
@Bouh @4ian

**Comment by 4ian** [comment] 2020-04-01 18:26
It's not super clear @utkarshshri1016, please include more details in your message.

**Comment by Quarkstar** [comment] 2020-04-13 05:10
Has it been fixed? I cannot reproduce it in Beta89. Or do I misunderstand it?


![test](https://user-images.githubusercontent.com/32167255/79093848-1fc12f80-7d88-11ea-8645-7488d33edb2f.gif)

**Comment by 4ian** [comment] 2020-04-13 08:49
@Quarkstar To see the issue, either use an expression in the "Repeat" (`MyObject.Variable(test)` instead of 100) or use a For Each event with an object. You'll see that both are not renamed.

To fix this, events must be added a method "GetAllParametersWithMetadata" (or similar name to find) that will return a std::vector of pairs, containg a pointer to the gd::Expression (the value of the parameter) and a gd::ParameterMetadata (the "metadata").
Then, we:
* add a method similar to `RenameObjectInConditions`, which is called `RenameObjectInEventParameters`, that call `GetAllParametersWithMetadata` on the event, and then do the same thing as `RenameObjectInConditions`.
* Call `RenameObjectInEventParameters` in `RenameObjectInEvents`.
* Implement `GetAllParametersWithMetadata` in ForEachEvent.h, RepeatEvent.h. This means returning the expression that is in the BaseEvent (as a pointer) and a ParameterMetadata constructed on the fly (the type is important, the rest is less important). Other events will use the default implementation, which returns an empty vector.

Recompiling GDevelop.js, and hopefully with this the "parameters" of the events should now be properly handled.

**Comment by Quarkstar** [comment] 2020-04-13 08:52
Thank you! @4ian I will try to fix it.

**Comment by gautamv95** [comment] 2020-04-14 07:30
@4ian can we use the method `GetAllExpressions()` in `RenameObjectInEventParameters()`, as with [this](https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Events/Builtin/ForEachEvent.cpp#L57) and [this](https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Events/Builtin/RepeatEvent.cpp#L36), we can get access to that `gd::Expression` parameter and modify it?

With this, we won't have to make the method `GetAllParametersWithMetadata()`
> To fix this, events must be added a method "GetAllParametersWithMetadata" (or similar name to find) that will return a std::vector of pairs, containg a pointer to the gd::Expression (the value of the parameter) and a gd::ParameterMetadata (the "metadata").

**Comment by Quarkstar** [comment] 2020-04-14 08:34
> @4ian can we use the method `GetAllExpressions()` in `RenameObjectInEventParameters()`, as with [this](https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Events/Builtin/ForEachEvent.cpp#L57) and [this](https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Events/Builtin/RepeatEvent.cpp#L36), we can get access to that `gd::Expression` parameter and modify it?
> 
> With this, we won't have to make the method `GetAllParametersWithMetadata()`

Thank you! And I think metadata is important, because expression is just a string, and we need to know more information about it(metadata) to decide which part needs to be replaced.

**Closed** 2020-04-18 16:24 UTC
Labels: ⚙️ Addition required in GDevelop.js/GD Core (C++), 🐛 bug, 👌good first issue
