### ISSUE TITLE
Editor hang when opening a large 3D game project

### ISSUE THREAD

**Issue by ikmalsaid** [4ian/GDevelop#5460] opened 2023-07-04 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Opening a large 3D game project will hang the editor and need to force close it.

### Steps to reproduce

[Facebook.webm](https://github.com/4ian/GDevelop/assets/35127268/ffd4d02a-0668-4983-91ee-513ffedf0c10)

### GDevelop platform

Desktop

### GDevelop version

5.2.166

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
>Windows 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>-

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>-

</details>

### Additional context

Additional info: RAM and CPU usage jump so high when it hangs

**Comment by ikmalsaid** [comment] 2023-07-04 11:09
Additional info: RAM and CPU usage jump so high when it hangs

**Comment by AlexandreSi** [comment] 2023-07-05 07:42
Hi @ikmalsaid 
Sorry for the inconvenience!
If it happens each time you open your project, could you maybe check what is displayed in the console in the developer tools (you can open them using the shortcut Ctrl + Shift + i)?

**Comment by ikmalsaid** [comment] 2023-07-05 11:03
Hi @AlexandreSi 
Thanks for the reply!
Here is the screenshot of the developer tools:

![Screenshot (30)](https://github.com/4ian/GDevelop/assets/35127268/a64f9119-eefb-4f23-acfd-7ea661f3c97c)

**Comment by AlexandreSi** [comment] 2023-07-05 16:14
Thanks for the screenshot.
There is nothing weird though in the console.
Would it be possible that you send your project (as a zip file) so that I can try to reproduce this on my computer?
If you want it to stay private, I can send you my email address directly.

**Comment by ikmalsaid** [comment] 2023-07-05 23:39
It seems like I can't upload it here. Can you send me your email instead?
Thank you

**Comment by ikmalsaid** [comment] 2023-07-05 23:45
Here's my drive link:
https://drive.google.com/drive/folders/1erzrFgTuw6RLj_b2BC2euGO0Gxrvtk-J?usp=sharing

**Comment by AlexandreSi** [comment] 2023-07-06 08:32
Ok, the bug is easily reproducible, thanks for sharing your project, we'll have a look.
As a workaround to try if you need to work on your project: on my end, it looks like the first opening of the project skyrockets the resources but if I quickly close it and reopen it, it works fine.

**Comment by ikmalsaid** [comment] 2023-07-06 08:43
Thank you for the suggestion,
However, the problem still persists and using an older GDevelop version works fine.
I guess I will work on other projects for now.

**Comment by AlexandreSi** [comment] 2023-07-10 14:16
How did you end up being stuck? Was it working on the 165 and you upgraded to 166 and it started to not work? Or did you duplicate a bunch of instances maybe, and it started to bug?

**Closed** 2023-07-10 15:31 UTC
Labels: 🐛 bug

**Comment by ikmalsaid** [comment] 2023-07-11 01:39
Yes correct, it was working fine on 164 not 165, updated to 166 and it crashed on my project.
I agree with you on the instances part, there are almost hundreds of them.
