### ISSUE TITLE
Panel Sprite 9-patch, opacity bug at beginning of the scene

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2830] opened 2021-07-21 21:03 UTC
## Describe the bug
The opacity action of a Panel Sprite is not take into account **At the beginning of the scene**.

## Example for reproduce
The red square is a Panel Sprite, run the preview, the opacity should be at 0 at the first frame, but 255 is used and the object blink.
[bug_9patch_opacity.zip](https://github.com/4ian/GDevelop/files/6858809/bug_9patch_opacity.zip)

[Original bug report on forum](https://forum.gdevelop-app.com/t/panel-sprite-9-patch-initial-opacity-oddity/33930)

## Other details
* Tested on B113 & B111

**Comment by 4ian** [comment] 2021-08-03 08:10
Investigated this quickly:
- You can remote the timer and add an action to change to the same scene to have the issue visible on the first frame (easier to see than waiting 2 seconds) :)
- Root cause is a bug in PixiJS (https://github.com/pixijs/pixijs/issues/4610), as we're using cacheAsBitmap.
- Workaround is probably to use another container and apply the alpha on it. But maybe there is something else to do.

Speaking of workaround, there is a `//TODO: Workaround a not working property in PIXI.js` that is outdated and not useful anymore (I think).

I'll assign to @ClementPasteau as it's a good issue to dive in PixiJS/how runtime objects work. Not entirely trivial though!

**Closed** 2021-08-05 12:25 UTC
Labels: 🐛 bug, 👌good first issue, 🙇‍♀️Careful thinking/design or refactoring needed

**Comment by ClementPasteau** [comment] 2021-08-05 12:30
Thanks for reporting this bug, it has now been fixed ! It should be available in the next release, in the next couple of weeks
