### ISSUE TITLE
Updating condition/action values does not update values in UI after latest update

### ISSUE THREAD

**Issue by shinobirozs** [4ian/GDevelop#1127] opened 2019-06-24 13:48 UTC
## Describe the bug
After the latest automatic update, whenever a condition or action value is updated, it was not automatically updated in the UI. User need to close the scene/external event to see the changes.

## To Reproduce
1. Go to a scene, update a condition/action sprite object.
2. Updated values not reflected in UI
3. Close the Scene
4. Open the same scene
5. Changes are reflected

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29979672/60024097-c0dfdc00-96c9-11e9-832a-dafec3c50add.gif)

## Other details
GDevelop Mac Version

**Comment by 4ian** [comment] 2019-06-24 13:53
Duplicate of https://github.com/4ian/GDevelop/issues/1126

**Closed by 4ian** 2019-06-24 13:53 UTC

**Comment by shinobirozs** [comment] 2019-06-24 13:58
Thank you.
