### ISSUE TITLE
Error adding number variable to array

### ISSUE THREAD

**Issue by brianhuster** [4ian/GDevelop#7220] opened 2024-12-03 08:19 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I cannot add number variable to array in Gdevelop. The command is run, but the array is  still empty

### Steps to reproduce

1. Create an array variable `arr`
1. Start a scene timer 'clock'
1. If the value 'clock' is greater than 1 then
         Add the value of 'clock' to array variable 'arr'
         Reset timer 'clock'
         Run Javascript 
```javascript
console.log(runtimeScene.getVariables('arr').get())
```

### GDevelop platform

Desktop

### GDevelop version

5.4.218

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>  Kubuntu

*OS Version (e.g. Windows 10, macOS 10.15)*
>  24.04.1

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> No

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> No

</details>

**Comment by 4ian** [comment] 2024-12-03 10:16
Can you share a full project reproducing the issue?

**Comment by brianhuster** [comment] 2024-12-03 11:32
Yes, this is the link (I suppose you can get access to source)
https://gd.games/brianpham/edgame

**Comment by brianhuster** [comment] 2024-12-03 15:52
Sure, here it is

[My project3.zip](https://github.com/user-attachments/files/17995578/My.project3.zip)

**Comment by 4ian** [comment] 2024-12-03 16:09
Your JS code is invalid. This is the fixed version:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/6087f4c7-7f33-47e1-8e8d-f51df65df9e5">

Closing as this is not a bug :)

**Closed by 4ian** 2024-12-03 16:09 UTC
Labels: Need a game/precise steps to reproduce the issue

**Comment by brianhuster** [comment] 2024-12-03 16:13
Thank you so much!
