### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by arow102** [4ian/GDevelop#6116] opened 2023-12-21 12:37 UTC
### Describe what you were doing when the crash happened

I went to work on my game and then this happened for the SECOND time it also happened like 1 month ago 
![IMG_0931](https://github.com/4ian/GDevelop/assets/101535997/f5a0e107-2b30-40ec-814c-d49845b55cf9)

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15, Platform: MacIntel

### Additional error context

uniqueErrorId: 0aa370f9-33fd-465d-b5ed-9c3555f789fe

i@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:2896196
ma@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:2896633
Ie@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:3033257
e@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:3033841
value@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:1484307
value@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:1483736
ds@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:502001
Fu@https://editor.gdevelop.io/static/js/main.6dfa29b9.js:2:519774
@https://editor.gdevelop.i...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in mw
    in Mw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-03 13:35
duplicate of #5987 
Need an upgrade of Pixi for fix

**Closed by ClementPasteau** 2024-01-03 13:35 UTC
