### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Ej1423** [4ian/GDevelop#4236] opened 2022-08-28 15:37 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: t.find is not a function
    at t.a (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1a92dbe2.chunk.js:1:405856)
    at t.a (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1a92dbe2.chunk.js:1:122868)
    at Qe (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1a92dbe2.chunk.js:1:1390232)
    at Yo (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:397550)
    at ks (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:443656)
    at mu (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:436416)
    at vu (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:436341)
    at su (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:433350)
    at file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384828
    at t.unstable_runWithPriority (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:460055)
    at $i (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384537)
    at Qi (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384773)
    at Ji (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384708)
    at M (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:453820)
    at Qt (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:361991)
    at HTMLDocument.i (file:///Users/JamisEM/Desktop/games/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in Qe
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in j
    in f
    in j
    in j
    in g
    in c
    in Be
    in n
    in t
    in he
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-a47ec5199eab60ac473453c8705686f737abff6a
* Arch: x64,
* Platform Name: darwin,
* System Version: 12.5.1,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.140 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by ClementPasteau** [comment] 2022-08-29 07:49
Duplicate of #4237

**Closed by ClementPasteau** 2022-08-29 07:49 UTC
