### ISSUE TITLE
Tilemap - Display Mode (index) not working in pre-view

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2259] opened 2021-02-02 15:28 UTC
Hi I made a tilemap example to day https://www.youtube.com/watch?v=zqeHTgOSpt0
and ran into a issue:
Display mode ( index ) doesn't work in a pre-view but it works in the ide
time stamp here -> https://youtu.be/zqeHTgOSpt0?t=494

**Comment by Silver-Streak** [comment] 2021-02-02 15:31
@Entr0py404 had been mentioning it on the discord. They're running b104 preview. I have some deadline stuff this week and don't have time to test, but the video does definitely seem to match up.

**Comment by 4ian** [comment] 2021-02-02 16:29
> Edit: Likewise, it seems like the boundary box issue is still not fixed.

It's not yet fixed indeed.

cc @blurymind any idea what could mess up the index display mode?

**Comment by blurymind** [comment] 2021-02-02 18:19
I couldnt figure out why the height of the boundary box is wrong

@Entr0py404 can you share your project please? It will help with finding out why its not rendering

**Comment by Entr0py404** [comment] 2021-02-02 18:25
[TileMap Test.zip](https://github.com/4ian/GDevelop/files/5913545/TileMap.Test.zip)

**Comment by Entr0py404** [comment] 2021-02-02 18:27
By the looks of it the bounding box is only accounting for used tile spaces, blank tile spaces seem to be ignored

**Comment by blurymind** [comment] 2021-02-02 18:33
hmm, that is strange. Works fine for me.
 
![weirdIndexBug](https://user-images.githubusercontent.com/6495061/106646053-1e662b00-6585-11eb-928b-f435e6c22bef.gif)

@4ian @Silver-Streak can you reproduce this bug?

**Comment by Entr0py404** [comment] 2021-02-02 18:36
I'm sorry I updated my comment it's the only using one map in the project

**Comment by Entr0py404** [comment] 2021-02-02 19:09
Thank you so very much for the tile map and the support!

**Comment by blurymind** [comment] 2021-02-02 19:10
fix here
https://github.com/4ian/GDevelop/pull/2260
@Entr0py404 thank you for reporting this and for the demo 👍 

A rather embarasing bug 😊

**Comment by blurymind** [comment] 2021-02-02 19:17
I filed a ticket for the boundary box problem
https://github.com/pixijs/pixi-tilemap/issues/108

**Comment by 4ian** [comment] 2021-02-02 19:18
@blurymind why is index converted to a string though? This should never be the case, `layerIndex` is typed as a number and if something set it to a string, then the bug is to be fixed at this location :)

**Comment by 4ian** [comment] 2021-02-02 19:19
Thanks for the report to pixi-tilemap! :)

**Comment by blurymind** [comment] 2021-02-02 19:24
> @blurymind why is index converted to a string though? This should never be the case, `layerIndex` is typed as a number and if something set it to a string, then the bug is to be fixed at this location :)

in JsExtension we are converting all numbers to strings, layerIndex is then never converted back to a number while making its way to the runtimerenderer

**Comment by 4ian** [comment] 2021-02-02 19:33
Problem is coming form here:

```
      if (propertyName in objectContent) {
        if (typeof objectContent[propertyName] === 'boolean')
          objectContent[propertyName] = newValue === '1';
        else objectContent[propertyName] = newValue;
        return true;
      }
```

newValue is a string. There should be a call to `parseFloat` if your property is a number.

**Comment by blurymind** [comment] 2021-02-02 19:37
yup, just saw it :) updating the PR now.

Having to do that for ever extension makes it a bit error prone

**Comment by blurymind** [comment] 2021-02-02 19:43
haha weird, its still a string xD

**Comment by 4ian** [comment] 2021-02-02 19:45
It's because if now it's set as a string, then it will always be considered as a string.
Anyway, let's not try to take any shortcut and let's write the thing for every property. Take a look at what the light object is doing:

```
if (propertyName === 'radius') {
        objectContent.radius = parseFloat(newValue);
        return true;
      }

      if (propertyName === 'color') {
        objectContent.color = newValue;
        return true;
      }

      if (propertyName === 'debugMode') {
        objectContent.debugMode = newValue === '1';
        return true;
      }

      if (propertyName === 'texture') {
        objectContent.texture = newValue;
        return true;
      }

      return false;
```

With this you're 100% sure that you're putting the proper property with the proper type.

**Comment by blurymind** [comment] 2021-02-02 19:49
can you have a look at the dif of the PR? I have this atm, and it still appears to be a string
  ```
  objectTileMap.updateProperty = function (
      objectContent,
      propertyName,
      newValue
    ) {
      if (propertyName in objectContent) {
        if (typeof objectContent[propertyName] === 'boolean')
          objectContent[propertyName] = newValue === '1';
        else if (typeof objectContent[propertyName] === 'number')
          objectContent[propertyName] = parseFloat(newValue);
        else objectContent[propertyName] = newValue;
        return true;
      }

      return false;
    };
```

**Comment by blurymind** [comment] 2021-02-02 20:12
Ok, updated now and the fix should be good now 👍 
@Entr0py404 you will need to update change the index values in your project's tilemaps or delete and recreate the tilemaps to be sure - after you upgrade to the fixed version

**Comment by blurymind** [comment] 2021-02-02 20:30
For the bounding box bug, I wonder if putting an empty texture tile in empty tile slots would fix it 🤔

**Closed** 2021-02-02 20:45 UTC
