### ISSUE TITLE
Top buttons and scrolling in Piskel window are somewhat broken

### ISSUE THREAD

**Issue by kryptot7** [4ian/GDevelop#1411] opened 2020-02-05 20:26 UTC
## Describe the bug
The top buttons in the Piskel window (Save, Cancel, etc.) are cut off on the right side:
![image](https://user-images.githubusercontent.com/30781325/73879624-d48c1d00-482a-11ea-8ea4-8acd275305ce.png)

This is because the window has some extra room to scroll horizontally for some reason, even though the Piskel window lacks a visible scrollbar. If you scroll to the right, you can see that two of the buttons are overlapping:
![image](https://user-images.githubusercontent.com/30781325/73880029-96dbc400-482b-11ea-9730-e775dece860d.png)

Also, now the left side of the UI is cut off.
This scrolling bug may have something to do with #1337.

## To Reproduce
1. Create a Sprite object.
2. Open the animation editing window.
3. Click "Edit with Piskel".

## Other details
* Windows 10 1909 x64
* GDevelop 5 beta 88

**Comment by blurymind** [comment] 2020-02-07 17:27
Do you also get the tablet bug? I might have a look at this tonight. Its some funky css rule somewhere being pesky

**Comment by blurymind** [comment] 2020-02-07 20:58
How the hell do you manage to get it in that state? I cant replicate it

**Comment by blurymind** [comment] 2020-02-07 21:00
I can guess what will fix it, but its impossible to test

**Comment by kryptot7** [comment] 2020-02-08 18:34
I have a trackpad, so even though there are no visible scrollbars, I can scroll horizontally and see the rest of the buttons that were cut off before.

**Comment by kryptot7** [comment] 2020-02-09 04:54
That's odd, I've opened GDevelop Piskel again and I don't see the issue...
![image](https://user-images.githubusercontent.com/30781325/74096527-315b3200-4ace-11ea-8b15-682260021602.png)
I was messing around with my Piskel files, and I also noticed that the name field is no longer editable (see the first screenshot). Maybe that has something to do with it?

**Comment by kryptot7** [comment] 2020-02-16 04:12
Try this:
* open GDevelop
* create a new project
* create a new scene
* add a Sprite
* make an animation for the Sprite
* click to edit it with Piskel
 I did this sequence, and the scrolling bug showed up again.

**Comment by alex1san2to** [comment] 2020-07-01 14:35
![image](https://user-images.githubusercontent.com/67696530/86256638-f1850c00-bb8e-11ea-8e55-bdf8681b7b6d.png)

**Comment by alex1san2to** [comment] 2020-07-01 14:36
![image](https://user-images.githubusercontent.com/67696530/86256801-24c79b00-bb8f-11ea-8899-defcde5d43e9.png)

**Comment by alex1san2to** [comment] 2020-07-01 14:40
MY IS GIVING THAT BARS ARE APPEARING ALL WHITE AND I CANNOT SAVE

**Comment by PascalLadalle** [comment] 2020-07-15 15:46
Issue still present in beta 97, only when creating a new animation, not when editing an existing one.
https://forum.gdevelop-app.com/t/slight-fix-in-the-piskel-editor/26292/3

**Comment by Silver-Streak** [comment] 2021-08-30 15:30
There's been some pretty significant changes to the integrated version of Piskel over the last few releases.

I can no longer reproduce this. Is anyone else still experiencing this in b115?

I will close this issue out if no response (or if no one can reproduce it) is received by 9/6.

**Comment by AlexandreSi** [comment] 2022-02-14 14:35
@Silver-Streak Thanks for following up on this.
I'm closing this issue given your last message and that I can't reproduce it either.

**Closed by AlexandreSi** 2022-02-14 14:35 UTC
Labels: 🐛 bug, 🔀Issue with external dependency
