### ISSUE TITLE
Special characters in filenames trigger wrong collisions

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1551] opened 2020-03-18 17:34 UTC
## Describe the bug
[A user on the forum](https://forum.gdevelop-app.com/t/a-bug-with-collision/23371/23) complained of erroneous collisions. It acted as if there was an offset between the custom hitbox and the actual sprite. After investigation, it turns out that the **@** character in the filename of one of the involved sprites was the culprit.

sample project provided by the user: https://mega.nz/#F!0UJ3ySKC!wttXww4i62E3WoDxXM9ODQ

**Comment by 4ian** [comment] 2020-03-22 15:48
Can you describe how to reproduce the error?

**Comment by PascalLadalle** [comment] 2020-03-23 14:56
Load the project, start preview, move the player towards the hole. Depending on which side you approach from, the collision is too early or too late.
Fix the file name, reload the resource and try again. The player disappears when touching the hole.

**Comment by PawBud** [comment] 2020-03-30 10:22
I am sorry but I wasn't able to recreate the situation which you just described, maybe I am doing something wrong. Can you please send a GIF or a video or even a screenshot @PascalLadalle, I think that will help a lot. Sorry for the trouble.

**Comment by PawBud** [comment] 2020-03-30 12:03
I have been trying for a few hours to find solution to fix this bug, If you may @PascalLadalle @4ian, can you please guide me as to where to start?

**Comment by PascalLadalle** [comment] 2020-03-30 17:11
I'm not a dev, sorry, just reporting the bug.
I guess there should be a check for special characters when adding a resource, giving the user an error and asking to fix the filename first.
...Or maybe GD can load the file as-is and just store internally a fixed name with special characters replaced by a valid character? 🤔 

Browsing the repo, I would guess the related files are:
Core/GDCore/Extensions/Builtin/SpriteExtension/SpriteObject.*
and perhaps:
newIDE/app/src/ObjectEditor/Editors/SpriteEditor/index.js

That's all I can say with my limited knowledge 😅

**Comment by PawBud** [comment] 2020-03-30 17:13
Thanks a lot, @PascalLadalle and I am sorry, I just thought you were a dev.

**Comment by PawBud** [comment] 2020-03-30 17:16
> ...Or maybe GD can load the file as-is and just store internally a fixed name with special characters replaced by a valid character? 
> 
yes that might indeed be a good workaround

**Comment by PawBud** [comment] 2020-03-30 17:51
Wierdly whenever I am trying to change the File name, My electron app freezes and I have to force quit everytime, Is this an issue any one is having ?

My OS : Linux 18.04
Electron-app version:- GDevelop 5.0.0 89 beta based on GDevelop.js 4.0.98-0 release

**Comment by AlexandreSi** [comment] 2023-06-23 07:51
Closing this since the project resources are not available anymore to check if the bug still exists

**Closed by AlexandreSi** 2023-06-23 07:51 UTC
Labels: 🐛 bug
