### ISSUE TITLE
Better text editor/formatting options

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#890] opened 2019-01-19 18:59 UTC
See here for the original discussion: http://forum.compilgames.net/viewtopic.php?f=19&t=11165

Basically the request is to add either:

- A better text editor for text objects to use (like the editors you see on websites, like the GD Forum)
- The ability to display an HTML page in the game (so instead of using a text object you can display nicely formatted, advanced text and images from HTML/CSS)

**Comment by 4ian** [comment] 2019-01-19 19:06
Created a card for the first point here: https://trello.com/c/oen41cpL/236-add-a-text-object-that-support-rich-text-formatting-bold-italic-colors-potentially-markup-like-markdown-html-or-bbcode

@blurymind was thinking of something similar at some point.

For the second point, I think it would be interesting to know more about the use case. Because such powerful feature is both hard to implement, costly to maintain, costly to make performant, costly to have all the features and potentially insecure if displaying user generated HTML.

(Closing as usual as it's not a bug)

**Closed by 4ian** 2019-01-19 19:06 UTC

**Comment by BWPanda** [comment] 2019-01-19 19:13
The use case is basically an easier way to store and display formatted text and images (e.g. a lengthy intro/help/info page/screen).
