### ISSUE TITLE
Drag and drop crash webpp

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1404] opened 2020-02-01 10:35 UTC
## Describe the bug
Drag and drop crash the web app

## To Reproduce
Video
https://streamable.com/l29mv

Console log
https://pastebin.com/raw/k6dJHXUD

## Other details
Only current webapp for now
Cache is clear, i've seen your webapp update last night ;)

**Comment by 4ian** [comment] 2020-02-01 11:38
Your video is very interesting ! This is triggered by no less than 3 factors:

- On the web-app, the ContextMenu is calling `buildFromTemplate` even when the menu is not opened (triggering a function that generates the crash). (this probably needs a fix)
- The function that generates the crash is crashing because it's calling isExecutable on an event that was potentially removed from memory. This is because the event move in EventsTree/index.js is made by cloning the event, inserting a new event and removing the old BUT the events sheet is not clearing the selection because it assumed the event in memory was not changed.  (this probably needs a fix: moving an event should NOT invalidates it in memory).
- I updated the web-app from a branch where I updated Emscripten so that GDevelop.js is compiled with the latest compiler... which seems generate a code that is more prone to crash here. 

It's actually a good thing that you found this crash, because it exposed a bug that is hard to find and may have created random crashes beforehand. 
You can "see" the issue because sometimes if you drag'n'drop an event that is selected (blue border around it) - it is NOT selected when dropping it.
This means that internally the selection is now pointing to an event that disappeared from memory, leading to Very Bad Things™️

I'll fix that but first revert the web-app to the old Emscripten version.

**Comment by 4ian** [comment] 2020-02-01 11:40
Well turns out that the previous version also generates a crash (a bit more randomly):

![image](https://user-images.githubusercontent.com/1280130/73591533-8e138700-44e7-11ea-80f3-31d56693f315.png)

These crashes are really the worse, I'm glad you caught one :)

**Comment by 4ian** [comment] 2020-02-01 14:18
Fixed in https://github.com/4ian/GDevelop/commit/1e1c5f7206c17866daf55dfa2d4cbb1f0fe0c2c6

Thanks a lot for spotting this and for doing the video - it was essential for me to be able to reproduce the issue! 👍👍
I've updated the web-app, hopefully everything is working properly.

**Closed by 4ian** 2020-02-01 14:18 UTC
