### ISSUE TITLE
Problems with custom fonts

### ISSUE THREAD

**Issue by UnnamedOpera** [4ian/GDevelop#536] opened 2018-06-23 09:49 UTC
## 1. Custom fonts are not loaded in exported games and in preview

**5.0.0-beta42**
![GDevelop5.0.0-beta42Print1](https://i.imgur.com/i95Lkcw.png)

**Electron v2.0.3 x64**
![Electronv2.0.3Print](https://i.imgur.com/NGGY53b.png)

## 2. Text objects with custom fonts are not displayed in Firefox

![FirefoxPrint1](https://i.imgur.com/XYcw0Sn.png)

**Without custom font**
![FirefoxPrint2](https://i.imgur.com/ZOJaZre.png)

## Additional Information and Links
Windows 7 Home Premium SP1 x64
XAMPP 7.2.5-0

**game.json with custom font** https://pastebin.com/raw/AXGVGmqh
**game.json without custom font** https://pastebin.com/raw/NrVhjP5N
**Font** https://fonts.google.com/specimen/Righteous

**Comment by Wend1go** [comment] 2018-06-23 13:11
I can reproduce that.
It doesn't seem to be related to the font. Others don't work either.
Strangely the fonts are working an my project that I started in GD4 and later moved to GD5.
Looks like it only affects new projects created in GD5.

**Comment by 4ian** [comment] 2018-07-25 22:54
Seems like an issue with the loading of the font which is done too late, the text being already rendered.
(might not happened with a larger game ^^).

Will think about how to make sure fonts are loaded. It's a bit more tricky than textures or audio, as they are included and loaded differently.

**Comment by 4ian** [comment] 2018-07-25 23:18
Also if you want to verify that it's a loading issue: in a browser during the game your reload it (Ctrl+R or Cmd+R), or if you open developers tools in the preview and reload it (Ctrl+R or Cmd+R), the font should be displayed properly (because it is in Browser cache - so loading is instant and the text can use it).

**Comment by Bouh** [comment] 2018-08-21 20:58
I have a possible lead for loading.
Currently if I have understood correctly, the game download the font file.
But if we convert the font to base64 and import it where the file is loaded in `index.html` then the loading is done directly.

Original file : [Swkeys1.ttf ](https://github.com/baylesj/Dotfiles/blob/master/.fonts/Swkeys1.ttf)(124 Ko)
[Base 64](https://pastebin.com/raw/JYtcU5em) : 171 Ko

Present 
  `@font-face{ font-family : "gdjs_font_Swkeys1.ttf"; src : url('Swkeys1.ttf') format('truetype'); }`
Future 
`@font-face{ font-family : "gdjs_font_Swkeys1.ttf"; src : url('data:font/ttf;charset=utf-8;base64,[HERE_INSERT_BASE_64_DELETE_BRACKETS]') format('truetype'); }`

**Comment by 4ian** [comment] 2018-10-21 21:44
More information about this: 

Loading of assets at the beginning of the game should wait for fonts to be loaded. We could use  https://github.com/bramstein/fontfaceobserver

**Comment by 4ian** [comment] 2018-11-12 23:50
Should be fixed by #742 :)

This will add proper selector for fonts in the text object editor. Using this, the fonts will be added as resource of the game and will be properly loaded! Tested on Chrome + Firefox.

**Closed** 2018-11-13 23:33 UTC
Labels: 🐛 bug
