### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by mikeshan55** [4ian/GDevelop#6118] opened 2023-12-22 05:11 UTC
### Describe what you were doing when the crash happened

Was typing in a value to enter into an array

### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.0.22631, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 58ff7894-f31f-40f3-9284-122e6830b4e9

RuntimeError: memory access out of bounds
    at wasm://wasm/00b41ea6:wasm-function[832]:0x495ee
    at wasm://wasm/00b41ea6:wasm-function[1266]:0x7cc81
    at wasm://wasm/00b41ea6:wasm-function[2561]:0x18aae7
    at wasm://wasm/00b41ea6:wasm-function[2590]:0x18bc10
    at wasm://wasm/00b41ea6:wasm-function[3968]:0x1c16c8
    at Function.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor [as getCompletionDescriptionsFor] (file:///C:/Users/User/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=...

### Additional component context

    in n
    in ForwardRef
    in div
    in s
    in f
    in div
    in div
    in s
    in div
    in ForwardRef
    in t
    in ForwardRef
    in div
    in div
    in a
    in Ng
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in $g
    in t
    in Unknown
    in em
    in t
    in div
    in n
    in l
    in n
    in ForwardRef(xx)
    in n
    in t
    in Unknown
    in UM
    in di...

**Comment by ClementPasteau** [comment] 2024-01-03 13:56
seems to be duplicate of #6137 which has more details

**Closed by ClementPasteau** 2024-01-03 13:56 UTC
