### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Kimjulun** [4ian/GDevelop#6119] opened 2023-12-22 09:30 UTC
### Describe what you were doing when the crash happened

Scrolling

### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.0.19044, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: f1dd14d6-c057-46c6-8c18-365652636a39

TypeError: Cannot read properties of null (reading '_batchEnabled')
    at n.value (file:///D:/Game%20Design/Gdevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1922809)
    at n.value (file:///D:/Game%20Design/Gdevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1924974)
    at n.value (file:///D:/Game%20Design/Gdevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1925394)
    at e.value (file:///D:/Game%20Design/Gdevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1930967)
    at e.value (file:///D:/Game%20Design/Gdevelop/resources/app....

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aw
    in jw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in UM
    in div
    in n
    in Ji
    in div
    in VA
    in Unknown
    in Qe
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in me
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-03 14:01
Duplicate of #5997

**Closed by ClementPasteau** 2024-01-03 14:01 UTC
