### ISSUE TITLE
Suggestions to improve the action/condition selector

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1153] opened 2019-07-14 17:50 UTC
## Description
Currently, the list that is displayed is visually difficult to use, unless you use the search. It's hard to find things - the folders containing commands. Reading text is slow and makes it a hassle, especially when the items listed are not even alphabetically sorted! I feel that we can considerably improve it with very little work. 

## Solution suggested
- First of all we absolutely need to give them alphabetical sorting. Right now the sorting makes no sense and makes it difficult to build muscle memory to scroll to items in the list. By default, they should be sorted in a logical way. Without the sorting it's pretty difficult to find anything.
- Secondly reading text takes more effort than reading symbols. We need to give folder entries icons that the user will be able to discover at a glance - instead of after scanning and reading text.

I made a crude mockup:
![screenshot](https://user-images.githubusercontent.com/6495061/61187336-30f9d600-a668-11e9-9b37-c9ff66161bc2.png)

Since we don't have top level folder icons, my suggestion for this is to use the icon of the first nested child for each folder -at least until we do have top level icons.

**Comment by 4ian** [comment] 2019-07-14 19:07
* Agree on icons, the reason it's not done is because there is no icons specified in extensions, but we can maybe use the first icon yeah - though this can lead to maybe strange icons.
* For displaying alphabetically, it's also a possibility - though this could lead to give more visibility to the first elements in the list which maybe not be the more used.

I think the problem is more in depth. It's hard to build muscle memory* because list is long (so lack of icons make it worse, and it make me reluctant to order by alphabetically). And it's too long because it's mixing too many different things in the same list. 
My idea for this is : https://trello.com/c/sRlxFnwh/303-redesign-the-action-condition-editor-dialog-to-choose-objects-first - basically allow to first choose the object which will narrow the choice to first the object (or directly a condition/action related to an extension).
  * This actually won't create extra clicks/keystrokes for power users using search.
  * Another idea is to use `Subheaders` components from material-ui for nicer visual separations, but this is only possible with shorter lists.

I plan to give a try to this idea soon, though any improvement mentioned here in the meantime are welcome :) 

* For muscle memory, I expect users to start using search when they are becoming experimented with the software. For this, the main point is to make sure that search field is focused when the window is opened and pressing enter will choose the first item in the list (which should be the case now).

**Comment by Bouh** [comment] 2019-07-14 20:29
Alphabetical order and icons are a good thing!
I'm not fan with the object list before traditionnal condition/action, but why not test new list with objects and Icons and Alphabetical order.

>  It's hard to build muscle memory because list is long

At one point the list of objects is longer than the conditions/actions, it bothers me to have a list that varies in number. It affects this muscular memory and it disrupts it.
Keep the possibility to open/close the list of objects.
But let's go with it.
We'll see in practice it may be better 🙄

**Comment by blurymind** [comment] 2019-07-14 21:31
Without alphabetical order, it is hard to find the items even without the
icons. I don't understand how not having it would have any cons. This is
indeed a part of a bigger problem - the order of selection right now
requires all actions to be displayed, which leads to a giant list. If an
object was first selected, then only the items concerning the object can
only be displayed. Refactoring the selection dialogue to use a better
selection order would potentially be a much bigger job than making it
sorted and with icons. My suggestion here is for the lower hanging fruits
that dramatically improve the you imo

**Comment by 4ian** [comment] 2019-07-15 00:07
> At one point the list of objects is longer than the conditions/actions, it bothers me to have a list that varies in number.

Fair enough, I'll give a try with two tabs "Objects" and "Non-objects and other conditions" (or actions) in the first screen.
Choosing the object first should help to reduce drastically the length of the lists.
It will also help understanding the difference between things that are related to objects, and other action/conditions (Inventory, file system, scene variables, etc...), making them more discoverable as they'll have their own list.

**Comment by Wend1go** [comment] 2019-07-15 06:34
The tabular approach sounds good. Maybe we could release a test build to the public and ask for critique on the forum.
The main issue, I have with the status quo is that some actions / conditions are hard to find with the search box like the action to set a text of a text object. So one still has to manually scroll through the actions list which without ordering is pretty cumbersome.

**Comment by 4ian** [comment] 2019-07-15 09:14
> Maybe we could release a test build to the public and ask for critique on the forum.

I added a preference to opt in (or out) of the new action/condition editor that I'm working on :) Should allow to gather feedback from people before making this the new default.

> The main issue, I have with the status quo is that some actions / conditions are hard to find with the search box like the action to set a text of a text object. So one still has to manually scroll through the actions list which without ordering is pretty cumbersome.

Yes, this is exacerbating the problem that blurymind mentioned, and does not help with the muscle memory that Bouh mentioned too.

And if you think of the increasing number of custom behaviors, and the idea that in the future we could have way more behaviors in objects, the list is going to keep increasing and increasing - the approach was fine when the list was small but does not scale for extensions and now for custom behaviors at all.
Having objects first is becoming a necessity - and I think something that is welcome for making the search of action/conditions lighter and more intuitive.

I hope to have something working soon :)

**Comment by blurymind** [comment] 2019-07-15 18:31
one thing to be careful about is not to increase the number of steps required to discover and set the action/condition. I suggested taking some ideas from clickteam's menu approach - but adding a search filter to it in the past. Here is another crude mockup
![mockup](https://user-images.githubusercontent.com/6495061/61239557-10e51800-a737-11e9-9e51-3374c9221af8.jpg)
The idea is to select the object and the action in a single menu, opening the current existing editor dialogue with them selected

**Comment by blurymind** [comment] 2019-07-15 19:33
@4ian and anyone else - try blender 2.8 for inspiration:
https://www.blender.org/download/releases/2-80/
Then try it in blender 2.79 

They did some fantastic work on the UI =) 
It's truly a huge leap

**Comment by Bouh** [comment] 2019-07-16 14:08
I like this quick menu model. I really like the fact that I see the event sheet in the background. And that makes the interface much lighter.

In Blender's new UI, the great thing is that the software only displays what is available during the context.

Except that we have two contexts and it is necessary to make a choice.
Add an event with an object, or a general event (Global variable, etc...).

In blender the choice is made according to the mode, Object mode, Edit mode, Sculpt, Pose, ...
In GD, an event is added via a single button, the context does not adapt because it is not possible to know in advance which choice the user wants to make.
That's where it gets stuck.

Blurymind's proposal is good, especially on one point, it reduces the list and it does not move by opening a category.
But it doesn't take into account the context object or general.
So I propose a small improvement which is the addition of context.
And then a little description on the flyover.

![quick_menu](https://user-images.githubusercontent.com/1670670/61301305-edc47200-a7e3-11e9-9a42-7c113ca8ada7.png)


If we stay on the current system with the selection window I propose a little bit the same idea for context.

![Sans titre](https://user-images.githubusercontent.com/1670670/61301310-ef8e3580-a7e3-11e9-8cf8-c5a46259b802.png)

**Comment by 4ian** [comment] 2019-07-16 17:23
Thanks for your suggestions :)
Lot to say but to put it simply:
* Context menu is interesting. I see the advantage of not hiding the rest of the events. Note though that menus with sub menus are often discouraged in UX best practices because they are hard to aim and a pain to scroll. Having a search is also something entirely new to develop and not doable with native context menu. For these reasons, it's not the short term solution I'm aiming for - even if this can be built later.
* Bouh is right about the "context". Whatever the solution is, once we have the user to select the object or search in the list of other conditions/actions, we drastically reduce the need for very long lists.

I'll be using a solution extremely similar to what Bouh describe with two tabs in the first screen to either choose an "Object" or a "Non-object and other conditions"  (these are the names of the tab).

* For collapsing category accordion, this might be totally removed in the new solution I have. It will for sure disappear almost entirely in the list of action/conditions for objects (the picture 2 that Bouh drawn). It might be still in the list of "Non-object and other conditions" - or maybe not I have to test.
Instead, the grouping will stay there but using subtitles ("subheader") in the list.
* These subheader can be ordered alphabetically.

Give me a bit of time (I have to tackle android update) to get something working - I'm pretty sure this will be a big improvement :) Will potentially open the way to other solutions in the future like menu/floating panels.

**Comment by 4ian** [comment] 2020-02-22 12:14
Closing as we now have a new action/condition editor - better create issue for this one in case there are enhancements to do

**Closed by 4ian** 2020-02-22 12:14 UTC
Labels: ✨ enhancement
