### ISSUE TITLE
Closing GDevelop window before the preview windows lead to a error

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4029] opened 2022-06-13 10:35 UTC
## Describe the bug
Close the main GDevelop app before closing the preview window show an error.

![image](https://user-images.githubusercontent.com/1670670/173335314-da489a9f-d2b5-442f-955c-cfb372e1eda3.png)

## To Reproduce
1. Start a preview
2. Close GDevelop (leave the preview open)

## Other details
* Only on desktop
* GD all versions
* Source [forum link](https://forum.gdevelop.io/t/solved-gdevelop-error-show-some-weird-message-when-i-close-gd-before-the-preview/40293).

**Comment by 4ian** [comment] 2022-06-13 12:24
Duplicate of #3997

**Closed by 4ian** 2022-06-13 12:24 UTC
Labels: 🐛 bug, 💥crash
