### ISSUE TITLE
Sprites display incorrectly in preview for project-resource URL on iOS app

### ISSUE THREAD

**Issue by giannpls** [4ian/GDevelop#5838] opened 2023-10-26 03:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Observing an issue on the iOS mobile app where sprites display incorrectly in the preview. The issue seems to happen after saving a project from local computer to cloud on a PC, and then opening the project on iOS. In preview, if custom size is enabled then the sprite becomes massive and covers the entire screen. If custom size is disabled, the sprite is drawn in the wrong location (looks like the center is used as the origin). Writing the objects width and height to a text object shows that the engine thinks the sprite has width and height of 1 pixel, which seems like it may cause the auto calculation of the center point to be practically on the origin. 

After saving to cloud from the local computer, the resource URL for the sprite is at project-resources.gdevelop.io. If I manually update the URL to the original asset store URL, the issue seems to go away. I downloaded both images and compared them with winmerge and they are identical. 

At this point it seems like a bug but I can’t debug the issue any further on my own. I’m concerned because this effectively rendered the iOS app useless for the affected project, and I had to manually restore the URL for all resources to get it working again.

I posted some reports on the forum for this issue:
https://forum.gdevelop.io/t/preview-broken-in-ios-app/51107?u=giannpls
https://forum.gdevelop.io/t/get-objects-to-draw-from-origin/51250?u=giannpls

### Steps to reproduce

-Create a new cloud project
-Add an object from the asset store and place it in the scene
-preview the scene, the sprite displays correctly
-using windows app, save to local computer
-using windows app, save back to cloud
-using iOS app, open the new cloud project
-using iOS app, preview the scene. The sprite displays incorrectly

### GDevelop platform

Desktop, Mobile

### GDevelop version

5.2.176

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>
Windows 11, iOS 16.6.1
*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>
iPhone 2020 SE
</details>

**Comment by giannpls** [comment] 2023-10-28 04:44
Did some digging, looks like baseTexture.resource.valid is false when the issue occurs, which I assume is related to the incorrect width/height values. Still not sure what would cause an invalid resource.

**Comment by giannpls** [comment] 2023-10-29 05:05
Did further testing, I confirmed via the image manager PixiImageManager.getPIXITexture("Pine tree.png").valid and PixiImageManager. _loadedTextures.get("Pine tree.png").valid that the texture is not valid for the resource when the issue happens. Still unclear on
- How does the preview even draw the tree when the texture is invalid. It seems like all of the animation objects use the image manager as the source of textures, so they should also have invalid data.
- When does the image manager load the textures, and is it possible to debug this from a JavaScript runtime event

**Comment by giannpls** [comment] 2023-10-29 10:45
It looks like for a project-resource URL, iOS app provides gd_resource_token in getFullURL, but windows app does not. The iOS web editor also does not provide gd_resource_token.

The resource is valid in iOS web editor and windows app, but not iOS app, so it seems like the issue follows the gd_resource_token parameter

I haven’t found a way to catch and display the promise error on PIXI resource.load() in iOS app preview using a js runtime event, but I assume the error is happening

**Comment by AlexandreSi** [comment] 2023-10-30 08:50
Hi @giannpls,
Thanks for this thorough investigation.
There might have been an issue around the authorization as you point it out. it behaves differently between the desktop app, the web app and the mobile apps.

**Comment by giannpls** [comment] 2023-10-30 12:01
@AlexandreSi Thanks for your comment. Just to clarify, were you able to find the issue or will you or someone else be able to look into it? Otherwise, I had planned to try a few more things

- I tried copying some of the loadTexture code into a JS event and storing the promise results of the PIXI resource.load() into a variable, however so far I have not been able to see that any error is caught.
- If I can successfully load the PIXI resource from a js event, I should be able to force the sprite object to take the updated texture, which should correct the issue. This could serve as a workaround, by running the event at the beginning of the scene.

**Comment by ClementPasteau** [comment] 2023-10-30 15:34
Hey @giannpls we're looking at this issue.
I'm trying to reproduce it first and will share updates

**Comment by ClementPasteau** [comment] 2023-10-30 16:29
Hey @giannpls I can't seem to reproduce the issue.
I've:
- created a project on desktop / saved locally / saved to cloud with an asset from the store
- opened it on iOS and I can correctly see it in the preview.

A few questions:
- what do you mean by "The sprite displays incorrectly" -> it doesn't appear? it displays in pink? It has wrong size?..
- when a preview is launched on iOS, it opens a webview with a URL like `https://game-previews.gdevelop.io/xxx/index.html` Are you able to open that URL on your desktop and look at the console & network calls happening? There's probably an error if something doesn't load properly

**Comment by giannpls** [comment] 2023-10-30 17:22
> Hey @giannpls I can't seem to reproduce the issue.
> 
> I've:
> 
> - created a project on desktop / saved locally / saved to cloud with an asset from the store
> 
> - opened it on iOS and I can correctly see it in the preview.
> 
> 
> 
> A few questions:
> 
> - what do you mean by "The sprite displays incorrectly" -> it doesn't appear? it displays in pink? It has wrong size?..
> 
> 

@ClementPasteau When the issue happens, if custom size is unchecked then the sprite appears normal but is drawn in the wrong location. As far is I can tell this is because the engine thinks the width and height are 1px.

If custom size is checked, the sprite becomes huge and covers the entire screen.

I should have example screenshots of these in the linked forum posts. For your second question, I will try when I have access to my PC

**Comment by giannpls** [comment] 2023-10-30 18:12
> - when a preview is launched on iOS, it opens a webview with a URL like `https://game-previews.gdevelop.io/xxx/index.html` Are you able to open that URL on your desktop and look at the console & network calls happening? There's probably an error if something doesn't load properly
> 
> 
@ClementPasteau 
I tried this and I am able reproduce the issue when I load the iOS preview URL from my windows PC. In chrome console there is a 403 error from the server on the resource URL, and then some errors from PIXI.

**Comment by giannpls** [comment] 2023-10-31 18:07
I am confused about the architecture with regard to credentials. From looking at the code for RuntimeGame and RuntimeGameResourcesLoader, I note the following:

- if gdevelopResourceToken exists in this._runtimeGame._options then credentials are not required (checkIfCredentialsRequired() returns false)

- if gdevelopResourceToken is not defined in this._runtimeGame._options, do not add gd_resource_token search param to the resource URL in getFullUrl
- if the url is not a cloud bucket (project-resources) URL, do not add gd_resource_token search param to the resource URL in getFullUrl
- if neither of the above, add gd_resource_token search parameter to the URL in getFullUrl

Observed preview behavior:
- if the preview is generated from PC, imageManager._resourcesLoader.checkIfCredentialsRequired() returns true for the PIXI resource.file
- if the preview is generated from iOS, imageManager._resourcesLoader.checkIfCredentialsRequired() returns false for the PIXI resource.file (confirmed by loading the iOS preview URL using Chrome on PC)

Based on the observed behavior, it seems that the presence of the resource token is determined by the application that generated the preview, and not the platform where the browser is running that loads the preview. Is this the expected behavior?

- When credentials are required, we do not include the resource token in the URL
- When credentials are not required, we do include the resource token in the URL

Note the issue seems to happen when credentials are not required (resource token is included in the URL). I am confused why the resource token is provided in the URL when credentials are not required. Isn't the resource token a way of providing credentials?

**Comment by giannpls** [comment] 2023-11-01 04:55
@ClementPasteau let me know if there's anything else needed from my end. Without access to the server or iOS app debug I am in doubt that I will be able to make any further progress.

**Comment by giannpls** [comment] 2023-11-01 14:09
I had some success recovering the asset by calling loadTextures() in a JS event at the beginning of the scene, which seems to succeed. Then calling _updateAnimationFrame() will cause the sprite to draw in the correct location. However, right now it only works if custom size is disabled, so need to dig a bit more to see if i can make it work with custom sizes.

`/** @type {gdjs.SpriteRuntimeObject} */const obj = objects[0]
const imageManager = runtimeScene.getGame().getImageManager()
const resource = imageManager._resources.get("Pine tree.png")

PIXI.Texture.from(
                imageManager._resourcesLoader.getFullUrl(resource.file),
                //resource.file,
                {
                  resourceOptions: {
                    autoLoad: false,
                    crossOrigin: imageManager._resourcesLoader.checkIfCredentialsRequired(
                      resource.file
                    )
                      ? 'use-credentials'
                      : 'anonymous',
                    //crossOrigin: 'use-credentials'
                  },
                }
              ).baseTexture.resource.load().then((()=>{
                console.log("loaded");
                obj.setVariableString(obj.getVariables().get("ResourcePromise"), "Loaded")
                obj._updateAnimationFrame()
                })).catch((err) => {console.error("err: ",err);obj.setVariableString(obj.getVariables().get("ResourcePromise"), err)});`

**Comment by ClementPasteau** [comment] 2023-11-02 09:45
> Can you confirm if your resources are using a project-resource URL in the cloud project?

Yes, when a project is saved in the cloud, all custom resources will be hosted on project-resources. I can confirm I have an example running with this and cannot see an issue.

> I am confused about the architecture with regard to credentials.

I think you got it in the end, but basically:
- on web/desktop applications, a security token is passed via a Cookie, thus the need of using `credentials` so that the cookie is passed
- on mobile applications, Cookies are not used and the token is passed via the URL

> So credentials will be different for iOS/mobile. But should that apply for the device building the game or the device running the game?

This logic is done when the preview is generated by the device, so when your iOS app generates the preview link, it indicates that all resource URLs will use the token in the URL, because you are on iOS.

Unfortunately, I still can't reproduce your issue from this post or the ones on the forum you created.
Would you be able to create a really simple project (only 1 asset?) and save it in a zip shared here, where we can:
- open this project on desktop
- save it on the cloud
- open on iOS from cloud
- see the bug **with a screenshot** of what it should look like / what it does

That would help a lot as otherwise, I'm shooting in the dark

**Comment by giannpls** [comment] 2023-11-03 00:56
The scene has a single sprite with a custom size at (0, 0)
![image](https://github.com/4ian/GDevelop/assets/6901161/726a3e61-5ae5-4f6d-8ba0-000594d3919a)

When I preview, the entire screen is green (as far as I can tell, the tree is being drawn much larger than the screen)
![image](https://github.com/4ian/GDevelop/assets/6901161/1811e1e6-fb73-4c6f-b275-78c5de442267)

If I disable custom size on the tree and preview, the tree is drawn offset (partially offscreen)![image](https://github.com/4ian/GDevelop/assets/6901161/12671cb5-0d9f-427b-b02a-3428ab33d825)

For this scene I disabled my JavaScript event. In my testing seems like the resource load succeeds in the event triggered at the beginning of the scene, so maybe there is a timing issue.

**Comment by ClementPasteau** [comment] 2023-11-03 10:20
Thanks @giannpls that's extremely helpful.

We're getting somewhere.
I can finally reproduce your issue.
![image](https://github.com/4ian/GDevelop/assets/4895034/ba0781ac-d502-4bc7-96c1-b1b024872356)
![image](https://github.com/4ian/GDevelop/assets/4895034/4278a870-0af8-4d77-bed1-85b318a9eae7)

Turns out, a fix has been done in the loading of the images recently but hasn't been ported to the mobile app yet (which is why I couldn't reproduce it, I was testing with the latest dev version)

I can confirm this is fixed in the latest which will be released in the next days. Sorry about the confusion!
![image](https://github.com/4ian/GDevelop/assets/4895034/1e8af7da-f806-4ab0-b37f-10c45720b821)

**Comment by giannpls** [comment] 2023-11-03 14:38
@ClementPasteau Great news! Hopefully I won't need my workaround then, but at least it was a good excuse to poke around in the engine.

**Comment by giannpls** [comment] 2023-11-10 04:23
@ClementPasteau This looks to be fixed in my testing on the 180-mobile build, will you close it or can I? I'm also curious what the fix was if you can share it.

**Comment by ClementPasteau** [comment] 2023-11-10 08:58
Great news!
I'm not entirely sure what the exact fix was, there were a few changes that have been done in the `pixi-image-manager` following the upgrade to pixi v7. (you can check the history of this file)

The fix could be this one https://github.com/4ian/GDevelop/commit/95a0012c5ecf1319dd5b310f7a73cf14ca67c378
With the update, we tried switching to a new way of loading assets which was more generic, but we had to roll back because some asset extensions were not detected properly.
Also, a typo in `crossorigin` had to be fixed later. (but shouldn't have affected the mobile app I think)

Closing the issue!

**Closed by ClementPasteau** 2023-11-10 08:58 UTC

**Comment by giannpls** [comment] 2023-11-10 12:04
Interesting, when I tried reloading the asset in a JS event, I copied the pixi code from the head of the master which looks like it is probably different than what the mobile app was using in 176. That could explain why the second attempt worked correctly.

Thanks!
