### ISSUE TITLE
Physics 2 polygons hitbox doesn't scale with the object

### ISSUE THREAD

**Issue by planktonfun** [4ian/GDevelop#4580] opened 2022-11-24 21:18 UTC
## Describe the bug
Physics 2 collision shape type polygon does not scale with the object
Expectation is physics collision shape will scale with the object just like Box and Circle shape

## To Reproduce
1. Create a sprite object
2. Add Physics behavior, change shape to polygon, create the shape of the polygon
3. Add Physics draggable behavior
4. Create 2 unscaled object and 1 scaled object
5. Preview and drag the object to test the collisions

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1837825/203863421-5b075204-afd2-4a49-8dd2-63419693acad.png)

https://user-images.githubusercontent.com/1837825/203863668-9084b4c3-d37d-476f-ab8f-8bf9d299271c.mp4

## Other details
Windows 10
Gdevelop Desktop (editor full version: 5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e, core version: 4.0.99-0-release)

**Comment by PascalLadalle** [comment] 2022-11-26 18:38
Duplicate of https://github.com/4ian/GDevelop/issues/1812 ?

**Comment by tristanbob** [comment] 2022-11-26 19:03
@planktonfun did you use the action to change the physics scale of the object, or just the normal scale action?

Taking a step back: I cannot think of a use case where the physics scale and the visual scale should be out of sync.  This will always result in unexpected behavior from the user's perspective.  My recommendation is to remove the physics scale actions and for the standard scale actions to automatically change the physics scale.

**Comment by planktonfun** [comment] 2022-11-26 20:43
> @planktonfun did you use the action to change the physics scale of the object, or just the normal scale action?

> Taking a step back: I cannot think of a use case where the physics scale and the visual scale should be out of sync. This will always result in unexpected behavior from the user's perspective. My recommendation is to remove the physics scale actions and for the standard scale actions to automatically change the physics scale.

No, I used the scene to create the object and change the size from there

**Comment by planktonfun** [comment] 2022-11-26 20:45
> Duplicate of #1812 ?
Didn't see this one, yes possible duplicate

**Comment by Silver-Streak** [comment] 2023-02-05 04:59
Closing as the issue has been linked with the original.

**Closed by Silver-Streak** 2023-02-05 04:59 UTC
Labels: 🐛 bug, 👌good first issue
