### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by Profusebug** [4ian/GDevelop#2250] opened 2021-01-30 14:01 UTC
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **[Health.zip](https://github.com/4ian/GDevelop/files/5897993/Health.zip)**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Bouh** [comment] 2021-01-30 19:17
Duplicate of #2249

**Closed by Bouh** 2021-01-30 19:17 UTC
