### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by arow102** [4ian/GDevelop#6063] opened 2023-12-12 02:49 UTC
### Describe what you were doing when the crash happened

![IMG_0854](https://github.com/4ian/GDevelop/assets/101535997/89d7f46c-8dcd-45f5-b583-e247bbc965cd)

### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15, Platform: MacIntel

### Additional error context

uniqueErrorId: 6b335ab1-5bd6-42cb-b6d3-0722add59d67

i@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:2897741
ma@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:2898178
Ie@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:3034802
e@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:3035386
value@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380607
value@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380036
ds@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:501173
Fu@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:518946
@https://editor.gdevelop.io/...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in pM
    in div
    in n
    in Ga
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by arow102** [comment] 2023-12-12 12:00
It is still happening 9 hours later 
![IMG_0857](https://github.com/4ian/GDevelop/assets/101535997/31074075-1b84-4131-8976-245a45fd1efc)

**Comment by ClementPasteau** [comment] 2023-12-12 15:03
Duplicate of #5987 
There is a conflict between this version of PixiJS and some MacOS devices. (need to upgrade to Pixi 7.3.2)
As a workaround try using another device in the meantime.

**Closed by ClementPasteau** 2023-12-12 15:03 UTC
