### ISSUE TITLE
Automatically generate collision masks for TileMap objects

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#2775] opened 2021-07-01 20:47 UTC
## Description

Currently gdevelop can parse tiled files and render tilemaps from them.
The user however still needs to manually create collision objects within GDevelop.

## Solution suggested

Tiled lets you create shape objects and collisions on tiles.
The tilemap extension can use this data to create collision shape objects - potentially the user needs to be able to:

* enable/disable this feature - for shape objects and/or tile shapes (more expensive if each tile has a collision - so not sure if we want to allow that)
* only create collisions for shape objects that are in a specific group, maybe even detect the tiled data group a collision belongs to when colliding with it

Note that the engine is not optimized to handle an object with a lot of hitboxes. This means we may have to rework how collision handling is done.

This is linked to https://trello.com/c/3B6otFoa/481-add-ability-to-automatically-generate-collision-shapes-to-the-tilemap-extension and discussed here: https://github.com/4ian/GDevelop/discussions/2366

**Comment by Bouh** [comment] 2021-07-01 21:33
Note in the checklist, the collision shapes are for the moment convex only in GD5.
The support of concave collisions does not exist.

I tell you because Tiled editor has a[ free line mode for creating collision shapes.](https://youtu.be/72x3jaJrc-0?t=304)

**Comment by Silver-Streak** [comment] 2021-07-01 22:38
To Bouh's point, I'm not sure how/if you'd be able to implement Tiled collisions unless Concave collisions became possible.

**Comment by Silver-Streak** [comment] 2021-07-03 18:29
Related to this, LDtk is going to add a collision creation method to its IntGrid layers: https://github.com/deepnight/ldtk/issues/357

As I am personally fond of/biased towards LDtk over Tiled, I'd love to see that method implemented (since that gets GD5 closer to full IntGrid support for LDtk, which has amazing possibilities)

**Comment by willianholtz** [comment] 2021-07-03 19:18
> Related to this, LDtk is going to add a collision creation method to its IntGrid layers: [deepnight/ldtk#357](https://github.com/deepnight/ldtk/issues/357)
> 
> As I am personally fond of/biased towards LDtk over Tiled, I'd love to see that method implemented (since that gets GD5 closer to full IntGrid support for LDtk, which has amazing possibilities)

My vote is the focus on Tiled, sorry @Silver-Streak  haha. I think it's simpler, direct and cleaner. And to work with tiled it's much better. I used LDtk for a while, actually I still use it, but the real thing is that I prefer Tiled. What is missing in Tiled in my opinion, is the export of maps created (one by one) in .world, which in LDtk already exists.

Opinions!

**Comment by Silver-Streak** [comment] 2021-07-03 19:26
I think both are exceptionally good tools, however:
LDtk's automapping is faster, more user controlled, and doesn't require external scriping.
LDtk's intgrid layers allows for a ton of advanced stuff, such as patrol paths and (soon) collisions
LDtk's enums are fantastic for a myriad of items in game dev.
(It's also built in a manner that would allow LDtk itself to be integrated as a native Tilemap editor, which 4ian and I already have a bounty out on. 😄 )

I think supporting both is the best path forward, but with the above in mind and my stated biases I push for LDtk.

**Comment by willianholtz** [comment] 2021-07-03 19:46
I understand your point. And I agree, I'm not prejudiced against one tool or another, I just think it's even simpler hahah
The important thing is for the GD to have something that works perfectly. It doesn't matter what it is  :smiley:

**Comment by blurymind** [comment] 2021-07-03 20:23
If one is implemented, it shouldn't be too hard to add it for the other :)

**Comment by tristanbob** [comment] 2021-07-03 21:51
Here is the bounty that I just started.  One of my upcoming projects is to remake a game that was made with the Flat Red Ball open source game engine.  I will have access to all content used, including the tiled files.  This new feature would save me time on that project.

**Comment by D8H** [comment] 2021-11-13 18:59
What do you think about a custom object?

## TileMapCollisionMaskObject
This object will not render in the game but only hold hitboxes.

![TileCollisionMask](https://user-images.githubusercontent.com/2611977/141655975-66315444-5164-4afe-b9d0-bd8473f76190.png)

### Properties
* "TileMap id" to attach the object to a `TileMapObject` (just a string?).
* "Tile type" to filter tiles using tile type from Tiled
* "Fill" and "Outline" to render the mask in the instance editor

![TileType](https://user-images.githubusercontent.com/2611977/141655933-fae413e1-7390-4dcf-a8ef-964a63d66caa.png)

### Behaviors
Behaviors can be attached to it to use the hitboxes.
For instance:
* Platform (using one `TileMapCollisionMaskObject` by platform kind)
* Pathfinding obstacle
* any other event based behavior

### Events
They can be used as any object with the "collision" condition and the "separate" action.
For instance, it can be used for spikes, water...

### Performance
Hitboxes on a grid are easy to find and it will be faster than using Rbush. It will need a new method on `RuntimeObject` to get hitboxes from a given area. This method can return all the hitboxes by default and let subclasses optimize it.

### UX
* The hitboxes will be rendered on the instances editor using the colors from properties to help debug.
* Layers can be used to hide them.
* One tile could be chosen as object icon.

**Comment by Silver-Streak** [comment] 2021-11-13 19:04
Hmmm... so the problem with this is that isn't how collision works in Tiled Tilemaps. Polygons are drawn for each tile and they can have custom shapes per tile type. 

https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-collision-editor

Unless I'm misunderstanding, the proposal above would mean each tile would just have a square shape?

**Comment by D8H** [comment] 2021-11-13 19:10
> Hmmm... so the problem with this is that isn't how collision works in Tiled Tilemaps. Polygons are drawn for each tile and they can have custom shapes per tile type.
> 
> https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-collision-editor
> 
> Unless I'm misunderstanding, the proposal above would mean each tile would just have a square shape?

No, hitboxes from a tile are inside the tile cell. Which means that if I ask "give me all the hitboxes in this rectangle", it only has to look inside the cells that this rectangle overlap and give the hitboxes of each cell.

**Comment by Silver-Streak** [comment] 2021-11-13 19:18
Hmmm...I'm not seeing the hitboxes being defined as that in Tiled. am I not seeing it in the documentation somewhere?

**Comment by D8H** [comment] 2021-11-13 19:27
> Hmmm...I'm not seeing the hitboxes being defined as that in Tiled. am I not seeing it in the documentation somewhere?

Do you mean that an hitbox defined on a tile could go outside of the tile square?

![TileOutside](https://user-images.githubusercontent.com/2611977/141656636-68fbb6d3-e62c-461b-b873-a1fd2460626d.png)

Even if its possible, I don't see a usage for it.

**Comment by D8H** [comment] 2021-11-13 20:10
> Hmmm... so the problem with this is that isn't how collision works in Tiled Tilemaps. Polygons are drawn for each tile and they can have custom shapes per tile type.

Tiles can have different hitboxes, this is not an issue. A `TileMapCollisionMaskObject` with the tile type property set to "Ladder" will contains the hitboxes of every titles with the Ladder type of the whole tilemap. This is not one instance per tile but one instance per tilemap.

**Comment by Silver-Streak** [comment] 2021-11-13 21:19
> > Hmmm... so the problem with this is that isn't how collision works in Tiled Tilemaps. Polygons are drawn for each tile and they can have custom shapes per tile type.
> 
> Tiles can have different hitboxes, this is not an issue. A `TileMapCollisionMaskObject` with the tile type property set to "Ladder" will contain the hitboxes of every titles with the Ladder type of the whole tilemap. This is not one instance per tile but one instance per tilemap.

I'm still not following what you're suggesting, I apologize. In Tiled, a large number of users custom draw their collisions (Point based polygon collision). Ladders aren't just a "ladder" collision. It's whatever the user draws in Tiled. The same is true for slopes or other weird shaped polygons that they draw.

So while all instances of "Tile #1" will have the same collision, it could be any custom shape they draw, and will be completely different from "Tile #2" which is completely different from "Tile #3". 

How would this be accounted for?

**Comment by D8H** [comment] 2021-11-13 21:59
There can be several hitboxes in an object. Even if each tile where different, it would still not be an issue.
![Hitboxes](https://user-images.githubusercontent.com/2611977/141660029-7635503c-a3b5-40e7-a065-1bde042a44d7.png)

The type is just a way to filter the tiles. For instance, the user may want to only keep the hitboxes of the tiles tag as "ladder" so he can put a Platform behavior on it with "ladder" as platform type.

**Comment by Silver-Streak** [comment] 2021-11-14 04:55
Okay, I think I follow you now. Sorry for my confusion.

Although, your idea makes me wonder if a better solution is to implement a "polygon" object, which would (in theory) allow a user to draw (convex) polygons on the scene editor, and use those for collision (by adding the platform behavior if needed). I'd imagine the object would only actually store the points of the polygon (much like the sprite collision editor does), and you could pull up the polygon object details to delete/add a point as needed. 

 In theory that would apply to more than just Tilemaps, and could allow people to more rapidly do collisions for non-tilemap games too.

One could also be created based off the collision polygon points from the Tiled tilemap file, matching up with what you're thinking?

There's even a few Javascript canvas libraries that allow for this, it seems. https://github.com/sedrakpc/angular-canvas-area-draw

**Comment by D8H** [comment] 2021-11-14 12:53
> Although, your idea makes me wonder if a better solution is to implement a "polygon" object, which would (in theory) allow a user to draw (convex) polygons on the scene editor, and use those for collision (by adding the platform behavior if needed). I'd imagine the object would only actually store the points of the polygon (much like the sprite collision editor does), and you could pull up the polygon object details to delete/add a point as needed.
> 
> In theory that would apply to more than just Tilemaps, and could allow people to more rapidly do collisions for non-tilemap games too.
> 
> One could also be created based off the collision polygon points from the Tiled tilemap file, matching up with what you're thinking?

Can you give some user stories?

I never used tile map editors before yesterday, so I'm probably missing the user workflow. My guess is that generated hitboxes must not be editable on GDevelop side but only with the tools. Because users will eventually update the tile map with their tool which would overwrite any changes if allowed.
Furthermore, the idea is probably to rely on tools to avoid to maintain a complex editor inside GDevelop.

**Comment by Silver-Streak** [comment] 2021-11-14 16:21
> Can you give some user stories?

Here's an example I've seen a few times brought up: When you're making a Sonic the hedgehog style game with large slopes, the slope is actually made up of many different tiles at completely different angles. Each "Slope" is a separate tile with a completely different polygon shape and angle.

Or in Not-A-Vania, if I did my collisions in tiled, here are two completely different slope tiles that I manually drew the collision on:

![image](https://user-images.githubusercontent.com/24237149/141689000-eeb60554-951c-461a-9782-5e1020947e09.png)
![image](https://user-images.githubusercontent.com/24237149/141689037-f14af23a-98af-459f-97d7-caf87bc7c0b7.png)

Applying a more standard "Slope" collision to both of them would be incorrect as they're not the same shape.


> Furthermore, the idea is probably to rely on tools to avoid to maintain a complex editor inside GDevelop.

Sure, I follow you. My idea just popped up because it could help solve a *lot* of complex/larger collision workflow items within GDevelop in general, including but not limited to just Tilemaps. 

A polygon editor/drawer in the scene viewer would allow folks to make larger collision shapes that spawn multiple visible areas, such as in an adventure game, compared to today where they need to remember each object's configured collision mask shape.

For the Not-A-Vania example, rather than having to create a box sprite and duplicate and stretch it all over the map numerous times, I could simply draw a larger polygons around the areas I want, then add a platform behavior to them. 
![image](https://user-images.githubusercontent.com/24237149/141689195-6a22bb99-25c4-4ff2-9b44-276cdedce966.png)

Or, if I have collision polygons/shapes set up in my tilemap, toggle an option that says "Create polygons for tilemap collision shapes" and have it create similar shapes to the above automatically. They could be view only if imported this way.

This would also enable this type of tilemap collision to be adapted for the upcoming LDTK file format, which doesn't use the same type of collision methods as Tiled Map Maker.

**Comment by D8H** [comment] 2021-11-14 16:55
> Here's an example I've seen a few times brought up: When you're making a Sonic the hedgehog style game with large slopes, the slope is actually made up of many different tiles at completely different angles. Each "Slope" is a separate tile with a completely different polygon shape and angle.
> 
> Or in Not-A-Vania, if I did my collisions in tiled, here are two completely different slope tiles that I manually drew the collision on:
> Applying a more standard "Slope" collision to both of them would be incorrect as they're not the same shape.

Yes, this is not an issue. The object will contains all the hitboxes of each tile that have been filtered over the type.
It would be boken in version 121, but this 2 PR solve the collisions issues with tiny hitboxes:
* https://github.com/4ian/GDevelop/pull/3009
* https://github.com/4ian/GDevelop/pull/3236

> Sure, I follow you. My idea just popped up because it could help solve a _lot_ of complex/larger collision workflow items within GDevelop in general, including but not limited to just Tilemaps.
> 
> A polygon editor/drawer in the scene viewer would allow folks to make larger collision shapes that spawn multiple visible areas, such as in an adventure game, compared to today where they need to remember each object's configured collision mask shape.
> 
> For the Not-A-Vania example, rather than having to create a square sprite, then duplicate and stretch it all over the map numerous times, I could simply draw a larger polygons around the areas I want, then add a platform behavior to them. ![image](https://user-images.githubusercontent.com/24237149/141689195-6a22bb99-25c4-4ff2-9b44-276cdedce966.png)

This is another subject. I personally think it would be a bad idea. At least with rectangles users are not inclined to draw concave hitboxes like an the screenshot.
The example is with a tilemap which won't have this issue anymore and I don't see other cases.

> Or, if I have collision polygons/shapes set up in my tilemap, toggle an option that says "Create polygons for tilemap collision shapes" and have it create similar shapes to the above automatically based off the tilemap collision data from the Tiled JSON. They could be view only if imported this way.
> 
> This would also enable this type of tilemap collision to be adapted for the upcoming LDTK file format, which doesn't use the same type of collision methods as Tiled Map Maker.

This is approximately the idea.

**Comment by Silver-Streak** [comment] 2021-11-14 17:52
> Yes, this is not an issue. The object will contains all the hitboxes of each tile that have been filtered over the type. It would be boken in version 121, but this 2 PR solve the collisions issues with tiny hitboxes:
> 
> * [[Platformer] Remove the rounding property #3009](https://github.com/4ian/GDevelop/pull/3009)
> * [Fix the "separate" action when there is severa obstacles. #3236](https://github.com/4ian/GDevelop/pull/3236)

Fantastic! Glad to see that's already address.



> This is another subject. I personally think it would be a bad idea. At least with rectangles users are not inclined to draw concave hitboxes like in the screenshot.
> The example is with a tilemap which won't have this issue anymore and I don't see other cases.

Good call out. While the polygon on the left is not concave (I have tested with a similar shaped collision mask in the engine) the one on the right would have to be split into two polygons to work.

That said, the collision mask editor already doesn't allow for concave polygons, a polygon object should (assumeably) have the same restriction. 

Do note: Tiled does allow concave collision shapes. You might need to account for that in some way even if you aren't using a polygon object in the engine. 

![image](https://user-images.githubusercontent.com/24237149/141692424-1b6cc05d-a1b0-474c-b72e-08f45bfaf822.png)

The above shape is fine in Tiled, despite its concave-ness.

**Comment by D8H** [comment] 2021-11-14 18:08
> Good call out. While the polygon on the left is not concave (I have tested with a similar shaped collision mask in the engine) the one on the right would have to be split into two polygons to work.

It is :wink:
![Concave](https://user-images.githubusercontent.com/2611977/141692665-71ee6954-95f6-4d21-a098-885280c0aa15.png)

> That said, the collision mask editor already doesn't allow for concave polygons, a polygon object should (assumeably) have the same restriction.
> 
> Do note: Tiled does allow concave collision shapes. You might need to account for that in some way even if you aren't using a polygon object in the engine.

Yes, it will be hard to make an UI to point out which tile has the issue. Otherwise, it's not very hard to generate convex polygons form concave ones but it will probably result to more acute angles than what a user would do or need a bit more advance algo.

**Comment by Silver-Streak** [comment] 2021-11-14 18:46
> Yes, it will be hard to make an UI to point out which tile has the issue. Otherwise, it's not very hard to generate convex polygons form concave ones but it will probably result to more acute angles than what a user would do or need a bit more advance algo.

This is another reason I wonder if it would make more sense to have a polygon object that can be generated based off tilemap collision points (making the largest feasible concave polygon for each area, including multiple concave polygons for convex shapes, etc).

I wonder if it could be done in a phased approach?  Initial implementation is generating read-only polygon objects from Tilemap collision data that users can see, then at some point later allow them to be created bythe user manually for non-tilemap purposes?

Either way, you know implementation *far* better than I would, so I defer to your judgement.

(As far as the polygon in your screenshot above, you're 100% right, I looked at my project where I had used a large map image instead of a tilemap, and assumed I had just set up a single mask in the mask editor, but it's actually two sets of polygons that are overlapping)

**Comment by D8H** [comment] 2021-11-17 00:05
There is still work to do but the hit-boxes can be generated.

![TileMapCollisionMaskRuntimeObject-Preview](https://user-images.githubusercontent.com/2611977/142084179-370f5891-6539-410a-9d53-b85873c83bb0.png)

For this example, there is 3 objects:
* Platforms
* JumpThrus
* Ladders

Here there is one object per platform type but it can be used for anything.

![TileMapCollisionMaskRuntimeObject-Properties](https://user-images.githubusercontent.com/2611977/142084160-567432ee-a531-4df3-9e4f-737c2c712e23.png)

I'm not sure how to proceed to implement the `RenderedInstance`. I would like to use the same parser I wrote in GDJS but it looks like I will have to make a library because newIDE and GDJS don't share code.

**Comment by willianholtz** [comment] 2021-11-17 12:59
Will these Hitboxes be generated by the GD or the JSon (TMX) of the tiled? Because In the screenshot, it looks to me like you added objects for each hitbox type and then selected from the dropdown box. 

Because, as you know, in Tiled, when placing the collisions, we can name the type of collision that would be, as in the case here:
![Tile](https://user-images.githubusercontent.com/23488207/142204464-3edd8afe-b3c3-4a7a-87a9-1ab3d49411b5.png)
![Ladder](https://user-images.githubusercontent.com/23488207/142204472-ef42f208-1584-4a96-918f-76e884f90ab3.png)


However, as in Tiled the types are not defined by the program but by the user, this could be bad, but as this is a third-party software, the GD user must know that he must set the type before exporting to Tiled for the GD.
So you wouldn't need to create checkboxes in GD for this task, the Json file itself would tell GD what each object is about as long as the user defines the type of object being used.

**Comment by D8H** [comment] 2021-11-17 13:09
> However, as in Tiled the types are not defined by the program but by the user, this could be bad, but as this is a third-party software, the GD user must know that he must set the type before exporting to Tiled for the GD. So you wouldn't need to create checkboxes in GD for this task, the Json file itself would tell GD what each object is about as long as the user defines the type of object being used.

It's the purpose of the "Type filter" property.

**Comment by 4ian** [comment] 2021-11-18 09:25
> I'm not sure how to proceed to implement the RenderedInstance. I would like to use the same parser I wrote in GDJS but it looks like I will have to make a library because newIDE and GDJS don't share code.

Correct, this is more or less by design (the runtime should not be depend on the IDE and vice-versa), and I encourage to use the "library" approach ("library" meaning: a JS file that is used by the IDE and GDJS). See `pixi-tilemap-helper.js` that we already did for this - maybe you can reuse/improve it?

Sadly because it's read both by the IDE and GDJS, it's written in JS and not TS.

**Comment by D8H** [comment] 2021-11-20 02:33
It will allow strange things:

https://user-images.githubusercontent.com/2611977/142711480-363254d3-ea72-4d28-aff2-197dd7f8fce7.mp4

**Comment by Silver-Streak** [comment] 2021-11-20 03:26
> It will allow strange things:

What's strange to you in the video? Looks good to me? (Also have you tested any slope shapes that aren't from rotation yet?)

**Comment by 4ian** [comment] 2021-11-20 11:47
I guess "strange" in the sense "advanced stuff that turns out to work very well"! :) 
It also seem from my point of view to work well.

**Comment by D8H** [comment] 2021-11-20 13:10
> > It will allow strange things:
> 
> What's strange to you in the video? Looks good to me? (Also have you tested any slope shapes that aren't from rotation yet?)

Not yet, I plan to search and try other tile maps when I have a 1st clean implementation. If you have some tile maps with interesting shapes in the tiles, I'm interested.

The platformer slope tests cases use triangle shaped platforms so I don't worry too much about it.

**Comment by willianholtz** [comment] 2021-11-20 14:11
@D8H  Kenny's packages have a lot of interesting stuff, like slopes.

**Comment by D8H** [comment] 2021-11-21 13:08
On the 1st proto, I used the 2 JSON file path properties like the TileMapRuntimeObject do. It was easier to implement but that may not be the best way.

I'm thinking of replacing them with a string identifier property to have only one TileMap model shared by TileMapRuntimeObject and TileMapCollisionMaskRuntimeObject.

pros:
* When we add actions to allow procedural generation or bushes smashing, changes on TileMapRuntimeObject will affect TileMapCollisionMaskRuntimeObject too.
* Lighter in memory

cons:
* TileMapCollisionMaskRuntimeObject can't work without TileMapRuntimeObject (but I guess that fine)
* Trickier to configure

Do you see any other solutions or pros and cons to these solutions?

**Comment by D8H** [comment] 2021-11-24 20:52
## Architecture
The code is missing some features, needs to be rearranged a bit and documented, but I have the general idea about its structure.

(@blurymind this might interest you)
The 1st part is about Tiled and it's the only part that dependents to it. Which mean that to support a new file format, let's say Ldtk, the only thing to do will be to:
* Parse the file to instancate the universal tile map model
* Extract the texture from the atlas to fill the texture cache

I left the implementation in GDJS in this branch (in collision, sprite and common folders).
https://github.com/D8H/GDevelop/tree/TileMapHitBoxes/Extensions/TileMap

### Tiled Json handling
* `Tiled.ts` is an exhaustive type definition of Tiled Json. 
* `TiledTileMapLoader.ts` translates a Tiled Json in a tile map model.
* `PixiTileMapHelper.ts` contains a method to build a textures cache from an atlas and a Tiled Json.

### Universal tile map model
* `TileMapModel.ts` contains a tile map model that will aim to be editable (through actions).
* `TileTextureCache.ts` is a textures cache used by the render.

### Renders (GDJS only)
* `TileMapCollisionMaskRender.ts` render hitboxes for debugging (using the model).
* `tilemapruntimeobject-pixi-renderer.ts` render the tile map (using the model).

### Renders (GUI)
* `PixiTileMapHelper.ts` contains 2 methods to help rendering the instance editor (using the model).

### Collision handling (GDJS only)
* `TransformedTileMap` a layer over the tile map model to give a fast access to transformed hitboxes.

## An independent TypeScript lib?
I wrote it in TypeScript because I just can't work without type checking. I build a JS package from it to let the GUI use it. That not really optimal, but I think it has become too big to just write it in a JS that is shared by the GUI and GDJS.
Using it as a library allow to keep the type checking but it need to press a button to update it in GDevelop code (when it's well configured).
@4ian Do you think, it could be an independent library?

## A little demo
https://user-images.githubusercontent.com/2611977/143310801-4d3eb6be-0de9-46a5-93a7-95f51fbfe23b.mp4

**Comment by Silver-Streak** [comment] 2021-11-24 21:58
Wowww. That's amazing! 

With the universal tile map model + collision handling, once we get LDTK support in, I wonder if it becomes easy enough to just set up a x/y point array entity type in LDTK for each collision type (Ladder/Jump thru/platform/etc) and then just draw collisions in the editor to have it adapted in the same way you're doing with tiled.

Either way, amazing work.

**Comment by 4ian** [comment] 2021-11-25 18:21
> @4ian Do you think, it could be an independent library?

I think it could yeah. As you mentioned it's a bit of a pain to have to deal with building the library - so maybe it could be part of the GDJS build or something automated somewhere (I'm not clear exacly where is the best place).

We could also think about making all the extensions declaration in TypeScript, but that's where we have a "conflict" with now being in the realm of the editor (which is in Flow, but even if it was not it's important to keep things separated, types of the IDE and GDJS would not live together I guess). 

So far my only concern with this is that we now have objects that have collision hitboxes but are not rendering anything on screen. This works, but we should make that clear in the interface that we have a special type of object that are invisible (a bit like the TextEntry, but these objects have collision masks)

**Comment by D8H** [comment] 2021-11-26 11:42
> > @4ian Do you think, it could be an independent library?
> 
> I think it could yeah. As you mentioned it's a bit of a pain to have to deal with building the library - so maybe it could be part of the GDJS build or something automated somewhere (I'm not clear exacly where is the best place).
> 
> We could also think about making all the extensions declaration in TypeScript, but that's where we have a "conflict" with now being in the realm of the editor (which is in Flow, but even if it was not it's important to keep things separated, types of the IDE and GDJS would not live together I guess).

I guess that the integration with the GUI side doesn't need many iterations because the code is also used by GDJS. Maybe, the sources can be used by GDJS directly and a script will allow to update it for the GUI. It's already not great to iterate on the GUI side because it need to be restarted anyway.

**Comment by blurymind** [comment] 2021-11-28 14:52
This looks very cool :) but to be fair with you I see it as a sepparate task from the ldtk parsing.

My focus  is in implementing the parsing of ldtk files at this pr:
https://github.com/4ian/GDevelop/pull/2828

While I have been trying to get it sorted and struggling with a bigger problem - such as the lack of resource dependencies in gd, the engine has been moving under my feet - being refactored :) 

If you also completely refactor the extension under my feet, while I am trying to add something to it, my goal will constantly get delayed and delayed. Can we not do that until having the ldtk parsing?

I mean I welcome a complete rewrite, but am also weary of getting regressions.

Once that is sorted and this is sorted, maybe then we could refactor it?

**Comment by D8H** [comment] 2021-12-01 01:52
> While I have been trying to get it sorted and struggling with a bigger problem - such as the lack of resource dependencies in gd, the engine has been moving under my feet - being refactored :)
> 
> If you also completely refactor the extension under my feet, while I am trying to add something to it, my goal will constantly get delayed and delayed. Can we not do that until having the ldtk parsing?
> 
> I mean I welcome a complete rewrite, but am also weary of getting regressions and more problems to deal with thrown into the mix.
> 
> Once that is sorted and this is sorted, maybe then we could refactor it? Should my pr be considered a blocker for this? Or this a blocker for the pr?
> 
> In theory, I think it wouldnt be that difficult to add the new ldtk parsing bits to the auto collisions branch which also completely refactors the helper. I can help with that too if you like, but lets get the ldtk parser stable and kicking,lets get it in first

I understand you concerns, but the collision handling needs a model to work. I knew that you where working on this extension when I started and tried to avoid modifying the existing code but it didn't seem possible to me.
I don't know which PR will be merged first but I will help to rebase if this feature happens to come out first.

**Comment by blurymind** [comment] 2021-12-01 12:27
In that case if your pr goes through first, I will recreate my ldtk parsing
pr with your new api. Maybe put you as a reviewer with @4ian if that is ok
with you?

**Comment by Silver-Streak** [comment] 2021-12-27 14:28
Hey @D8H, where are we at on this one? 

Correct me if I'm wrong, but I believe this is a blocker for @blurymind's effort around LDTK file support (which is a blocker for LDTK bundling), so I wanted to see where this was stuck at.

**Comment by D8H** [comment] 2021-12-27 15:35
> Hey @D8H, where are we at on this one?
> 
> Correct me if I'm wrong, but I believe this is a blocker for @blurymind's effort around LDTK file support (which is a blocker for LDTK bundling), so I wanted to see where this was stuck at.

It's not a blocker, if LDTK support comes 1st it will even put the merging on my part.
If we solve the library issue and the collision mask comes 1st, I will help for the merge to avoid delaying LDTK support.

**Comment by willianholtz** [comment] 2022-01-14 18:39
Hey D8H, is there any possibility in an upcoming release, this becoming Experimental for us end users to test?

**Comment by D8H** [comment] 2022-07-26 09:13
Fixed with:
* https://github.com/4ian/GDevelop/pull/3313

**Closed by D8H** 2022-07-26 09:13 UTC
Labels: ✨ enhancement, 🙇‍♀️Careful thinking/design or refactoring needed, bounty 💰
