### ISSUE TITLE
Open URL, opening new window within GDevelop

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2165] opened 2021-01-01 10:50 UTC
## Describe the bug
I am putting this as a bug as @arthuro555 is much smarter than me and he thinks it's one. :D
When using the **Open a URL or file** action, the URL is opened using a GDevelop window. According to arthuro, the code should open the URL in the browser and not a new window within GDevelop.

If this is intended behavior, can we please have an option to override this and have the URL open in the users default browser. (I am currently using a JS function to achieve this, but it would be great to have it part of the action)

## To Reproduce
![image](https://i.gyazo.com/6b44d286937e7065b20854d222b76372.png)
![image](https://i.gyazo.com/64a366a1be7da0a7c97386f9da57ea20.gif)

## Other details
- Windows 10, Preview/Window App (not within a browser)
- GDev 5.00 Beta 102

**Comment by arthuro555** [comment] 2021-01-01 11:21
https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/Electron/main.js#L25-L29
This is the code that less me to believe it is unintended behavior.

**Comment by 4ian** [comment] 2021-01-01 16:39
> According to arthuro, the code should open the URL in the browser and not a new window within GDevelop.

Correct, this is a bug and should open in an external browser! 
PR to fix this is welcome :)

**Comment by INNOVATIVEGAMER** [comment] 2021-01-03 06:44
Can somebody please help me.
I am new to this project so I am having some trouble in development.
as @arthuro555 mentioned in his comment , I tried to change some code in the main.js but saving changes and recompiling the project not changing the behavior of the application.
I commented the whole function to check actually what is going on but there was no effect on the app.
![main js - GDevelop - Visual Studio Code 03-01-2021 12_08_02](https://user-images.githubusercontent.com/55017197/103473301-0e5bff80-4dbd-11eb-8488-3eaf2c684c06.png)

**Comment by arthuro555** [comment] 2021-01-03 10:34
As this is a change with the electron process, killing the `npm run electron-<platform>` process and running it again should do the trick.

**Comment by INNOVATIVEGAMER** [comment] 2021-01-05 10:12
> This is the code that less me to believe it is unintended behavior.

Are you sure about this file ?
Because changing the code in this file is not affecting the behavior at all.
Also I think this code is for the electron runtime ,so how it will affect the openURL event action ?

**Comment by INNOVATIVEGAMER** [comment] 2021-01-07 14:24
@4ian Can you please tell me where is file related to "Open a URL or File" action is located ? :)

**Comment by 4ian** [comment] 2021-01-07 14:48
https://github.com/4ian/GDevelop/blob/b475a2ed9625d268b6924fd88cde306d666aa514/GDJS/Runtime/events-tools/windowtools.js#L172-L174

=> 

https://github.com/4ian/GDevelop/blob/b475a2ed9625d268b6924fd88cde306d666aa514/GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.js#L475

**Comment by 4ian** [comment] 2021-01-07 14:53
To fix this issue, we need to use `shell.openExternal` (https://www.electronjs.org/docs/api/shell#shell) if we're in an Electron environment (which is the case for exported games on desktop or games previewed inside GDevelop). Conveniently, the renderer has a `getElectron` method for this, which can give access to `shell`.

**Comment by INNOVATIVEGAMER** [comment] 2021-01-08 14:23
@4ian You can close this issue now :)

**Closed** 2021-01-08 14:48 UTC
Labels: 👌good first issue
