### ISSUE TITLE
Can't Launch a preview of a Scene

### ISSUE THREAD

**Issue by kobayashimaru0** [4ian/GDevelop#1683] opened 2020-04-22 05:27 UTC
Everytime i save with CTRL + S and try to lauch a preview i can't preview the scene until i close GDevelop and open again.

Attached a video here 
CAUTION: Turn the volume down!
[cant_open_the_preview_window.zip](https://github.com/4ian/GDevelop/files/4513961/cant_open_the_preview_window.zip)

**Comment by 4ian** [comment] 2020-04-23 15:37
Hey @kobayashimaru0 that's a very strange issue. Could you try to reproduce the bug but with the debugger console opened? Open it using the menu (should be the same on Windows/Linux):
![image](https://user-images.githubusercontent.com/1280130/80118696-0f2f6700-8589-11ea-863f-2c124d0c6ed8.png)

Click on Preview and when it does not work, send a screenshot of what is displayed in the console (or copy/paste here the whole content :)). Thanks!

**Comment by convictedweirdo** [comment] 2020-04-26 06:21
I'm getting the same issue on beta 92. I get this error in the console.

![image](https://user-images.githubusercontent.com/25803863/80299721-e7830d80-87d9-11ea-8511-312105d5f2f8.png)

**Comment by convictedweirdo** [comment] 2020-04-26 12:34
Removing the intro.wav file and replacing it with an ogg file seems to have fixed the issue for me. Not sure if that's important but I thought I'd share.

**Comment by 4ian** [comment] 2020-04-26 13:23
Ah very interesting! Did you somehow have another preview or program with this file opened?

**Comment by kobayashimaru0** [comment] 2020-04-26 15:04
> Hey @kobayashimaru0 that's a very strange issue. Could you try to reproduce the bug but with the debugger console opened? Open it using the menu (should be the same on Windows/Linux):
> ![image](https://user-images.githubusercontent.com/1280130/80118696-0f2f6700-8589-11ea-863f-2c124d0c6ed8.png)
> 
> Click on Preview and when it does not work, send a screenshot of what is displayed in the console (or copy/paste here the whole content :)). Thanks!
------------------------------------------------------------------------------------------------------
Sorry if it took so long to reply.
Here's the console.
thanks!

![print](https://user-images.githubusercontent.com/32204834/80311411-e213cc00-87b5-11ea-9031-04c14fce3300.PNG)

**Comment by kobayashimaru0** [comment] 2020-04-26 15:05
I tried opening the preview window on other projects as well, and they all have the same bug.

**Comment by 4ian** [comment] 2020-04-26 15:21
Thanks @kobayashimaru0, seems like the issue is the same. That's a good thing!

> I tried opening the preview window on other projects as well, and they all have the same bug.

This seems not related to the game directly, but to some sound/music being marked as still used and so can't be erased when launching a new preview, when GDevelop tries to clean the preview folder.

I'll make a workaround and publish a new version.

**Comment by 4ian** [comment] 2020-04-26 17:13
This should hopefully be fixed in 0b5980d0b667be98a8763f4d66354857753aa653

I'll try to put a new testing version online soon.

**Closed** 2023-03-21 15:49 UTC
Labels: 🐛 bug
