### ISSUE TITLE
Crash at GDevelop opening

### ISSUE THREAD

**Issue by Buckethead172** [4ian/GDevelop#5771] opened 2023-10-12 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

It crashes and says I need to report the error or create a new github account

### Steps to reproduce

<img width="1440" alt="Screenshot 2023-10-12 at 6 12 34 PM" src="https://github.com/4ian/GDevelop/assets/129423964/e4909d2b-e68d-483b-b2a2-1feb38d8b91d">

### GDevelop platform

Desktop

### GDevelop version

???

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

I don't know the version.

**Comment by PixelMartian** [comment] 2023-10-15 22:07
Is there a date on which this issue will be fixed ??

**Comment by AlexandreSi** [comment] 2023-10-16 08:57
Hi @Buckethead172,
Sorry for the inconvenience.
Could you click on the button "Report the issue on GitHub" and copy paste the stack trace here?

**Comment by Buckethead172** [comment] 2023-10-16 13:15
I'm not the best at looking at the source codes.

**Comment by Buckethead172** [comment] 2023-10-16 13:16
> Hi @Buckethead172, Sorry for the inconvenience. Could you click on the button "Report the issue on GitHub" and copy paste the stack trace here? Also, could you check on this website that your device supports WebGL2? https://webglreport.com/?v=2

Yes, my device does support WebGL2. I'm using a MacBook Air 13.4.1

**Comment by AlexandreSi** [comment] 2023-10-16 13:56
> I'm not the best at looking at the source codes.

I meant: could you click on that button when the crash happens?
![image](https://github.com/4ian/GDevelop/assets/32449369/f1c3e5f3-a09c-4702-8863-7d2332bd6b8c)

There should be content that helps us identifying the root cause of this crash.

**Comment by Buckethead172** [comment] 2023-10-16 15:48
Hey cool it worked. I hope it doesn't crash again.

**Comment by AlexandreSi** [comment] 2023-10-17 07:30
Sorry to spoil the mood but it's weird that it started working although we did nothing to fix it. 
I hope it won't crash again

**Closed** 2023-10-17 08:26 UTC
Labels: 💥crash

**Comment by Buckethead172** [comment] 2023-10-17 11:13
Lmao. That's what I said.
