### ISSUE TITLE
Shortcut is not working in pisxel. it is also very outdated and not updating so pleaser fix it 

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2005] opened 2020-10-02 09:00 UTC

**Comment by blurymind** [comment] 2020-10-02 10:54
Im afraid you need to give us a bit more data to go on with this :)
Steps to reproduce? 
outdated and not updating? What do you mean

**Comment by Bibekz-dev** [comment] 2020-10-03 02:27
1 pisxel new tools helps us to make our work easierbut its no updated now.
2. add some kind of collision box cause in topdown-games its not possible to collide with anything
3. pencil tools shortcut doesnt work etc etc

**Comment by 4ian** [comment] 2020-10-03 10:38
@Bibekz-dev Would be better if you discuss about this with members on the forum or on the Discord. Collision box are already available, and more generally it's a bit hard to understand what you need. Thanks!

**Comment by blurymind** [comment] 2020-10-03 11:18
Out of curiosity what new tools are you talking about? Piskel hasn't had
any updates for ages

**Comment by Silver-Streak** [comment] 2020-10-04 01:48
More info is definitely needed. Piskel's last release was 2018. 

![image](https://user-images.githubusercontent.com/24237149/95005133-b2b18880-05b9-11eb-8a16-126b8da5ee32.png)

For the other comments:
Collision has nothing to do with Piskel, which is an image editor. 
Collision boxes exist on all sprite objects regardless of "top down" or not, since collision is not related to the object's behaviors.

**Comment by blurymind** [comment] 2020-10-04 10:17
In reality the version of piskel that is bundled in gdevelop has a number of tools that dont exist in the 2018 - it is ahead of it.
It has an index shift brush and a palette swap tool, which I added some time ago.

**Comment by PawBud** [comment] 2020-10-04 13:01
well we do have some bugs to solve first, to be precise #1751 #1848

**Comment by 4ian** [comment] 2020-10-04 21:22
Closing this for now, if there are specific improvements these are feature requests, and if things are unclear we could improve the interface as mentioned in the other issues.

**Closed by 4ian** 2020-10-04 21:22 UTC

**Comment by Bibekz-dev** [comment] 2020-10-05 07:14
ok now happy but what i am telling you is this

add a kind of square which is invisible to players but it stops players from from touching then and gdevelop cant do that we need to write it ourself.
and pisxel needs many imrovement like its ui. it makes me feel lik i am in a browser. cause i can scroll left and right too.
so please open it

**Comment by PawBud** [comment] 2020-10-05 07:36
> ok now happy but what i am telling you is this
> 
> add a kind of square which is invisible to players but it stops players from from touching then and gdevelop cant do that we need to write it ourself.
> and pisxel needs many imrovement like its ui. it makes me feel lik i am in a browser. cause i can scroll left and right too.
> so please open it

@Bibekz-dev firstly thanks for your interest in GDevelop. To start off, we know that there are many UI issues in GDevelop. 
In fact, the issues that you have mentioned are open and are being worked upon.  Hence, This issue should be closed in order to eliminate redundancy. 
Moreover, if you want to report some issues, consider the following steps:-
1. Check if the issue is already open. 
2. If it's unreported(an issue is not open regarding the bug) then you must discuss it on our [discord](https://discord.gg/rHYNyC7) channel first and hear the GDevelop Team's opinion on this. You can also create a new topic on the [forum](https://forum.gdevelop-app.com/), The GDevelop Team will reply to your topic accordingly. 
3. If both of the aforementioned steps have been completed, you may create a new issue, with complete information like screenshots, OS build, a complete description which says, where do u see the issue, how to reproduce it, etc.

Currently, this issue does no good since as I stated in the beginning, the issues are already open.
Hope you understand, Thanks for using GDevelop :)
