### ISSUE TITLE
Functions that are called from a life-cycle function cause the game to crash on the first frame 

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2604] opened 2021-05-03 01:07 UTC
## Describe the bug

Functions that are called from a life-cycle function cause the game to crash on the first frame with this error: 
`Uncaught TypeError: Cannot read property 'func' of undefined`

![Screenshot 2021-05-02 185218](https://user-images.githubusercontent.com/8879811/116833625-8d98ee80-ab77-11eb-8359-f69819cc2d03.jpg)

## To Reproduce

1) Create a new extension
2) Create a first custom function (no events needed, but fill out the metadata so it is more obvious when it is used)
3) Add an event in a scene to call this function (required so the extension gets used)
4) Create a second custom function that has a single event (turn the background blue)
5) Create a lifecycle function (i.e. onScenePreEvents or onScenePostEvents)
6) Add your second function (turn the background blue) as an action of an event in the lifecycle function
7) Game will crash at first frame (Uncaught TypeError: Cannot read property 'func' of undefined)

## Video of problem

https://user-images.githubusercontent.com/8879811/116833970-49a6e900-ab79-11eb-87ed-2311f75ea268.mp4

# Example Game

[LifeCycleFunctionBug.zip](https://github.com/4ian/GDevelop/files/6412568/LifeCycleFunctionBug.zip)

## Other details

GDevelop 5 Beta 108

**Comment by arthuro555** [comment] 2021-05-03 05:58
Duplicate of #2495

**Comment by ClementPasteau** [comment] 2021-08-31 15:05
Closing this one in favor of #2495 as this is the same issue

**Closed by ClementPasteau** 2021-08-31 15:05 UTC
Labels: 🐛 bug
