### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by ibrahimrefai2010** [4ian/GDevelop#6232] opened 2024-01-21 13:48 UTC
### GDevelop version

5.3.187-7fbe1bd23dfee19829f238048afd4c7ac84a00cf

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0, Platform: Win32

### Additional error context

uniqueErrorId: c04e73eb-275a-456c-a83c-d5b361b3106f

TypeError: Cannot read properties of null (reading 'valid')
    at new n (https://editor.gdevelop.io/static/js/1573.fe72a661.chunk.js:2:1976260)
    at n.value (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:2212406)
    at new n (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:2211390)
    at Object.createNewInstanceRenderer (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:2234340)
    at e.getRendererOfInstance (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:1486802)
    at instancesRenderer.invoke (https://editor.gdevelop.io/static/js/28...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aT
    in jT
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in KL
    in div
    in n
    in oa
    in div
    in xO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in u
    in j
    in h
    in h
    in Z
    in d
    in ee
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n...

**Comment by ClementPasteau** [comment] 2024-01-25 08:48
Duplicate of #5896 

What were you doing when the crash happened?

**Closed by ClementPasteau** 2024-01-25 08:48 UTC
