### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Next-StepGames** [4ian/GDevelop#6248] opened 2024-01-24 13:56 UTC
### GDevelop version

5.3.187-9eb721662f404d9cc215467ab132bf977fb24121

### Platform info

System Version: 6.1.7601 SP1, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.187 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 7a023a9a-56f3-4555-8b9e-d6e9c7f49edf

Error: Error creating WebGL context.
    at new e (file:///C:/GameEngine/GDevelop/resources/app.asar/www/static/js/2785.eefc90c7.chunk.js:2:3438735)
    at n.value (file:///C:/GameEngine/GDevelop/resources/app.asar/www/static/js/283.8113e3ca.chunk.js:1:1536482)
    at n.value (file:///C:/GameEngine/GDevelop/resources/app.asar/www/static/js/283.8113e3ca.chunk.js:1:1535903)
    at ds (file:///C:/GameEngine/GDevelop/resources/app.asar/www/static/js/main.69f282b5.js:2:505654)
    at Fu (file:///C:/GameEngine/GDevelop/resources/app.asar/www/static/js/main.69f282b5.js:2:523442)
    at t.unstable_run...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aT
    in jT
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in KL
    in div
    in n
    in oa
    in div
    in xO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in u
    in j
    in h
    in h
    in Z
    in d
    in ee
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n...

**Comment by Next-StepGames** [comment] 2024-01-24 13:57
This Crash Comes When I Run GDevelop In Windows 7

**Comment by Next-StepGames** [comment] 2024-01-24 13:57
Please Reply This Issue Comes 100 Times

**Comment by ClementPasteau** [comment] 2024-01-25 08:40
Duplicate of #5956 

Do you have the same error when working on a project in https://editor.gdevelop.io ?
Could you try on different browsers as well?

It could be that your computer does not support the 3D renderer

**Closed by ClementPasteau** 2024-01-25 08:40 UTC

**Comment by Next-StepGames** [comment] 2024-01-25 12:07
Sorry I Do Not Use The 3D Renderer I Only Work With The 2D.This Problem
Comes When There Are Too Many Assets.But When I Remove That And Submit On
GD.games It Just Removes Everything and I Do Not Use Online GDevelop Editor

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
