### ISSUE TITLE
Objects loaded from external layout are displaced at first and flicker

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1285] opened 2019-11-10 09:20 UTC
## Describe the bug
When you load objects from external layout, the objects are displaced at first and cause the screen flicker for a moment. It is with Sprite objects only, Text objects loaded from external layout are not effected.

Forum topic:
https://forum.gdevelop-app.com/t/external-layer-is-flicking-every-time-i-load-the-scene/18608

## To Reproduce
1. Load some objects from external layout and reload the scene

* Please include a link to a game if possible!
[elayout-flicker.zip](https://github.com/4ian/GDevelop/files/3828259/elayout-flicker.zip)

## Other details
* Include any OS/browser version/smartphone that you're using
Windows 10 64bit
Firefox 70.0.1
* Which version of GDevelop are you using? The desktop app or the web-app?
Desktop app version beta82

**Comment by ddabrahim** [comment] 2019-11-14 20:41
It seems like, we get the same bug also if we create objects manually at the beginning of the same scene.
Forum:
https://forum.gdevelop-app.com/t/weird-visuall-glitch-when-setting-scene-to-current-scene/21449

To reproduce:
At the beginning of the scene : Create any object at position X and Y

**Comment by KinkGD** [comment] 2019-11-18 20:51
Hello, yeah i confirm this bug and this is annoying, it's why is a fadeout transition from black on each scene reload...
Not related to external event, but a bit similar : https://github.com/4ian/GDevelop/issues/879
=> If change the animation of a sprite "at the beginning of the scene" => the object flicker because the animation 0 will always be displayed before animation changes..

**Comment by Bouh** [comment] 2021-02-21 21:08
Sprite flicker because the custom size are not used for define the object at the first frame.

That mean an object with a custom size on an external layout will be created on the scene with the action "Create objects from the external layout named XXX" with the  default size of the sprite at the first frame.
And at the next frames custom size is updated. That why objects flicks :)

**Comment by Bouh** [comment] 2021-05-01 14:21
Seem it can be fixed by `object.update(this);` at the first frame in the pre render step.
@4ian is an acceptable fix?

```js

/**
     * Called to update visibility of the renderers of objects
     * rendered on the scene and give a last chance for objects to update before rendering.
     *
     * Visibility is set to false if object is hidden, or if
     * object is too far from the camera of its layer ("culling").
     */
    _updateObjectsPreRender() {
      if (this._timeManager.isFirstFrame()) {
        this._constructListOfAllInstances();
        for (let i = 0, len = this._allInstancesList.length; i < len; ++i) {
          const object = this._allInstancesList[i];
          const rendererObject = object.getRendererObject();
          if (rendererObject) {
            object.getRendererObject().visible = !object.isHidden();
          }
          // Perform pre-render update.
          object.updatePreRender(this);
          object.update(this); // Fix wrong width and height on the object when it come from an external layout at the first frame.
        }
        return;
      } else {
        // After first frame, optimise rendering by setting only objects
        // near camera as visible.
        // TODO: For compatibility, pass a scale of `2`,
        // meaning that size of cameras will be multiplied by 2 and so objects
        // will be hidden if they are outside of this *larger* camera area.
        // Useful for objects not properly reporting their visibility AABB,
        // (so we have a "safety margin") but these objects should be fixed
        // instead.
        this._updateLayersCameraCoordinates(2);
        this._constructListOfAllInstances();
        for (let i = 0, len = this._allInstancesList.length; i < len; ++i) {
          const object = this._allInstancesList[i];
          const cameraCoords = this._layersCameraCoordinates[object.getLayer()];
          const rendererObject = object.getRendererObject();
          if (!cameraCoords || !rendererObject) {
            continue;
          }
          if (object.isHidden()) {
            rendererObject.visible = false;
          } else {
            const aabb = object.getVisibilityAABB();
            if (
              // If no AABB is returned, the object should always be visible
              aabb &&
              (aabb.min[0] > cameraCoords[2] ||
                aabb.min[1] > cameraCoords[3] ||
                aabb.max[0] < cameraCoords[0] ||
                aabb.max[1] < cameraCoords[1])
            ) {
              rendererObject.visible = false;
            } else {
              rendererObject.visible = true;
            }
          }
          // Perform pre-render update.
          object.updatePreRender(this);
        }
      }
    }
```

**Comment by 4ian** [comment] 2021-05-01 14:46
I think this would be risky because we would run `update` after `updatePreRender`, so we're breaking the order of the "updates", and this could create confusing bugs in the future if some objects really on `updatePreRender` being always called last before a render.

Actually, I wonder if the fix is moving `update` to `updatePreRender` for **sprite objects** only (as @ddabrahim said: "It is with Sprite objects only, Text objects loaded from external layout are not effected."). In the sense that currently, the implementation is not entirely correct as there is a one frame latency:

1. A frame starts
2. Objects are `update`d "pre events": `_updateObjectsPreEvents` is called, and calls `update` on each object.
  * In particular for sprites, the image is updated according to the animation/frame.
  * Also behaviors "pre events"
3. Events are run (here notably, we can change the animation/image of a sprite)
4. Objects are updated "post events": `_updateObjectsPostEvents` (mainly behaviors "post events" update)
5. Objects are updated "pre render": `_updateObjectsPreRender`
  * This hides objects too far from the camera (culling)
  * `updatePreRender` is called on each object
6. Layers are updated (`_updateLayers`) (this is for layers automatically following another)
7. Finally, `render` is called which instructs Pixi.js to render the objects on screen.

The problem is as follow:
Because we only update the sprite in `update` BEFORE the events, then any change of animation/direction/frame will be done on the next frame. So one frame latency which can be visible when you create new objects from an external layout (and it's also suboptimal during the game, but you don't see it).

So we should probably move the logic updating the image of a sprite in a `updatePreRender` method of sprite. Would be a breaking change though, so might be an option to check somewhere.
I'll double check the example to make sure I'm not telling something wrong :)

**Comment by 4ian** [comment] 2021-05-01 15:58
Should be fixable by adding 
```
    updatePreRender(runtimeScene): void {
      if (this._animationFrameDirty) {
        this._updateAnimationFrame();
      }
      this._renderer.ensureUpToDate();
    }
```

to spriteruntimeobject.ts
to ensure that the proper frame is shown (even when changed just before in events, that's `_updateAnimationFrame`) and be sure that it's done before the first render (`ensureUpToDate`).

**Comment by 4ian** [comment] 2021-05-01 16:02
Update example with a second scene where we can see a similar problem: changing the animation is not applied immediately, so we can see the first animation when changing the scene: 
[elayout-flicker 2.zip](https://github.com/4ian/GDevelop/files/6409893/elayout-flicker.2.zip)

**Comment by tristanbob** [comment] 2021-05-01 17:01
> Because we only update the sprite in `update` BEFORE the events, then any change of animation/direction/frame will be done on the next frame. So one frame latency which can be visible when you create new objects from an external layout (and it's also suboptimal during the game, but you don't see it).

I think I ran into this exact problem on my Cinematic Cutscene example (https://youtu.be/_qBIZsyF4kA).  I create a large number of ships at the top of the screen and immediately change their scale to a very small number.  This caused all ships to spend one frame at full size when they were created.   I worked around this by hiding them for a few frames before making them visible.

**Closed** 2021-05-01 17:05 UTC
Labels: 🐛 bug, 👌good first issue

**Comment by 4ian** [comment] 2021-05-01 17:09
> I create a large number of ships at the top of the screen and immediately change their scale to a very small number. This caused all ships to spend one frame at full size when they were created. I worked around this by hiding them for a few frames before making them visible.

Yes sounds exactly like this issue.
So this long running bug should be fixed and sprites should now always be displayed exactly as set in the events, even at the start of the scene or when just created!

Feel free to try after the nightly build is ready (~30min).

Note that this might cause subtle rendering changes in games, but this is just a rendering artifact so won't change any gameplay/game behavior - and will probably fix similar glitches/flickering in other situations :)
