### ISSUE TITLE
New Events now showing in Events Editor

### ISSUE THREAD

**Issue by convictedweirdo** [4ian/GDevelop#1126] opened 2019-06-24 01:12 UTC
## Describe the bug

When adding a new event in the event editor, pressing ok does not show the created event. The newly created event can only be seen by closing the scene in the project manager and reopening it, or creating a new event, pressing "add action" and then cancelling it.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to scene Events (on new or saved projects, seems to be happening universally)
2. Click on Add Event
3. Scroll down to "Happens to any/all events created"
4. Pressing ok, and nothing shows in the events editor, like it has not been created (but it has).

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

Windows 10
Gdevelop Beta 74
(was non issue on Beta 73)

**Comment by convictedweirdo** [comment] 2019-06-24 01:51
![bug1](https://user-images.githubusercontent.com/25803863/59985678-4e91dc00-9676-11e9-8a83-9a6726b27b78.gif)

**Comment by Phenomena3** [comment] 2019-06-24 04:50
> The newly created event can only be seen by closing the scene in the project manager and reopening it, or creating a new event, pressing "add action" and then cancelling it.

Oh, I didn't have to close the scene & reopen, just click somewhere else and the action appeared. But there's still a delay on it and maybe the difference is because of my OS (Windows 8.1 laptop). Thank you for reporting this!

**Comment by convictedweirdo** [comment] 2019-06-24 05:12
> > The newly created event can only be seen by closing the scene in the project manager and reopening it, or creating a new event, pressing "add action" and then cancelling it.
> 
> Oh, I didn't have to close the scene & reopen, just click somewhere else and the action appeared. But there's still a delay on it and maybe the difference is because of my OS (Windows 8.1 laptop). Thank you for reporting this!

Ah yes you're correct. Seems clicking on the condition will make it display/update. 

It also seems that updating event properties is also being delayed.

![bug22](https://user-images.githubusercontent.com/25803863/59993140-6c6d3a00-9692-11e9-8d88-79cce3d3924e.gif)

**Comment by 4ian** [comment] 2019-06-24 11:58
Indeed, will fix that tonight. I'm removing the automatic update to beta 74 in the meantime.

**Comment by 4ian** [comment] 2019-06-24 21:10
Should be fixed in beta 75, sorry for the regression!
Let me know if there is anything else strange, though I've checked and everything seems back to normal :)

**Closed by 4ian** 2019-06-24 21:10 UTC

**Comment by convictedweirdo** [comment] 2019-06-24 23:12
Updating to beta 75 has rectified the issue. Thank you so much for the speedy fix
