### ISSUE TITLE
Share button error on Web Version when exporting

### ISSUE THREAD

**Issue by convictedweirdo** [4ian/GDevelop#6429] opened 2024-03-07 00:02 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The web version of GDevelop has an error preventing generating exports.  It was reported on the forum and I can confirm the issue exists.

Please see images below

### Steps to reproduce

Go to gdevelop web
Share button
Auto-build export
Failure
![snip 1](https://github.com/4ian/GDevelop/assets/25803863/6e62c77f-5260-41ec-9b83-754537537979)
![Screenshot 2024-03-07 095249](https://github.com/4ian/GDevelop/assets/25803863/91b24cb8-f18b-4da0-8a6c-8b7123cbdd3b)
![1](https://github.com/4ian/GDevelop/assets/25803863/efb40ad3-a1fe-4de6-bfd6-99108ea2d328)

![2](https://github.com/4ian/GDevelop/assets/25803863/69519bbc-80e0-4271-9e13-e4d6acec45d2)

### GDevelop platform

Web

### GDevelop version

5.3.192 web

### Platform info

Windows 11
Chrome Browser
Firefox Browser

### Additional context

**Comment by ClementPasteau** [comment] 2024-03-08 09:01
Hey @convictedweirdo thanks for reporting.
This looks like a temporary issue that happened when a new version was deployed on the web.
I can't reproduce on my side, could you check if it still happens?
If it still does, can you reload your browser and check again?

**Comment by ClementPasteau** [comment] 2024-03-08 17:12
closing as this should be fixed, let us know if not

**Closed by ClementPasteau** 2024-03-08 17:12 UTC
