### ISSUE TITLE
Tween Major performance issue 

### ISSUE THREAD

**Issue by Keevle** [4ian/GDevelop#1645] opened 2020-04-12 17:50 UTC
## Describe the bug

There seems to be a massive issue with the Opacity tween,The videos below show that just simply adding the opacity tween into a chain of events adds a HUGE performance hit compared to the Scale tween for example

## To Reproduce
Reproduce the events in the screenshots below

* If applicable, add screenshots to help explain your problem.
![](https://i.imgur.com/3KRlG84.png) - Massive 

https://streamable.com/x12b51 - Effect without the Opacity tween

![](https://i.imgur.com/kWCNP17.png)

https://streamable.com/udx3ke - Effect with the Opacity Tween
![](https://i.imgur.com/q0gI3zq.png)
## Other details
* Include any OS/browser version/smartphone that you're using
Windows 10/Latest google chrome
* Which version of GDevelop are you using? The desktop app or the web-app?
beta 89,Desktop app

**Comment by Silver-Streak** [comment] 2020-04-13 06:22
So I have no experience with tweens, however I do have some experience with deletion of objects. This might be silly, but have you tried nesting your tweens within an "For each" event with "explosion" as the taret?

Additionally, consider a "trigger once" condition on the delete explosion event once it's in the "For Each"

It'd be interesting to see if there's any performance difference.

**Comment by 4ian** [comment] 2020-04-13 07:03
It might be a performance drop directly in the engine/tween extension, because not all objects have a set/get opacity method, so the JavaScript engine has internally more work to check the existence of these methods.
We might have to add these methods to `gdjs.RuntimeObject` and see if it's better (objects that don't have the notion of opacity will simply not redefine these methods).

**Comment by 4ian** [comment] 2020-04-13 17:43
Would you have a game to reproduce the issue? I don't see anything suspicious in the code.

**Comment by Keevle** [comment] 2020-04-13 20:21
I can extract out the events into a game and post it here @4ian

**Comment by 4ian** [comment] 2020-04-13 21:11
Would be great! Being able to reproduce the issue will be very useful

**Comment by Keevle** [comment] 2020-04-13 21:48
@4ian 
[proj.zip](https://github.com/4ian/GDevelop/files/4472036/proj.zip)

**Comment by 4ian** [comment] 2020-04-14 08:07
Can you include the images? Thanks! :)

**Comment by Keevle** [comment] 2020-04-15 14:00
[testderbug.zip](https://github.com/4ian/GDevelop/files/4481632/testderbug.zip) @4ian

**Comment by Keevle** [comment] 2020-04-23 16:44
After taking a further look at things,this might be the Tween behavior itself rather than just "Opacity tween" 
(Basic video with tweens enabled)
`https://streamable.com/wstcl5`
In this video it showes me firing into a corner constantly and you'll see the fps gradually decline after a little bit and even when there are 0 bullets/explosions on the screen the fps never recovers
compared to 
`https://streamable.com/ctv07u` 
without any tweens it can handle hundreds of objs at a solid fps
The only diffrence between these 2 videos is removing the tween at
![](https://i.imgur.com/VedxCk0.png)

**Comment by Wend1go** [comment] 2020-04-24 08:02
I had a look at your project file. Looks like you are checking if a tween called "bounce" has finished playing while the real name of the tween is "opacity". Since the condition will never be true, you are never deleting the invisible (opacity=0) explosion objects. This might be the reason for the slowdown:
![image](https://user-images.githubusercontent.com/7413059/80189151-83fab380-8612-11ea-86ec-bb009bbe711f.png)

**Comment by Wend1go** [comment] 2020-05-30 07:29
So is this still an issue or can we close this?

**Comment by 4ian** [comment] 2020-05-30 08:50
I'm closing this, please re-open if there is a clear issue :)

**Closed by 4ian** 2020-05-30 08:50 UTC
