### ISSUE TITLE
wont let me add a behavior to sprite

### ISSUE THREAD

**Issue by BigMack1234** [4ian/GDevelop#6088] opened 2023-12-15 13:31 UTC
### Describe what you were doing when the crash happened

trying to add a behaviore to a sprite

### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0, Platform: MacIntel

### Additional error context

uniqueErrorId: e71f88f7-8a32-48c2-ad0a-a7cf488c8443

fu@https://editor.gdevelop.io/static/js/main.075728f4.js:2:509002
enqueueForceUpdate@https://editor.gdevelop.io/static/js/main.075728f4.js:2:467783
41113/_.prototype.forceUpdate@https://editor.gdevelop.io/static/js/main.075728f4.js:2:539720
value@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:1289727
23262/yr/g</<.children<@https://editor.gdevelop.io/static/js/3611.839c7dea.chunk.js:1:409517
23262/zg/<@https://editor.gdevelop.io/static/js/3611.839c7dea.chunk.js:1:838359
fs@https://editor.gdevelop.io/static/js/main.075728f4.js:2:501821
ds@https://editor.gdevelop.io/static/js/main...

### Additional component context

    in zg
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in yr
    in div
    in s
    in f
    in Gg
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in qg
    in div
    in s
    in Cy
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
 ...

**Comment by ClementPasteau** [comment] 2024-01-03 10:03
This is a duplicate of #5933 
Some automatic translation extensions cause infinite loops in rendering of the behaviors list

**Closed by ClementPasteau** 2024-01-03 10:03 UTC
