### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by RMDB-GD** [4ian/GDevelop#6141] opened 2024-01-03 20:18 UTC
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: ff5ee135-6ae2-41f2-af4b-cd840a95d1f7

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at fu (file:///C:/Program%20Files/GDevelop2/resources/app.asar/www/static/js/main.f3ca4708.js:2:509002)
    at Object.enqueueForceUpdate (file:///C:/Program%20Files/GDevelop2/resources/app.asar/www/static/js/main.f3ca4708.js:2:467783)
    at n._.forceUpdate (file:///C:/Program%20Files/GDevelop2/resources/app.asar/www/static/js/main.f3ca4708.js:2:539720)
    at Object.onChange (file:///...

### Additional component context

    in ForwardRef
    in div
    in a
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in xh
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in vh
    in Rx
    in div
    in n
    in l
    in n
    in ForwardRef(Em)
    in div
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
  ...

**Comment by ClementPasteau** [comment] 2024-01-04 08:37
Duplicate of #5933 

Are you using some kind of automatic translation tool?

**Closed by ClementPasteau** 2024-01-04 08:37 UTC

**Comment by RMDB-GD** [comment] 2024-01-08 09:50
Hi clemente,
sorry for my late answer, but no . i'm not using auto translate tool, but i
noticed that sometimes gd change language automatically so i need to revert
to english.
So maybe yes it could be the issue

Il giorno gio 4 gen 2024 alle ore 09:37 Clément Pasteau <
***@***.***> ha scritto:
