### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Lucky131114** [4ian/GDevelop#6064] opened 2023-12-12 09:41 UTC
### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0, Platform: Win32

### Additional error context

uniqueErrorId: 489c152a-4f37-4283-b940-ed1be4ca3f2e

e@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:3034531
value@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380587
value@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380008
ds@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:501156
Fu@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:518944
22/t.unstable_runWithPriority@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:547685
Ko@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:462613
Pu@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:515603
gu@https://editor.gde...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in pM
    in div
    in n
    in Ga
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2023-12-12 15:08
Duplicate of #5956

**Closed by ClementPasteau** 2023-12-12 15:08 UTC
