### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by irinakova** [4ian/GDevelop#6093] opened 2023-12-15 18:18 UTC
### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: cd1e8e26-9ffb-4df7-8b56-8c9784148522

Error: Error creating WebGL context.
    at new e (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:3032986)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3611.38859ce7.chunk.js:1:1396081)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3611.38859ce7.chunk.js:1:1395502)
    at ds (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:501984)
    at Fu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:51...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aw
    in jw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in UM
    in div
    in n
    in Ji
    in div
    in VA
    in Unknown
    in Qe
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in me
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-03 10:04
Duplicate of #5956

**Closed by ClementPasteau** 2024-01-03 10:04 UTC
