### ISSUE TITLE
Lights are not rendered in browser if radius is over 255

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1990] opened 2020-09-17 21:15 UTC
## Describe the bug
If you set the radius of the lights higher than 255, it is no longer rendered in Safari and Chrome on iOS 13.7 and maybe also Android 9 (to be confirmed)
Here is the forum discussion about it:
https://forum.gdevelop-app.com/t/lights-does-not-render-on-ios/27492

## To Reproduce
1. Create a light object
2. Set radius to 256 or higher
3. Add light object to scene
4. run preview over wifi, open the project in your web browser on your mobile.

* Please include a link to a game if possible!
[LightTest.zip](https://github.com/4ian/GDevelop/files/5241845/LightTest.zip)

## Other details
* Include any OS/browser version/smartphone that you're using
iOS 13.7, latest version of Safari and Chrome web browser
* Which version of GDevelop are you using? The desktop app or the web-app?
desktop v5 beta 100

Thanks.

**Comment by 4ian** [comment] 2020-09-18 08:11
Chrome and Safari are the same browser on iOS, because Apple does not allow 3rd party browsers (Chrome is just a shell around Safari, which is the only allowed way to make a browser) ;) 
This being said, there seems to be some glitches when rendering lights on iOS/Android indeed. Might be due to the shader being used - @HarsimranVirk would you have a device to test this?

**Comment by HarsimranVirk** [comment] 2020-09-18 08:15
@4ian I could test on Android, but I'm not sure about the problem though. What do you suggest, how should I figure out the exact issue (whether its shader related or not)?

**Comment by 4ian** [comment] 2020-09-18 08:19
Let's confirm if you can observe a glitch, and if it's related to the radius of the object: is the light showing properly for radius 50? 250? 600? 1000? 
Then we can start finding some hypothesis, maybe there are some PIXI.Mesh limitations on mobile phones that may have more limited GPUs?

**Comment by 4ian** [comment] 2020-09-18 08:26
Maybe try also with/with a few/with a lot of obstacles. Could be some uniforms not being passed properly? Or the fading effect not shown because we use some GLSL syntax not supported on some GPUs.

**Comment by HarsimranVirk** [comment] 2020-09-18 08:54
About the hypothesis of 255 radius, I believe it's really device/chrome ver/webgl ver specific. I could easily render 1000+ radius on my device (again it was pretty pointless, because my screen was completely red, red being the color of light).

![WhatsApp Image 2020-09-18 at 2 16 12 PM](https://user-images.githubusercontent.com/39851078/93577608-de2d5400-f9b9-11ea-8de4-01fd86ab997e.jpeg)
This is a 500 radius light, working fine.

> Let's confirm if you can observe a glitch

About the glitch, I could see one
![WhatsApp Image 2020-09-18 at 2 16 17 PM](https://user-images.githubusercontent.com/39851078/93577857-3401fc00-f9ba-11ea-8c87-ba6284fa582d.jpeg)

The light is cut off abruptly, this should be a shader issue I guess. I'll have to try some solutions to see if it can be fixed or not. 😬 

My guess is that the fading function isn't able to get rgb(0, 0, 0) before it hits the boundary of the light object, let's try out different functions to see if they work or not.

**Comment by 4ian** [comment] 2020-09-20 11:07
>  The guess was based on the fact that I can see light not fading out after a certain distance, the color becomes fairly constant.

Yeah that's strange. Surely goes in the direction of the shader function not working properly.

**Comment by Bouh** [comment] 2021-08-28 15:30
I closing this , it seem fixed since a while, the test project works fine to me now.

**Comment by ddabrahim** [comment] 2021-09-04 10:25
@Bouh I was uncertain about Android hence I wrote "to be confirmed". I believe someone reported similar rendering problems on Android on the forums but I was not sure. So it is not a problem on Android then.

But I still have this problem on iOS 14.7.1 using Safari, though it may be a limitation of Safari/WebKit on iOS....

Thanks.

**Comment by Bouh** [comment] 2021-09-04 10:45
It would be necessary that somebody with an iphone debug the runtime. I don't know who in the team have one.
@ClementPasteau Do you have an iPhone?

**Comment by ddabrahim** [comment] 2021-09-04 11:13
In the iPhone console I get a bunch of 404 errors, nothing related really:

<img width="1459" alt="Screenshot 2021-09-04 at 12 02 58" src="https://user-images.githubusercontent.com/24738433/132092399-62fc1d84-e8d2-418c-9f51-c981e6851548.png">

Is there anything else I can try maybe?
All this 404 errors are still weird though...

**Comment by ClementPasteau** [comment] 2021-09-05 20:30
The 404 errors are weird indeed. Maybe Safari always tries to download a ".map" version of any ".js" resource. 
Anyway, It shouldn't be an issue if you can see the same files (without the .map) being correctly downloaded.

I've double checked on Safari desktop and there are indeed no problems so definitely a mobile-specific issue.
I do have a spare iPhone I can use to try to reproduce the problem, I'll take a look tomorrow! 

I'm reopening the issue for the moment @Bouh  :)

**Comment by 4ian** [comment] 2021-09-05 20:44
Sourcemaps of the files of the game engines are not exported in a game export (just for preview) - but unfortunately the files are still referring to these and so generate a warning in the console. Harmless though!

Seems definitely mobile/GPU related. Thanks for checking!

**Comment by ClementPasteau** [comment] 2021-09-06 15:52
I've done a bit of digging.

I've managed to reproduce the problem on an iPhone 6.
After a certain radius (for me it looked like ~280) the glowing starts growing faster and weird things happen:

<img src="https://user-images.githubusercontent.com/4895034/132240395-3c798cd1-0845-48b2-addc-d06a6fdb36bf.png" data-canonical-src="https://user-images.githubusercontent.com/4895034/132240395-3c798cd1-0845-48b2-addc-d06a6fdb36bf.png" width="200" height="400" />

I've looked at different issues PixiJS had in the past regarding iOS compatibility and haven't found something specific about shaders. But I found that one issue was fixed by replacing the precision of a float from `mediump` to `highp`. (https://github.com/pixijs/pixijs/pull/1975)

When I replaced the 3 definitions of the float attribute in the pixi-renderer, for the different shaders definitions, the issue seems fixed (https://github.com/4ian/GDevelop/blob/master/Extensions/Lighting/lightruntimeobject-pixi-renderer.ts#L512-L548) 

<img src="https://user-images.githubusercontent.com/4895034/132240708-f78e0c38-f93d-4dc2-a1a8-7faa7b71bcd1.png" data-canonical-src="https://user-images.githubusercontent.com/4895034/132240708-f78e0c38-f93d-4dc2-a1a8-7faa7b71bcd1.png" width="200" height="400" />

(I've compared with my Android and the result is similar)

------------

I'm wondering if iOS has some trouble with non-highp float definitions in general (the `mediump` seems to be used in other extensions & effects: `light-night-pixi-filter` `night-pixi-filter` `bevel` `dot` `pixelate`.....)
Have we noticed similar weird behaviors on iOS for those effects/extensions?

Finally, I can't seem to find any information on a performance impact by setting this prop to highp.
But the code shows that if a device cannot support it, then it falls back to medium (https://api.pixijs.io/@pixi/core/src/shader/utils/setPrecision.ts.html)

**Comment by 4ian** [comment] 2021-09-06 16:17
Good catch!
One article mentioning float precision and webgl: https://webglfundamentals.org/webgl/lessons/webgl-precision-issues.html

*Maybe* highp is not required for the vertex shader (it's really the color shading that was causing problem because of this loss of precision), but for safety sake we can have it here too. I think it's unlikely mobiles modern enough to run GDevelop games don't have highp support.

> But the code shows that if a device cannot support it, then it falls back to medium

This fallbacks looks good, though I don't know if it's used by default (are we using setPrecision?)

**Comment by ClementPasteau** [comment] 2021-09-06 16:24
You're right, the shader is defined as a whole using a string. So I assume the function isn't used.

I'll create a PR with the fix and we can do more testing with light-heavy games.

**Closed** 2021-09-06 16:43 UTC
Labels: 🐛 bug, os: ios
