### ISSUE TITLE
Error preview followed by normal preview

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1149] opened 2019-07-09 23:14 UTC
I wonder if I'm the only one to suffer from this?
Sometimes, when I click on the preview icon, a first preview opens, with missing textures/sprites, and a couple of seconds later, a proper preview opens on top of it.
Let me know if I can somehow investigate it the next time it occurs.

![image](https://user-images.githubusercontent.com/25978830/60928813-0c3fe000-a2af-11e9-9be5-558808c83600.png)

GD5b75 Win10

**Comment by KinkGD** [comment] 2019-07-10 07:05
Hello,

I don't have this issue. Multiples preview windows can happen, but only if i click a second time while the first preview window is opening.. I'm on win10 too.

**Comment by PascalLadalle** [comment] 2019-07-10 13:11
OK... I'm 99% sure I was not double-clicking the button, but I did a few tests after your comment, and it turns out that if I hit the preview button a second time **before the preview is fully loaded** (when the editor UI is grayed), the bug occurs (every time).

**Comment by 4ian** [comment] 2019-07-10 13:33
Ok this must be because you launch the first preview, GDevelop clears the preview folder, generates the game and open the preview window, then when you launch the second preview, GDevelop clears the preview folder (and start to generates the game) *before* the first preview window has finished to load (so some assets will be missing as the directory was just cleared).

This being said, not sure what the good solution to this can be.

**Comment by Wend1go** [comment] 2019-07-10 16:38
Could we keep track of the Preview Window process and grayout/disable the run icon until it gets closed?

**Comment by Bouh** [comment] 2019-07-11 09:22
In any case we need keep the possibility to open multiple preview. It's useful for debugging and compare.

**Comment by 4ian** [comment] 2019-07-11 16:51
When the game is launched, the IDE has no way to know if the loading is finished or not. We could add this, but seems like a lot of work for a edge case. Maybe a better solution would be simply to output in different temporary folders, and remove these folders only when the preview dialog is closed (which is something that is owned by the IDE). This would entirely remove the possibility for this bug to exist.

**Comment by Silver-Streak** [comment] 2021-07-25 15:52
I used to be able to reproduce this behavior.
However, I think this was inadvertantly solved once live preview happened, as I can no longer get this to occur.

I'm going to close this out, but @PascalLadalle if you're still having this occur, please feel free to reopen this issue.

**Closed by Silver-Streak** 2021-07-25 15:52 UTC
Labels: 😇A workaround exists, 😤Non optimal UI behavior

**Comment by PascalLadalle** [comment] 2021-07-25 18:01
This was fixed a long time ago indeed 👌

**Comment by 4ian** [comment] 2021-07-26 08:43
Thanks for the follow up 👍
