### ISSUE TITLE
Install a game overwrite the previous game already installed

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2252] opened 2021-01-30 19:25 UTC
## Describe the bug
Install a game made with GDevelop5 overwrite the previous game already installed.
[It seem appear only with the build service.](https://forum.gdevelop-app.com/t/game-override-another-game/30229/5?u=bouh)

## To Reproduce
1. Export a game for windows with the auto-installer.
2. Install the first game
3. Repeat the process with another game, with a different, game name, package name, version number, and author name.
4. See the second game is installed in the folder of the first game.

[Bug fixes for manual export.](https://forum.gdevelop-app.com/t/allow-install-directory-selection-for-desktop-builds/30230)

## Other details
* W10
* B103
Source [link 1](https://forum.gdevelop-app.com/t/game-override-another-game/30229) [link 2](https://forum.gdevelop-app.com/t/windows-auto-installer-game-builds-are-overwriting-each-other-on-install/27398/8)

**Comment by Silver-Streak** [comment] 2021-01-31 07:12
This has been happening on and off for some users since at least September last year. I have never been able to reproduce it for folks reporting it on the forums, likely because I build locally. This makes me think it is definitely specific to the build service.

The linked post for bug fixes is more of a feature request I had to help alleviate it (and would likely still be a good option for the build service), but it doesn't necessarily tell us the *source* of the issue on the build service.

**Comment by arthuro555** [comment] 2021-02-01 07:35
My guess is that the nsis ID is somehow cached by the build service, so when installing a GDevelop game, the installer sees the other installed GDevelop game as the same app and treats the installation as an update. As the installation path could have been defined by the user in the last installer, it just uses that same path to make sure the user preferences are respected.

**Comment by 4ian** [comment] 2021-02-01 09:21
Each build is made on a blank virtual machine launched specifically for the build so it's not entirely a caching issue - but the issue is surely related to NSIS using the same identifier for two apps.

**Comment by arthuro555** [comment] 2021-02-01 09:28
I'd propose to make the package.json have the field [`nsis.guid`](https://www.electron.build/configuration/nsis#NsisOptions-guid) set to the Project UID, that way it should remain the same across updates and stay unique to the game.

**Comment by 4ian** [comment] 2021-02-01 09:52
Good finding, though the docs indicates that `You can explicitly set guid using option nsis.guid, but it is not recommended — consider using appId.`

So we could go ahead with the `appId` field (which is by the way what we're using for GDevelop itself), and set it to the package name (used for Android/iOS already). It's pretty obvious that the package name should be unique, because it's what is used for app stores :) 

Also note that the documentation answer to the question:

> name-based UUID v5 will be generated from your appId or name. It means that you should not change appId once your application in use (or name if appId was not set).

This means that because appId is not set for now, the application name is used. If someone uses the same name as another app ("Platformer"), the new app will replace the old one.

Should be not too hard to add appId then :) And update the UI to also say that it's used for Android, iOS, but also for installers on Windows.

**Comment by arthuro555** [comment] 2021-02-01 10:04
That's weird... I've experienced this issue myself but the games definitely didn't had the same name. I extracted data.js from the app.asar from both to verify: one had `Project` as project name and the other `Miko's Adventures`.

**Comment by 4ian** [comment] 2021-02-01 11:09
Definitely weird then! Good reason to go the appId way as a first solution in any case.

**Comment by arthuro555** [comment] 2021-02-22 09:04
With #2310 this issue should be fixed. Should we close it?

**Comment by 4ian** [comment] 2021-02-22 09:26
Let's close it for now to avoid forgetting about it :)

**Closed by 4ian** 2021-02-22 09:26 UTC
Labels: 👌good first issue
