### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#630] opened 2018-09-10 19:40 UTC
I was editing a scene and clicked on the background object and in the property window selected "Lock position/angle in the editor" and it crashed.

I saved and tried same again and worked fine.

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'getObjectName' of undefined
    at Object.getValue (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.580c1bf5.chunk.js:1:1968429)
    at t.value (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.580c1bf5.chunk.js:1:156133)
    at t.i._renderEditField (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.580c1bf5.chunk.js:1:154589)
    at file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.580c1bf5.chunk.js:1:156482
    at Array.map (<anonymous>)
    at t.value (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.580c1bf5.chunk.js:1:156397)
    at h (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:103488)
    at beginWork (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:106935)
    at o (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:123209)
    at a (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:123482)
    at b (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:126433)
    at m (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:125973)
    at flushInteractiveUpdates (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:129666)
    at X (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:79134)
    at qe (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:87147)
    at interactiveUpdates (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:129580)
    at He (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:86891)
    at HTMLDocument.r (file:///C:/Users/charl/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.d89edd59.js:1:605733)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in div
    in t
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in _
    in div
    in div
    in t
    in div
    in t
    in g
    in t
    in t
    in div
    in t
    in t
    in t
    in y
    in div
    in div
    in y
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
    in t
    in t
```

**Comment by 4ian** [comment] 2018-09-10 20:26
It's strange that this can even happen 🤔
I've added a protection against this for next version but it's possible that there is a root cause hidden somewhere.
Do you remember if you've done something in particular before the crash, apart from clicking "Lock position/angle in the editor"? 

Closing this as there is an additional protection but let me know if you manage to reproduce it, I would be highly interested

**Closed by 4ian** 2018-09-10 20:26 UTC

**Comment by zatsme** [comment] 2018-09-10 21:09
I was copy pasting multiple object clones to the scene and wanted to make sure the background didn't move.
