### ISSUE TITLE
Prevent users from losing work when pop-up windows close

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2482] opened 2021-03-29 15:45 UTC
## Description

Many people (including myself) have reported frustration when they have entered data into a pop-up window (such as editing an event) only to have that work discarded because the user accidentally clicked outside the pop-up window when trying to click "OK".

Forum discussion: https://forum.gdevelop-app.com/t/improving-gdevelop-usability/8245/183

## Solution suggested

Option 1:  (Preferred)
- When someone clicks outside a pop-up window, change the default behavior from "Cancel" to "OK".  

This will prevent users from losing work.  If a user really wants to cancel the changes, they can always use the "Cancel" button or hit "Escape" on the keyboard.  

From a probability point of view, GDevelop users save their changes way more frequently when compared to canceling their changes.  That is why this makes a good default behavior.  

From an impact point of view, a user who loses the work they have entered has no options to get that work back.  The same is not true for users who want to cancel a change and are surprised that clicking outside the pop-up saved the change.  In this case, the user can simply use the Undo function to revert the unintended change.

## Alternatives considered 

Option 2: (Not preferred)
- Don't take any action when clicking outside a pop-up window. Force users to click "OK" or "Cancel" (or use the Escape key).

Option 3: (Not preferred)
- If a user has made changes and clicks outside a pop-up window, bring up a dialogue that asks if they want to save the changes or not.

**Comment by Silver-Streak** [comment] 2021-03-29 15:56
I would personally prefer option 2 or 3, specifically because there is no standard window size for any of the dialogs in GD5. Since accidental double-clicks are a thing, you could double-click OK on one window and end up cancelling out the window below it, such as with Piskel vs Animation window.

Overall, any of these options are probably an improvement over current state.

**Comment by 4ian** [comment] 2021-03-29 15:58
Thanks for writing this and the alternatives :)

>  The same is not true for users who want to cancel a change and are surprised that clicking outside the pop-up saved the change. In this case, the user can simply use the Undo function to revert the unintended change.

Unfortunately no, there is sadly no "project wide" undo command that would undo any change that you've done.
So this means that in this case, someone closing the dialog by clicking outside will have its changes applied and can't easily undo.
This being said I agree it might be better go this road.

Though I wonder if option 2 is not better. This is more akin to what a modal dialog would do in another software (if you click outside, it just don't close). You can keep using Esc to quickly cancel if you opened something by mistake (something that can happen fairly often). And you're protected against misclicks (not misuage of Esc, but that's less often!).

What do you think?

**Comment by arthuro555** [comment] 2021-03-29 16:42
What about all options? We can just provide a preference "action on click outside modal", that can be either "Cancel changes", "Save changes", "Ask every time" or "Do nothing". That way, it can satisfy everyone, as everyone seems to have a different opinion on the subject, probably due to different usages and workflow in GDevelop.

I think either "Do nothing", "Ask every time" or asking to select their preference when it happens the first time are safer defaults for such a preference, as people may be angry if they don't like the default, those allow to have some kind of choice to not be angered by the outcome.

**Comment by Bouh** [comment] 2021-03-29 16:54
This subject comes up all the time and tends to choices bad pratice of blocking dialogs in most cases and it bugs me....

As said @arthuro555 the better solution is to make an options for it.
No body is ok with these suggestions. so the global solution is the preferences!

I am against the dialog box, the click back drop are made precisely to have a fluid, fast and not blocking environment.
So I don't like options 2 and 3.

The option 1 can be ok for me, the argument "users save more than they cancel" convinced me in this use case for this panel only.

My prefered choice is the actual behavior, because i know use my mouse.
**To please everyone I really think it is necessary to have a preference for this.
It's the best option.**

**Comment by 4ian** [comment] 2021-03-29 17:02
Alright, let's go for a preference that will be:
- Do nothing 
- Close and apply changes
- Close and cancel changes (if applicable)

I would not go for "Ask me every time" if possible to avoid adding extra confirmation dialogs (in this case, you might as well just keep "Do nothing" :)).
I think ESC should still be always "Close and cancel changes (if applicable)".

**Comment by Bouh** [comment] 2021-03-29 17:09
Ok i'am on it rn

**Comment by 4ian** [comment] 2021-03-29 17:27
We might need a new prop and refactor `<Dialog` which would be called `onApply`. So that when the Material-UI Dialog `onClose` is called, we check the `reason` (second argument to onClose, see material-ui Dialog documentation):
- if it's `escapeKeyDown` => just close it by "cancelling" by calling `onRequestClose`, as now (no change in behavior).
- if it's `backdropBlick` => according to the preference, either cancel (`onRequestClose`), apply (`onApply`) or do nothing.

If `onApply` is not specified, then we call `onRequestClose`. For most dialog, we should then add a `onApply` prop that will be called to close and apply the changes (i.e: what the "OK" button is doing :)).

**Comment by Silver-Streak** [comment] 2021-03-29 17:50
Worth mentioning that Tristan opened a bounty on this: https://www.bountysource.com/issues/97505566-prevent-users-from-losing-work-when-pop-up-windows-close

I've added what I could to it today, as well.

**Comment by Bouh** [comment] 2021-03-29 18:11
Press escape cancel already `<Dialog` .
There is already a props `cannotBeDismissed` on `<Dialog` we can use it, naively pass the option from preferences to this props?

**Comment by 4ian** [comment] 2021-03-29 18:20
> Press escape cancel already <Dialog .

Yes, and I believe we can keep this behavior.

> There is already a props cannotBeDismissed on <Dialog we can use it, naively pass the option from preferences to this props?

This prop `cannotBeDismissed` is useless for now. It was designed at the time to say "this dialog is important and should not be closed by mistake". But we'll probably remove it. All dialogs should behave the same.

> naively pass the option from preferences to this props?

No, because this would imply that every component using `<Dialog` will need to also read the preferences => a nightmare.
Instead, just read the preferences from the React context in `Dialog/index.js` (in other words => it's the responsibility of the dialog to know what to do)

**Closed** 2021-04-10 18:36 UTC
Labels: bounty 💰, ✨ enhancement
