### ISSUE TITLE
Idea: support for zdog pseudo 3d rendering

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1248] opened 2019-10-04 21:17 UTC
This is kind of a crazy idea, that would really work if this library had some kind of an editor, but the style you can get through it is very very attractive for mobile type games. Check this out
https://zzz.dog/

The way I see it, to use this, we would need a zzdog pseudo 3d game object extension. You could even give it the ability to rotate around - creating a 3d effect. The library can even nest objects and animate them.

If I give it a shot to create some sort of an editor that lets you create an animated pseudo 3d object - would this be something that you would love having in gdevelop? It will be sort of an evolution of piskel - but with vector graphics and on top of that - pseudo 3d!

It's just really exciting to think what can be made in terms of an editor, just by using this library. But it would be useless without having a runtime that uses the same library for rendering the game objects.

Anyways, thought it could grab other people's interest and was wondering what you think of it.

If I do ever give this a shot, it will probably take a whileto make, but it will be hella fun to work on :p 

BUt what would such an editor export? A json file containing all the objects and their animations? And then a runtime would generate js out of it?
Or should it produce a raw js file instead?

**Comment by 4ian** [comment] 2019-10-04 22:09
Well this looks interesting but before investing all your time on it, be sure to consider:
* Is this suitable for a lot of games or just a few? The rendering is very opinionated around "round things". Would be a bummer for lots of games, especially if you want to do pseudo pixel art?
* How performant is the rendering for a game? Are there benchmarks about displaying a few hundreds of these?
* Can you reuse this in Pixi/WebGL? 
* How successful is the library? Seems quite starred on GitHub! What about the usage in the wild?

Basically, I find it to be very interesting, pleasant to see and probably to use. Not doubt it can be used to make beautiful websites and animations.
But for games, you're more in an unknown territory and I'm not sure the library goals are aligned with the one from a game engine. Also remember that for us maintainers of GDevelop, a new library = a new complex thing to handle, and complexity is multiplied everytime we had a new library, because this has the potential to work - or not - with all the other features (collisions, rendering in the scene, rendering in the editor). 
You can of course give it a go, but I can't promise to integrate this into GDevelop, and so pay the cost of maintaining it on the long term for potentially years, if it's not something that is demanded and used by a lot of games.

I'm closing the issue as it's not a bug, but discussion can continue as usual.

**Closed by 4ian** 2019-10-04 22:09 UTC
