### ISSUE TITLE
Author of game aren't showing

### ISSUE THREAD

**Issue by marshallovski** [4ian/GDevelop#3401] opened 2021-12-23 18:00 UTC
## Describe the bug

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Just open GDevelop
2. Click on any game

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Windows 10
* version of GDevelop: 5.0.124

![изображение](https://user-images.githubusercontent.com/68496774/147276777-0a0de3f6-d1a1-48cd-b63f-0befb448e464.png)

**Comment by ClementPasteau** [comment] 2021-12-28 08:56
Thanks for reporting.
I can confirm the problem is only happening on the Windows Desktop version. (tested MacOS & web editor, no problem)

Weird, probably an issue with lingui, but strange it happens only on 1 OS.

**Comment by ClementPasteau** [comment] 2022-02-28 13:26
Couldn't reproduce it on my windows, I assume the translations are correctly handled now.
Closing for now, but if it's still a problem, feel free to reopen.

**Closed by ClementPasteau** 2022-02-28 13:26 UTC
Labels: 🐛 bug
