### ISSUE TITLE
Multiplayer games in Preview not work - Web Version only

### ISSUE THREAD

**Issue by Nader-B10** [4ian/GDevelop#6753] opened 2024-07-04 11:08 UTC
### Describe what you were doing when the crash happened

I have a project from the previous version in which I was testing the multiplayer game feature... I tested it in the preview and the multiplayer feature was working in it almost stably... but now after the latest update it is no longer stable and does not work. I faced a lot of strange problems and I could not make it work. Even once... watch the attached videos. When I tried to try it more than once... the game fails to start, so the host enters the game and the rest of the players fail to enter (this is a test on the web version and the preview... I have not yet tried the Windows version or an exported game)

https://github.com/4ian/GDevelop/assets/113104542/782663dd-0d48-4f68-a676-578f5cf98a8f

https://github.com/4ian/GDevelop/assets/113104542/f24aec50-5ecf-41b5-9e7f-94e426455a0b

https://github.com/4ian/GDevelop/assets/113104542/78e91a41-275a-4578-81f5-0f0fe5cc4310

### GDevelop version

5.4.205

### Platform info

Web version

**Comment by Nader-B10** [comment] 2024-07-04 11:41
I have now tested a preview of the project on the previous version (5.4.204), but the Windows version, not the web version, and the multiplayer project works well without problems, which proves that there is a problem with the latest update. Even the bandwidth is good at only 17. The characters move smoothly and the connection synchronizes smoothly without problems.. Unlike the latest update 5.4.205
![Screenshot 2024-07-04 143121](https://github.com/4ian/GDevelop/assets/113104542/f1d07725-d31b-488b-b934-b9463a0e007e)

**Comment by Nader-B10** [comment] 2024-07-04 12:21
I did one last test of the latest update 5.4.205...on the Windows version and the multiplayer feature worked correctly without problems unlike the web version...in short, the problem is with the latest update on the web version only (I did not test the mobile version or any exported game).

https://github.com/4ian/GDevelop/assets/113104542/fca3d722-661d-488a-99aa-7853b2804f40

**Comment by deftrashu** [comment] 2024-07-05 22:54
same problem but on android. 
Android online lobby stuck logging screen like this screen:
![Screenshot_2024 07 06_00 53 30 206](https://github.com/4ian/GDevelop/assets/126200725/4d77af3e-65c0-427f-875c-b6bd350c2fee)

**Comment by ClementPasteau** [comment] 2024-07-09 08:08
Hi @Nader-B10 thanks for reporting and for the videos, it helps a lot.

It looks like what's causing the issue is not the version of GDevelop but the time of the lobby countdown.
In the new version, we've reduced the countdown to 2 seconds to speed up preview lobbies, but on some connections or computers, it's not enough for everyone to be connected in time.

We'll rollback to 5 seconds, while we think of a better way to handle it.
You should see the change in the next hour.

@deftrashu please open a separate issue.

**Comment by ClementPasteau** [comment] 2024-07-09 11:40
I'm closing the issue considering it should be fixed, but please let me know and re-open it if you still have issues with a 5 seconds countdown.

**Closed by ClementPasteau** 2024-07-09 11:40 UTC
