### ISSUE TITLE
Cannot Preview any game builds I have

### ISSUE THREAD

**Issue by SnakeXS** [4ian/GDevelop#5645] opened 2023-09-07 17:37 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

During the previous update, I did not run into this issue with the editor as everything was still working properly on my end. After updating to the newest version of Gdevelop, I could not preview any of the builds that I have had. This included new ones as well.

I tested this by attempting to make a new build and just trying to open it to see if it would work, and it did not open at all. It is just a black screen.

Something that I can note as well is that all new projects I start up have this issue now as well with the "DisplayAuthenticationBanner action from PlayerAuthentication extension is missing."

![image](https://github.com/4ian/GDevelop/assets/98198950/423bcc0b-33a1-4856-b025-546011dbe6e0)

### Steps to reproduce

1. Go to File > Create > New Empty Project
2. Create the Empty project
3. Press Preview

Doing this might or might not activate the error of a black screen.

![image](https://github.com/4ian/GDevelop/assets/98198950/01cc7835-793f-4de7-ad81-65ff32f38cd8)

### GDevelop platform

Desktop

### GDevelop version

5.2.172

### Platform info

<details>

*Desktop Version, Windows 10
</details>

### Additional context

[Digital Solver.zip](https://github.com/4ian/GDevelop/files/12559046/Digital.Solver.zip)

**Comment by ClementPasteau** [comment] 2023-09-08 07:51
Hi @SnakeXS thanks for reporting your problem.
You haven't told us which platform you're using. Are you on desktop? Windows?

We cannot reproduce this issue on our end.
Could you save and share the project in a zip in this issue?

Thanks.

**Comment by SnakeXS** [comment] 2023-09-08 11:42
> Hi @SnakeXS thanks for reporting your problem. You haven't told us which platform you're using. Are you on desktop? Windows?
> 
> We cannot reproduce this issue on our end. Could you save and share the project in a zip in this issue?
> 
> Thanks.

This was done on the Desktop version of Windows 10. I added the build file as well.

**Comment by ClementPasteau** [comment] 2023-09-08 12:14
Thanks for sharing your project.
I really can't reproduce your problem. This seems like GDevelop is missing some crucial engine parts preventing the game or the events to run.

Could you try:
- Quitting and relaunching GDevelop
- uninstalling & Reinstalling GDevelop from the website: https://gdevelop.io/fr-fr/download

Let us know if any fixes it

**Comment by SnakeXS** [comment] 2023-09-08 12:32
> Thanks for sharing your project. I really can't reproduce your problem. This seems like GDevelop is missing some crucial engine parts preventing the game or the events to run.
> 
> Could you try:
> 
> * Quitting and relaunching GDevelop
> * uninstalling & Reinstalling GDevelop from the website: https://gdevelop.io/download
> 
> Let us know if any fixes it

The first option did not work; however a complete uninstall and reinstall had worked since after doing so, I am able to use the previewer again for all my current builds.

**Comment by ClementPasteau** [comment] 2023-09-08 12:48
Good to know! Looks like the update went wrong somewhere and didn't download everything correctly.
I'll close this issue now 👍

**Closed by ClementPasteau** 2023-09-08 12:48 UTC
