### ISSUE TITLE
Variable from properties editor are not always saved

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1345] opened 2019-12-30 15:55 UTC
## Describe the bug
When i type new instance variable in propertie panel, the input are not saved when i select another instance.
It's only save if i click on background.

## To Reproduce
1 Create new variable instance
2 rename it
3 click on another instance
4 go back to previous instance
5 name of instance variable is reset to **Variable**

![drag_n_drop_object](https://user-images.githubusercontent.com/1670670/71589419-1982ac80-2b25-11ea-8783-eea01449908d.gif)

## Other details
* B83

**Comment by 4ian** [comment] 2019-12-31 10:01
Right this is an issue indeed, this comes from the fact that we're waiting for the text field `onBlur` to be called to persist the changes. 

The difficulty here is to detect that the component is unmounted and properly persist the changes.
We could do something like: a SemiControlledTextField, if focused, calls its `onBlur` prop when it's unmounted. So that we would be sure that in this case, the `onBlur` is always called, so the changes are always persisted.

BUT the issue is that this can have a unwanted side effects. In particular, let's imagine that a SemiControlledTextField is modifying a field of a libGD.js object. Let's say that somewhere, I delete the libGD.js object. To be sure that the user is not modifying the object I just deleted, I also update some React state to hide the component. This looks like this:

```
whenSomethingHappen = () => {
  myGDobject.delete();
  this.setState({ showTextField: false });
}

render() {
  return this.state.showTextField ? <SemiControlledTextField value={myGDobject.getText()} onChange={(value) => myGDobject.setText(value)}>
}
```

If I focus the text field, then for some reason `whenSomethingHappen` is called, the `myGDobject` is deleted (so far so good), then the state `showTextField` is changed to false, the component is re-rendered (so far so good), the SemiControlledTextField is unmounted and then BOOM, because the text field was focused, `onChange` is called, and `onChange` calls `setText` on an object that was deleted.
This crashes libGD.js and GDevelop entirely :/ 

I'm not entirely sure how to deal with this. Ideally, `onBlur` would be called BEFORE the component is unmounted and replaced by something else.
This would mean that when we click on the scene editor, there is first the `blur` event and THEN the click event - but I think this is dependent on the browser.

A potential solution would be to apply the changes to the selection on the next tick (using a setTimeout). So that we would let the browser the time to see that there was a blur event on the text field and THEN (on the next tick) update the selection (which will update the property panel, unmounting the old components).

**Comment by AlexandreSi** [comment] 2022-05-18 15:40
Closing this as #3847 brings a work-around to this bug: the new variable is persisted at creation time, so this bug is not relevant anymore.

**Closed by AlexandreSi** 2022-05-18 15:40 UTC
Labels: 🙇‍♀️Careful thinking/design or refactoring needed, 😤Non optimal UI
