### ISSUE TITLE
3d Particle Emitter has a slowing down leak.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#6003] opened 2023-12-04 11:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When you create a lot of 3d particle emitters like for ammunition that have a limited life span.
After a while the game starts to slow down considerably the longer the particle emitters are created.
In the example I made a 3d particle emitter with 3 second lifetime and 100 particles per second is created every frame.
After a while the FPS count starts to drop and will be dropping further the more time the game goes on.
Even manually deleting the emitters before the lifetime is over will yield the same result.

Increase the amount of particles emitted in the events to see the problem on more powerful computers.
On my laptop this amount is starting at 60fps and going down to 40fps in half a minute or so.

### Steps to reproduce

Create 3d particle emitter with limited life time.
Spawn one emitter per frame
watch the game slowing down gradually over time.

Link to [gd.games](https://gd.games/instant-builds/627ba14c-81de-4ec9-ace5-c29ffee041aa) 

Example project
[3dParticleEmitterTest.zip](https://github.com/4ian/GDevelop/files/13545393/3dParticleEmitterTest.zip)

### GDevelop platform

Desktop

### GDevelop version

5.3.181

### Platform info

Windows 10/11

### Additional context

This is heavily impacting on 3d projects that want to make ammunition or star streaks etc effects on continuous manner using 3d emitter.

**Comment by AlexandreSi** [comment] 2023-12-04 13:48
Hi @VanCastar,
Thanks for the detailed issue!
I can't reproduce your issue on my Mac M1 (on both gd.games and on Desktop), it could be worth trying on another platform.

**Comment by ClementPasteau** [comment] 2023-12-04 17:40
Might be useful for debug, I can see a `RuntimeScene.getObjects: No instances called "Particle"! Adding it.` log being called in loop in the console after a while (not when the items are destroyed)

**Comment by VanCastar** [comment] 2023-12-05 14:50
> Might be useful for debug, I can see a `RuntimeScene.getObjects: No instances called "Particle"! Adding it.` log being called in loop in the console after a while (not when the items are destroyed)

The slowdown occurs even if I do the object deletion manually like when using a tween.

**Comment by D8H** [comment] 2024-01-26 10:37
Thank you for reporting this issue. It should be fixed with 3D particle emitter extension 1.1.3
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1143

Extensions issues can be reported in the extension repository:
- https://github.com/GDevelopApp/GDevelop-extensions/issues

**Closed by D8H** 2024-01-26 10:37 UTC
