### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#3592] opened 2022-02-03 07:09 UTC
![Screenshot 2022-02-03 000732](https://user-images.githubusercontent.com/75917656/152297069-7ed4f687-fcbc-472b-a72f-b871166ddf1d.png)

was fixing a crash in preview window when this message popped up then crashed

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[3076]:0xa4d3a
    at wasm-function[2728]:0x8a979
    at wasm-function[412]:0x259bb
    at Project.HasLayoutNamed.Project.HasLayoutNamed [as hasLayoutNamed] (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.126-d49d765ec05d0454b365031d793c1702647877d8:9:910411)
    at n.value (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:363205)
    at n.value (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:363339)
    at Eo (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:239002)
    at xo (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:238795)
    at Co (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:242656)
    at Ua (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266568)
    at Fa (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266952)
    at Eu (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273988)
    at wu (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273368)
    at yu (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:272389)
    at qa (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:271258)
    at Object.enqueueSetState (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:220650)
    at n.w.setState (file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:170934)
    at file:///C:/Users/dev-f/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:589984
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.126-d49d765ec05d0454b365031d793c1702647877d8
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.126 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment] 2022-02-03 08:13
That's a really bad bug. Do you have any mean to reproduce it?

**Comment by Bouh** [comment] 2022-09-30 13:57
Hi @Entr0py404 
Without more information and because it was on a very old version,  we close this bug report.
GDevelop has had corrective updates since the crash, please update GDevelop.
If you encounter a new one please open a new bug report. If you had a similar crash to this one you can reopen this one.

**Closed by Bouh** 2022-09-30 13:57 UTC
Labels: 💥crash
