### ISSUE TITLE
Missing zoom in shortcut indicator

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1592] opened 2020-03-27 12:05 UTC
## Describe the bug
The 'Zoom In' item is missing the shortcut indicator (Cmd/Ctrl +). It would be good if there was one like 'Zoom Out' for consistency.

## To Reproduce
1. Open a project
2. Click on change editor zoom (magnifying glass icon).
3. Observe the missing indicator for 'Zoom In'.

## Screenshot
![Screenshot 2020-03-27 at 5 01 57 PM](https://user-images.githubusercontent.com/42793024/77754327-21cd8380-7051-11ea-8ed7-3968b476aa8f.png)

## Other details
Mac OSX Mojave
Desktop App

**Comment by ner-aim** [comment] 2020-03-27 12:41
I have seen the same issue in a Windows 10 OS. Does the Command + or Command - work shortcut work for zoom?

**Comment by pranavmodx** [comment] 2020-03-27 14:06
@ner-aim The shortcuts for Editor Zoom do work fine in Mac. Just that the indicator is missing. 
Have you tried in Windows? Did you have any issues?

**Comment by ner-aim** [comment] 2020-03-27 14:14
It doesn't, neither for the web-app or the desktop app in Windows 10. Also, the browser zoom is overlapping in the web-app. Did you check for the web-app in the mac?

**Comment by 4ian** [comment] 2020-03-27 19:09
Seems like a duplicate of #1580? :) Let's try to continue the discussion in the other issue to keep everything in a single place :)

**Closed by 4ian** 2020-03-27 19:09 UTC
