### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by d3vi0uss** [4ian/GDevelop#6100] opened 2023-12-18 15:47 UTC
### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Safari/605.1.15, Platform: MacIntel

### Additional error context

uniqueErrorId: 73f61781-7b0b-499b-a8b4-e9e0a1bc04f5

i@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:2896196
ma@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:2896633
Ie@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:3033257
e@https://editor.gdevelop.io/static/js/6891.db715c35.chunk.js:2:3033841
value@https://editor.gdevelop.io/static/js/3611.839c7dea.chunk.js:1:1396101
value@https://editor.gdevelop.io/static/js/3611.839c7dea.chunk.js:1:1395530
ds@https://editor.gdevelop.io/static/js/main.075728f4.js:2:502001
Fu@https://editor.gdevelop.io/static/js/main.075728f4.js:2:519774
@https://editor.gdevelop.i...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aw
    in jw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in UM
    in div
    in n
    in Ji
    in div
    in VA
    in Unknown
    in Qe
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in me
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-03 10:14
Duplicate of #5987

Need to upgrade PixiJS to 7.3.2 for a fix for Apple devices

**Closed by ClementPasteau** 2024-01-03 10:14 UTC
