### ISSUE TITLE
Crash while using an editor (non WebGL/Canvas issue)

### ISSUE THREAD

**Issue by SkyTheProtoDragon** [4ian/GDevelop#2270] opened 2021-02-03 19:49 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at t.We._renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:326179)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327898)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327975)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327975)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327975)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327975)
    at t.f.Container.renderCanvas (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:327975)
    at t.render (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:307941)
    at n.e._renderScene (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.0ba97536.chunk.js:1:999745)
    at n.value (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.0ba97536.chunk.js:1:1007342)
    at fi (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:96718)
    at ko (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:112739)
    at Co (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:117709)
    at Ua (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:141621)
    at Fa (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:142005)
    at Tu (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:149041)
    at Eu (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:148421)
    at gu (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:147442)
    at Wa (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:146311)
    at Object.enqueueSetState (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:95703)
    at s.E.setState (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:45988)
    at file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.36e4fbfc.chunk.js:2:811146
    at i (file:///C:/Users/sergi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta104-5d2c861d6ac727967695491f6e514abfda51b2c4
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta104 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment] 2021-02-03 21:22
I think it related to
https://github.com/4ian/GDevelop/issues/2089#issuecomment-726136316

Should be fixed with PixiJS v5.3.7 or higher.

**Comment by Silver-Streak** [comment] 2021-04-28 13:50
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash?

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment] 2021-06-04 08:35
Closed due to lack of steps to reproduce and no response.

**Closed by Silver-Streak** 2021-06-04 08:35 UTC
Labels: 🐛 bug
