### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Ssuar09** [4ian/GDevelop#2851] opened 2021-07-28 16:36 UTC
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: P.JsPlatform.get(...).getBehavior is not a function
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1002120
    at Array.map (<anonymous>)
    at t.a (https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1002039)
    at qi (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:104245)
    at Eo (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:111085)
    at Co (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:117833)
    at Ua (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:141827)
    at Fa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:142211)
    at Tu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149247)
    at Eu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:148627)
    at Nu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:150006)
    at Nn (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:81693)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:363571)
```

## Component stack (don't write anything here)
```

    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in j
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta110-61a969fdb1bc5aac3af1896cc376d91e4e64c2ec
* Arch: Unknown architecture (web-app),
* Platform Name: MacIntel,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36,

**Comment by Bouh** [comment] 2021-07-28 17:47
@Ssuar09  Thanks for reporting this.
What you did before is helpful in understanding the cause of the crash.
Can you list out the steps to reproduce the crash?

**Comment by 4ian** [comment] 2021-07-28 17:54
All of these getBehavior are I think (again) due to an incomplete update. Closing all tabs should fix it.

**Closed** 2021-07-29 00:17 UTC
Labels: Need a game/precise steps to reproduce the issue, 💥crash
