### ISSUE TITLE
Gdevelop delated itself

### ISSUE THREAD

**Issue by cattymations** [4ian/GDevelop#6095] opened 2023-12-17 09:32 UTC
### Describe what you were doing when the crash happened

I woke up this morning to work on my game I've been working on for multiple years now. I opened up my PC and to my dismay, Gdevelop was gone. I went to the installation directory, only to find there was nothing there.

No big deal. I'll just re-install Gdevelop.

And I did. It seemed to be working fine, until I was playtesting and one of my scenes that worked perfectly fine before, only played audio and showed nothing but a black screen.

"Okay," I thought. "I was probably an idiot and set a fade transition to go on for too long. I'll just fix that!"

And then I saw it.

An ominous message telling me something had gone wrong with the editor.

Now saving and re-loading seemed to do the trick but, I just want to know how to stop this from happening again. And what was going on the the whole delating itself thing? To be fair, I think I did do something stupid the other day that might have caused it but, I doubt it.

Thanks! -cattymations

### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: f63442dc-bd79-4539-a95b-c370db3d7ba7

Error: Error creating WebGL context.
    at new e (file:///C:/Users/auror/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:3032986)
    at n.value (file:///C:/Users/auror/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/3611.38859ce7.chunk.js:1:1396081)
    at n.value (file:///C:/Users/auror/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/3611.38859ce7.chunk.js:1:1395502)
    at ds (file:///C:/Users/auror/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:501984)
    at Fu (file:///C:/Use...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in aw
    in jw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in UM
    in div
    in n
    in Ji
    in div
    in VA
    in Unknown
    in Qe
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in me
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment] 2024-01-03 10:06
GDevelop disappearing is sometimes due to auto-updates not completing as expected.

Regarding the `Error creating WebGL context` This is a duplicate of #5956 so closing this issue.
Are you having this crash consistently?

**Closed by ClementPasteau** 2024-01-03 10:06 UTC
