### ISSUE TITLE
Games not running when using the Network Preview

### ISSUE THREAD

**Issue by Keevle** [4ian/GDevelop#1780] opened 2020-05-30 01:37 UTC
Beta 95 is completley unusable
Open any built in project and try and preview it 

runtimegame.js:21 Uncaught TypeError: gdjs.ImageManager is not a constructor
    at new gdjs.RuntimeGame (runtimegame.js:21)
    at (index):86
    at (index):98
gdjs.RuntimeGame @ runtimegame.js:21
(anonymous) @ (index):86
(anonymous) @ (index):98
(index):127 Live reload enabled.

**Comment by HarsimranVirk** [comment] 2020-05-30 06:31
I couldn't reproduce this locally, also I don't really see any problem with `gdjs.ImageManager`.
![Screenshot from 2020-05-30 11-58-26](https://user-images.githubusercontent.com/39851078/83321415-31459480-a26d-11ea-84ed-95f4548257c4.png)

**Comment by 4ian** [comment] 2020-05-30 08:58
Can you post a screenshot, confirm what is your operating system, confirm which kind of preview you are trying?
I see `Live reload enabled`, so I assume you launched Network Preview. If you used to launch it in the previous version, it's maybe possible that there is a cache issue, because the browser is caching files. Try to clear your cache and reload and see if it's better.

**Comment by Keevle** [comment] 2020-05-30 11:21
@4ian 
System info
![System info](https://i.imgur.com/J0zSUid.png)
I cleared the chache for the network preview and cleared the chache for the entire ID,what i did find while clearing the chache for the ide tho was 
![](https://i.imgur.com/sfWZenM.png)

**Comment by Keevle** [comment] 2020-05-30 11:37
ok so thanks to @arthuro555 ,I was able to figure out the issue on discord,Aparently when i installed version 95 it didnt install everything correctly,as a result no pixi.js render files were in the runtime folder

**Comment by 4ian** [comment] 2020-05-30 11:41
I'd like to better understand how it's even possible that not everything was installed properly. @arthuro555 can you help? This should never happen in any circumstances, I'd like to know the root cause of this.

**Comment by arthuro555** [comment] 2020-05-30 11:54
I have honestly no idea too. I just saw in the logs it sayed that pixi-runtime files where missing so I asked Keevle to check the directory where they are installed, and they were missing. I just zipped mine and sent them. I investigated a bit with sandboxes and tryed to replicate it but I couldn't.

**Comment by 4ian** [comment] 2020-06-01 07:48
Closing as non reproducible.

**Closed by 4ian** 2020-06-01 07:48 UTC
Labels: Need a game/precise steps to reproduce the issue
