### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Astr092** [4ian/GDevelop#6175] opened 2024-01-11 13:53 UTC
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0, Platform: MacIntel

### Additional error context

uniqueErrorId: b457d355-7ad8-49b5-8ff9-3447735a69d8

@https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:wasm-function[4198]:0x1c3d8c
initializeGDevelopJs/BehaviorMetadata.prototype.GetRequiredBehaviorTypes@https://editor.gdevelop.io/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1248064
61428/ax/y<@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:932166
61428/ax/y</<@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:932308
18455/mapVector/<@https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:2550446
t@https://editor.gdevelop.io/static/j...

### Additional component context

    in ax
    in div
    in s
    in Ay
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Wy
    in n
    in t
    in Unknown
    in Yy
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
...

**Comment by ClementPasteau** [comment] 2024-01-18 08:46
Looks like a duplicate of #5898 
What were you doing when the crash happened? Is this happening consistently?

**Closed by ClementPasteau** 2024-01-18 08:46 UTC
